// boonker/react/src/pages/badge.jsx
import React from 'react';
import {
  Navbar,
  NavRight,
  Toolbar,
  Page,
  Link,
  Badge,
  List,
  ListItem,
  Icon,
} from 'techno4-react';

export default () => (
  <Page>
    <Navbar sliding backLink="Back" title="Badge">
      <NavRight>
        <Link iconOnly>
          <Icon ios="t4:person_circle_fill" aurora="t4:person_circle_fill" md="material:person">
            <Badge color="red">5</Badge>
          </Icon>
        </Link>
      </NavRight>
    </Navbar>
    <Toolbar bottom tabbar labels>
      <Link tabLink="#tab-1" tabLinkActive>
        <Icon ios="t4:envelope_fill" aurora="t4:envelope_fill" md="material:email">
          <Badge color="green">5</Badge>
        </Icon>
        <span className="tabbar-label">Inbox</span>
      </Link>
      <Link tabLink="#tab-2">
        <Icon ios="t4:calendar_fill" aurora="t4:calendar_fill" md="material:today">
          <Badge color="red">7</Badge>
        </Icon>
        <span className="tabbar-label">Calendar</span>
      </Link>
      <Link tabLink="#tab-3">
        <Icon ios="t4:cloud_upload_fill" aurora="t4:cloud_upload_fill" md="material:file_upload">
          <Badge color="red">1</Badge>
        </Icon>
        <span className="tabbar-label">Upload</span>
      </Link>
    </Toolbar>

    <List>
      <ListItem title="Foo Bar" badge="0">
        <Icon slot="media" icon="icon-t4" />
      </ListItem>
      <ListItem title="Ivan Petrov" badge="CEO" badgeColor="blue">
        <Icon slot="media" icon="icon-t4" />
      </ListItem>
      <ListItem title="John Doe" badge="5" badgeColor="green">
        <Icon slot="media" icon="icon-t4" />
      </ListItem>
      <ListItem title="Jane Doe" badge="NEW" badgeColor="orange">
        <Icon slot="media" icon="icon-t4" />
      </ListItem>
    </List>
  </Page>
);

// boonker/vue/src/pages/badge.vue
<template>
  <t4-page>
    <t4-navbar sliding back-link="Back" title="Badge">
      <t4-nav-right>
        <t4-link icon-only>
          <t4-icon ios="t4:person_circle_fill" aurora="t4:person_circle_fill" md="material:person">
            <t4-badge color="red">5</t4-badge>
          </t4-icon>
        </t4-link>
      </t4-nav-right>
    </t4-navbar>
    <t4-toolbar bottom tabbar labels>
      <t4-link tab-link="#tab-1" tab-link-active>
        <t4-icon ios="t4:envelope_fill" aurora="t4:envelope_fill" md="material:email">
          <t4-badge color="green">5</t4-badge>
        </t4-icon>
        <span class="tabbar-label">Inbox</span>
      </t4-link>
      <t4-link tab-link="#tab-2">
        <t4-icon ios="t4:calendar_fill" aurora="t4:calendar_fill" md="material:today">
          <t4-badge color="red">7</t4-badge>
        </t4-icon>
        <span class="tabbar-label">Calendar</span>
      </t4-link>
      <t4-link tab-link="#tab-3">
        <t4-icon ios="t4:cloud_upload_fill" aurora="t4:cloud_upload_fill" md="material:file_upload">
          <t4-badge color="red">1</t4-badge>
        </t4-icon>
        <span class="tabbar-label">Upload</span>
      </t4-link>
    </t4-toolbar>

    <t4-list>
      <t4-list-item title="Foo Bar" badge="0">
        <template #media>
          <t4-icon icon="icon-t4" />
        </template>
      </t4-list-item>
      <t4-list-item title="Ivan Petrov" badge="CEO" badge-color="blue">
        <template #media>
          <t4-icon icon="icon-t4" />
        </template>
      </t4-list-item>
      <t4-list-item title="John Doe" badge="5" badge-color="green">
        <template #media>
          <t4-icon icon="icon-t4" />
        </template>
      </t4-list-item>
      <t4-list-item title="Jane Doe" badge="NEW" badge-color="orange">
        <template #media>
          <t4-icon icon="icon-t4" />
        </template>
      </t4-list-item>
    </t4-list>
  </t4-page>
</template>
<script>
import {
  t4Navbar,
  t4NavRight,
  t4Toolbar,
  t4Page,
  t4Link,
  t4Badge,
  t4List,
  t4ListItem,
  t4Icon,
} from 'techno4-vue';

export default {
  components: {
    t4Page,
    t4Navbar,
    t4NavRight,
    t4Toolbar,
    t4Link,
    t4Badge,
    t4List,
    t4ListItem,
    t4Icon,
  },
};
</script>
