// boonker/react/src/pages/routable-actions.jsx
import React from 'react';
import { Actions, ActionsLabel, ActionsGroup, ActionsButton } from 'techno4-react';

export default () => (
  <Actions>
    <ActionsGroup>
      <ActionsLabel>This Action Sheet was loaded as standalone component</ActionsLabel>
      <ActionsButton>Action 1</ActionsButton>
      <ActionsButton>Action 2</ActionsButton>
    </ActionsGroup>
    <ActionsGroup>
      <ActionsButton color="red">Cancel</ActionsButton>
    </ActionsGroup>
  </Actions>
);

// boonker/vue/src/pages/routable-actions.vue
<template>
  <t4-actions>
    <t4-actions-group>
      <t4-actions-label>This Action Sheet was loaded as standalone component</t4-actions-label>
      <t4-actions-button>Action 1</t4-actions-button>
      <t4-actions-button>Action 2</t4-actions-button>
    </t4-actions-group>
    <t4-actions-group>
      <t4-actions-button color="red">Cancel</t4-actions-button>
    </t4-actions-group>
  </t4-actions>
</template>
<script>
import { t4Actions, t4ActionsLabel, t4ActionsGroup, t4ActionsButton } from 'techno4-vue';

export default {
  components: {
    t4Actions,
    t4ActionsLabel,
    t4ActionsGroup,
    t4ActionsButton,
  },
};
</script>
