// boonker/svelte/src/pages/swiper-gallery.svelte
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-svelte';

  let swiperThumbs;
  const setSwiperThumbs = (e) => {
    const [swiper] = e.detail;
    setTimeout(() => {
      swiperThumbs = swiper;
    });
  };
</script>

<Page style="background: #000">
  <Navbar title="Two Way Control Gallery" backLink="Back" />
  <Swiper
    class="demo-swiper-gallery-top color-theme-white"
    navigation
    spaceBetween={10}
    thumbs={{ swiper: swiperThumbs }}>
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-1.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-2.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-3.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-4.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-5.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-6.jpg)" />
  </Swiper>
  <Swiper
    class="demo-swiper-gallery-thumbs"
    on:swiper={setSwiperThumbs}
    slidesPerView={4}
    spaceBetween={10}
    freeMode={true}
    watchSlidesProgress={true}
    watchSlidesVisibility={true}>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-1.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-2.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-3.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-4.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-5.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
    <SwiperSlide>
      <div
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-6.jpg)"
        class="swiper-slide-pic" />
    </SwiperSlide>
  </Swiper>
</Page>

// boonker/vue/src/pages/swiper-gallery.vue
<template>
  <t4-page style="background: #000">
    <t4-navbar title="Thumbs Gallery" back-link="Back"></t4-navbar>
    <t4-swiper
      class="demo-swiper-gallery-top color-theme-white"
      :space-between="10"
      navigation
      :thumbs="{
        swiper: swiperThumbs,
      }"
    >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-1.jpg)"
      />
      >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-2.jpg)"
      />
      >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-3.jpg)"
      />
      >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-4.jpg)"
      />
      >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-5.jpg)"
      />
      >
      <t4-swiper-slide
        style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-6.jpg)"
      />
      >
    </t4-swiper>
    <t4-swiper
      class="demo-swiper-gallery-thumbs"
      :slides-per-view="4"
      :space-between="10"
      :free-mode="true"
      :watch-slides-progress="true"
      :watch-slides-visibility="true"
      @swiper="swiperThumbs = $event"
    >
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-1.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-2.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-3.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-4.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-5.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
      <t4-swiper-slide>
        <div
          style="background-image: url(https://cdn.techno4.io/placeholder/nature-800x800-6.jpg)"
          class="swiper-slide-pic"
        />
      </t4-swiper-slide>
    </t4-swiper>
  </t4-page>
</template>
<script>
import { t4Navbar, t4Page, t4Swiper, t4SwiperSlide } from 'techno4-vue';

export default {
  components: {
    t4Navbar,
    t4Page,
    t4Swiper,
    t4SwiperSlide,
  },
  data() {
    return {
      swiperThumbs: null,
    };
  },
};
</script>
