// boonker/react/src/pages/swiper-horizontal.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Swiper Horizontal" backLink="Back"></Navbar>
    <Swiper className="demo-swiper" pagination={{ hideOnClick: true }}>
      <SwiperSlide>Slide 1</SwiperSlide>
      <SwiperSlide>Slide 2</SwiperSlide>
      <SwiperSlide>Slide 3</SwiperSlide>
      <SwiperSlide>Slide 4</SwiperSlide>
      <SwiperSlide>Slide 5</SwiperSlide>
      <SwiperSlide>Slide 6</SwiperSlide>
      <SwiperSlide>Slide 7</SwiperSlide>
      <SwiperSlide>Slide 8</SwiperSlide>
      <SwiperSlide>Slide 9</SwiperSlide>
      <SwiperSlide>Slide 10</SwiperSlide>
    </Swiper>
  </Page>
);

// boonker/vue/src/pages/swiper-horizontal.vue
<template>
  <t4-page>
    <t4-navbar title="Swiper Horizontal" back-link="Back"></t4-navbar>
    <t4-swiper :pagination="{ hideOnClick: true }" class="demo-swiper">
      <t4-swiper-slide>Slide 1</t4-swiper-slide>
      <t4-swiper-slide>Slide 2</t4-swiper-slide>
      <t4-swiper-slide>Slide 3</t4-swiper-slide>
      <t4-swiper-slide>Slide 4</t4-swiper-slide>
      <t4-swiper-slide>Slide 5</t4-swiper-slide>
      <t4-swiper-slide>Slide 6</t4-swiper-slide>
      <t4-swiper-slide>Slide 7</t4-swiper-slide>
      <t4-swiper-slide>Slide 8</t4-swiper-slide>
      <t4-swiper-slide>Slide 9</t4-swiper-slide>
      <t4-swiper-slide>Slide 10</t4-swiper-slide>
    </t4-swiper>
  </t4-page>
</template>
<script>
import { t4Navbar, t4Page, t4Swiper, t4SwiperSlide } from 'techno4-vue';

export default {
  components: {
    t4Navbar,
    t4Page,
    t4Swiper,
    t4SwiperSlide,
  },
};
</script>
