// boonker/react/src/pages/timeline.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Timeline" backLink="Back"></Navbar>
    <List>
      <ListItem link="/timeline-vertical/" title="Vertical Timeline" />
      <ListItem link="/timeline-horizontal/" title="Horizontal Timeline" />
      <ListItem link="/timeline-horizontal-calendar/" title="Calendar Timeline" />
    </List>
  </Page>
);

// boonker/vue/src/pages/timeline.vue
<template>
  <t4-page>
    <t4-navbar title="Timeline" back-link="Back"></t4-navbar>
    <t4-list>
      <t4-list-item link="/timeline-vertical/" title="Vertical Timeline" />
      <t4-list-item link="/timeline-horizontal/" title="Horizontal Timeline" />
      <t4-list-item link="/timeline-horizontal-calendar/" title="Calendar Timeline" />
    </t4-list>
  </t4-page>
</template>
<script>
import { t4Navbar, t4Page, t4List, t4ListItem } from 'techno4-vue';

export default {
  components: {
    t4Navbar,
    t4Page,
    t4List,
    t4ListItem,
  },
};
</script>
