// src/svelte/components/card.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';

  import CardHeader from './card-header.svelte';
  import CardContent from './card-content.svelte';
  import CardFooter from './card-footer.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let title = undefined;
  export let content = undefined;
  export let footer = undefined;
  export let outline = false;
  export let expandable = false;
  export let expandableAnimateWidth = false;
  export let expandableOpened = false;
  export let animate = undefined;
  export let hideNavbarOnOpen = undefined;
  export let hideToolbarOnOpen = undefined;
  export let hideStatusbarOnOpen = undefined;
  export let scrollableEl = undefined;
  export let swipeToClose = undefined;
  export let closeByBackdropClick = undefined;
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let noShadow = false;
  export let noBorder = false;
  export let padding = true;

  let el;

  $: classes = classNames(
    className,
    'card',
    {
      'card-outline': outline,
      'card-expandable': expandable,
      'card-expandable-animate-width': expandableAnimateWidth,
      'no-shadow': noShadow,
      'no-border': noBorder,
    },
    colorClasses($$props),
  );

  /* eslint-disable no-undef */
  $: hasHeaderSlots = $$slots.header;
  $: hasContentSlots = $$slots.content;
  $: hasFooterSlots = $$slots.footer;
  /* eslint-enable no-undef */

  function open() {
    app.t4.card.open(el);
  }

  function close() {
    app.t4.card.close(el);
  }

  let initialWatched = false;
  function watchOpened(openedPassed) {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (openedPassed) {
      open();
    } else {
      close();
    }
  }

  $: watchOpened(expandableOpened);

  function onBeforeOpen(cardEl, prevent) {
    if (cardEl !== el) return;
    emit('cardBeforeOpen', [el, prevent]);
  }
  function onOpen(cardEl) {
    if (cardEl !== el) return;
    emit('cardOpen', [el]);
    expandableOpened = true;
  }
  function onOpened(cardEl, pageEl) {
    if (cardEl !== el) return;
    emit('cardOpened', [el, pageEl]);
  }
  function onClose(cardEl) {
    if (cardEl !== el) return;
    emit('cardClose', [el]);
  }
  function onClosed(cardEl, pageEl) {
    if (cardEl !== el) return;
    emit('cardClosed', [el, pageEl]);
    expandableOpened = false;
  }

  onMount(() => {
    if (!expandable) return;
    t4ready(() => {
      app.t4.on('cardBeforeOpen', onBeforeOpen);
      app.t4.on('cardOpen', onOpen);
      app.t4.on('cardOpened', onOpened);
      app.t4.on('cardClose', onClose);
      app.t4.on('cardClosed', onClosed);
      if (expandable && expandableOpened && el) {
        app.t4.card.open(el, false);
      }
    });
  });

  onDestroy(() => {
    if (!expandable) return;
    if (!app.t4 || !el) return;
    app.t4.off('cardBeforeOpen', onBeforeOpen);
    app.t4.off('cardOpen', onOpen);
    app.t4.off('cardOpened', onOpened);
    app.t4.off('cardClose', onClose);
    app.t4.off('cardClosed', onClosed);
  });
</script>

<div
  bind:this={el}
  class={classes}
  data-animate={typeof animate === 'undefined' ? animate : animate.toString()}
  data-hide-navbar-on-open={typeof hideNavbarOnOpen === 'undefined'
    ? hideNavbarOnOpen
    : hideNavbarOnOpen.toString()}
  data-hide-toolbar-on-open={typeof hideToolbarOnOpen === 'undefined'
    ? hideToolbarOnOpen
    : hideToolbarOnOpen.toString()}
  data-hide-statusbar-on-open={typeof hideStatusbarOnOpen === 'undefined'
    ? hideStatusbarOnOpen
    : hideStatusbarOnOpen.toString()}
  data-scrollable-el={scrollableEl}
  data-swipe-to-close={typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()}
  data-close-by-backdrop-click={typeof closeByBackdropClick === 'undefined'
    ? closeByBackdropClick
    : closeByBackdropClick.toString()}
  data-backdrop={typeof backdrop === 'undefined' ? backdrop : backdrop.toString()}
  data-backdrop-el={backdropEl}
  {...restProps($$restProps)}
>
  {#if typeof title !== 'undefined' || hasHeaderSlots}
    <CardHeader>
      {plainText(title)}
      <slot name="header" />
    </CardHeader>
  {/if}
  {#if typeof content !== 'undefined' || hasContentSlots}
    <CardContent {padding}>
      {plainText(content)}
      <slot name="content" />
    </CardContent>
  {/if}
  {#if typeof footer !== 'undefined' || hasFooterSlots}
    <CardFooter>
      {plainText(footer)}
      <slot name="footer" />
    </CardFooter>
  {/if}
  <slot />
</div>

// src/vue/components/card.vue
<template>
  <div
    ref="elRef"
    :class="classes"
    :data-animate="typeof animate === 'undefined' ? animate : animate.toString()"
    :data-hide-navbar-on-open="
      typeof hideNavbarOnOpen === 'undefined' ? hideNavbarOnOpen : hideNavbarOnOpen.toString()
    "
    :data-hide-toolbar-on-open="
      typeof hideToolbarOnOpen === 'undefined' ? hideToolbarOnOpen : hideToolbarOnOpen.toString()
    "
    :data-hide-statusbar-on-open="
      typeof hideStatusbarOnOpen === 'undefined'
        ? hideStatusbarOnOpen
        : hideStatusbarOnOpen.toString()
    "
    :data-scrollable-el="scrollableEl"
    :data-swipe-to-close="
      typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()
    "
    :data-close-by-backdrop-click="
      typeof closeByBackdropClick === 'undefined'
        ? closeByBackdropClick
        : closeByBackdropClick.toString()
    "
    :data-backdrop="typeof backdrop === 'undefined' ? backdrop : backdrop.toString()"
    :data-backdrop-el="backdropEl"
  >
    <t4-card-header v-if="hasHeader">
      {{ title }}
      <slot name="header" />
    </t4-card-header>
    <t4-card-content v-if="hasContent" :padding="padding">
      {{ content }}
      <slot name="content" />
    </t4-card-content>
    <t4-card-footer v-if="hasFooter">
      {{ footer }}
      <slot name="footer" />
    </t4-card-footer>
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4, t4ready } from '../shared/t4.js';

import t4CardHeader from './card-header.js';
import t4CardContent from './card-content.js';
import t4CardFooter from './card-footer.js';

export default {
  name: 't4-card',
  components: {
    t4CardHeader,
    t4CardContent,
    t4CardFooter,
  },
  props: {
    title: [String, Number],
    content: [String, Number],
    footer: [String, Number],
    outline: Boolean,
    expandable: Boolean,
    expandableAnimateWidth: Boolean,
    expandableOpened: Boolean,
    animate: {
      type: Boolean,
      default: undefined,
    },
    hideNavbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    hideToolbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    hideStatusbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    scrollableEl: {
      type: String,
      default: undefined,
    },
    swipeToClose: {
      type: Boolean,
      default: undefined,
    },
    closeByBackdropClick: {
      type: Boolean,
      default: undefined,
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    backdropEl: {
      type: String,
      default: undefined,
    },
    noShadow: Boolean,
    noBorder: Boolean,
    padding: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  emits: [
    'card:beforeopen',
    'card:open',
    'card:opened',
    'card:close',
    'card:closed',
    'update:expandableOpened',
  ],
  setup(props, { emit, slots }) {
    const elRef = ref(null);

    const open = () => {
      if (!elRef.value) return;
      t4.card.open(elRef.value);
    };
    const close = () => {
      if (!elRef.value) return;
      t4.card.close(elRef.value);
    };
    const onBeforeOpen = (el, prevent) => {
      if (elRef.value !== el) return;
      emit('card:beforeopen', el, prevent);
    };
    const onOpen = (el) => {
      if (elRef.value !== el) return;
      emit('card:open', el);
      emit('update:expandableOpened', true);
    };
    const onOpened = (el, pageEl) => {
      if (elRef.value !== el) return;
      emit('card:opened', el, pageEl);
    };
    const onClose = (el) => {
      if (elRef.value !== el) return;
      emit('card:close', el);
    };
    const onClosed = (el, pageEl) => {
      if (elRef.value !== el) return;
      emit('card:closed', el, pageEl);
      emit('update:expandableOpened', false);
    };

    onMounted(() => {
      if (!props.expandable || !elRef.value) return;
      t4ready(() => {
        if (props.expandable && props.expandableOpened) {
          t4.card.open(elRef.value, false);
        }
        t4.on('cardBeforeOpen', onBeforeOpen);
        t4.on('cardOpen', onOpen);
        t4.on('cardOpened', onOpened);
        t4.on('cardClose', onClose);
        t4.on('cardClosed', onClosed);
      });
    });

    onBeforeUnmount(() => {
      t4.off('cardBeforeOpen', onBeforeOpen);
      t4.off('cardOpen', onOpen);
      t4.off('cardOpened', onOpened);
      t4.off('cardClose', onClose);
      t4.off('cardClosed', onClosed);
    });

    watch(
      () => props.expandableOpened,
      (value) => {
        if (value) {
          open();
        } else {
          close();
        }
      },
    );

    const hasHeader = computed(() => props.title || slots.header);
    const hasContent = computed(() => props.content || slots.content);
    const hasFooter = computed(() => props.footer || slots.footer);

    const classes = computed(() =>
      classNames(
        'card',
        {
          'card-outline': props.outline,
          'card-expandable': props.expandable,
          'card-expandable-animate-width': props.expandableAnimateWidth,
          'no-shadow': props.noShadow,
          'no-border': props.noBorder,
        },
        colorClasses(props),
      ),
    );
    return {
      elRef,
      classes,
      hasHeader,
      hasContent,
      hasFooter,
    };
  },
};
</script>
