// src/svelte/components/fab-backdrop.svelte
<script>
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  export let t4Slot = 'fixed';

  $: classes = classNames(className, 'fab-backdrop');
</script>

<div class={classes} data-t4-slot={t4Slot} {...restProps($$restProps)} />

// src/vue/components/fab-backdrop.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-fab-backdrop',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('fab-backdrop', colorClasses(props)));
    return { classes };
  },
};
</script>
