// src/react/components/fab-button.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  fabClose? : boolean;
  label? : string;
  target? : string;
  tooltip? : string;
  tooltipTrigger? : string;
  onClick? : (event?: any) => void;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const FabButton = forwardRef((props, ref) => {
  const { className, id, style, children, fabClose, label, target } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useTooltip(elRef, props);

  const classes = classNames(
    className,
    {
      'fab-close': fabClose,
      'fab-label-button': label,
    },
    colorClasses(props),
  );

  let labelEl;
  if (label) {
    labelEl = <span className="fab-label">{label}</span>;
  }

  return (
    <a
      id={id}
      style={style}
      target={target}
      className={classes}
      ref={elRef}
      {...extraAttrs}
      onClick={onClick}
    >
      {children}
      {labelEl}
    </a>
  );
});

FabButton.displayName = 't4-fab-button';

export default FabButton;

// src/vue/components/fab-button.vue
<template>
  <a ref="elRef" :class="classes" :target="target" @click="onClick">
    <slot />
    <span v-if="label" class="fab-label">{{ label }}</span>
  </a>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

export default {
  name: 't4-fab-button',
  props: {
    fabClose: Boolean,
    label: String,
    target: String,
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const elRef = ref(null);

    const onClick = (e) => {
      emit('click', e);
    };

    useTooltip(elRef, props);

    const classes = computed(() =>
      classNames(
        {
          'fab-close': props.fabClose,
          'fab-label-button': props.label,
        },
        colorClasses(props),
      ),
    );
    return { classes, onClick, elRef };
  },
};
</script>
