// src/svelte/components/fab.svelte
<script>
  import { createEventDispatcher, onMount, afterUpdate } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';
  import { useTooltip } from '../shared/use-tooltip.js';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let morphTo = undefined;
  export let href = undefined;
  export let target = undefined;
  export let text = undefined;
  export let position = 'right-bottom';
  export let tooltip = undefined;
  export let tooltipTrigger = undefined;
  export let t4Slot = 'fixed';

  let el;
  let linkEl;
  let textEl;

  $: hrefComputed = href === true ? '#' : href || undefined;

  // eslint-disable-next-line
  $: hasTextSlots = $$slots.text;

  $: classes = classNames(
    className,
    'fab',
    `fab-${position}`,
    {
      'fab-morph': morphTo,
      'fab-extended': text || hasTextSlots || typeof textEl !== 'undefined',
    },
    colorClasses($$props),
  );

  function onClick() {
    emit('click');
  }

  onMount(() => {
    t4ready(() => {
      const dom64 = app.t4.$;
      const rootEls = dom64(linkEl).children('.fab-buttons');
      if (rootEls.length) {
        dom64(el).append(rootEls);
      }
    });
  });
  afterUpdate(() => {
    if (!app.t4) return;
    const dom64 = app.t4.$;
    const rootEls = dom64(linkEl).children('.fab-buttons');
    if (rootEls.length) {
      dom64(el).append(rootEls);
    }
  });
</script>

<div
  class={classes}
  data-morph-to={morphTo}
  bind:this={el}
  data-t4-slot={t4Slot}
  {...restProps($$restProps)}
>
  <a
    bind:this={linkEl}
    on:click={onClick}
    {target}
    href={hrefComputed}
    use:useTooltip={{ tooltip, tooltipTrigger }}
  >
    <slot />
    {#if typeof text !== 'undefined' || hasTextSlots}
      <div class="fab-text" bind:this={textEl}>
        {plainText(text)}
        <slot name="text" />
      </div>
    {/if}
    <slot name="link" />
  </a>
  <slot name="root" />
</div>

// src/vue/components/fab.vue
<script>
import { h, computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

export default {
  name: 't4-fab',
  props: {
    morphTo: String,
    href: [Boolean, String],
    target: String,
    text: String,
    position: {
      type: String,
      default: 'right-bottom',
    },
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit, slots }) {
    const elRef = ref(null);

    const onClick = (e) => {
      emit('click', e);
    };

    useTooltip(elRef, props);

    const hrefComputed = computed(() => {
      let href = props.href;
      if (href === true) href = '#';
      if (href === false) href = undefined; // no href attribute
      return href;
    });

    return () => {
      const linkChildren = [];
      const rootChildren = [];
      let textEl;
      let linkEl;

      const { link: linkSlots, default: defaultSlots, root: rootSlots, text: textSlots } = slots;

      if (defaultSlots) {
        defaultSlots().forEach((vnode) => {
          if (typeof vnode === 'undefined') return;
          const tag = vnode.type && vnode.type.name ? vnode.type.name : vnode.type;
          if (tag === 'FabButtons' || tag === 't4-fab-buttons') rootChildren.push(vnode);
          else linkChildren.push(vnode);
        });
      }
      if (props.text || textSlots) {
        textEl = h('div', { class: 'fab-text' }, [props.text, textSlots && textSlots()]);
      }
      if (linkChildren.length || linkSlots || textEl) {
        linkEl = h('a', { target: props.target, href: hrefComputed.value, onClick }, [
          linkChildren,
          textEl,
          linkSlots && linkSlots(),
        ]);
      }
      const classes = classNames(
        'fab',
        `fab-${props.position}`,
        {
          'fab-morph': props.morphTo,
          'fab-extended': typeof textEl !== 'undefined',
        },
        colorClasses(props),
      );
      return h(
        'div',
        {
          class: classes,
          'data-morph-to': props.morphTo,
          ref: elRef,
        },
        [linkEl, rootChildren, rootSlots && rootSlots()],
      );
    };
  },
};
</script>
