// src/svelte/components/input.svelte
<script>
  import { createEventDispatcher, onMount, afterUpdate, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';
  import Toggle from './toggle.svelte';
  import Range from './range.svelte';
  import TextEditor from './text-editor.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let type = undefined;
  export let name = undefined;
  export let value = undefined;
  export let placeholder = undefined;
  export let inputId = undefined;
  export let size = undefined;
  export let accept = undefined;
  export let autocomplete = undefined;
  export let autocorrect = undefined;
  export let autocapitalize = undefined;
  export let spellcheck = undefined;
  export let autofocus = undefined;
  export let autosave = undefined;
  export let checked = undefined;
  export let disabled = undefined;
  export let max = undefined;
  export let min = undefined;
  export let step = undefined;
  export let maxlength = undefined;
  export let minlength = undefined;
  export let multiple = undefined;
  export let readonly = undefined;
  export let required = undefined;
  export let inputStyle = undefined;
  export let pattern = undefined;
  export let validate = undefined;
  export let validateOnBlur = undefined;
  export let onValidate = undefined;
  export let tabindex = undefined;
  export let resizable = undefined;
  export let clearButton = undefined;

  // Form
  export let noFormStoreData = undefined;
  export let noStoreData = undefined;
  export let ignoreStoreData = undefined;

  // Error, Info
  export let errorMessage = undefined;
  export let errorMessageForce = undefined;
  export let info = undefined;

  // Outline
  export let outline = undefined;

  // Components
  export let wrap = true;
  export let dropdown = 'auto';

  // Datepicker
  export let calendarParams = undefined;
  // Colorpicker
  export let colorPickerParams = undefined;
  // Text editor
  export let textEditorParams = undefined;

  // State
  let inputEl;
  let inputFocused = false;
  let inputInvalid = false;
  let updateInputOnDidUpdate = false;
  let t4Calendar;
  let t4ColorPicker;

  function domValue() {
    if (!inputEl) return undefined;
    return inputEl.value;
  }

  function inputHasValue() {
    if (type === 'datepicker' && Array.isArray(value) && value.length === 0) {
      return false;
    }
    const domV = domValue();
    return typeof value === 'undefined' ? domV || domV === 0 : value || value === 0;
  }

  function validateInput() {
    if (!app.t4 || !inputEl) return;
    const validity = inputEl.validity;
    if (!validity) return;

    if (!validity.valid) {
      if (onValidate) onValidate(false);
      if (inputInvalid !== true) {
        inputInvalid = true;
      }
    } else {
      if (onValidate) onValidate(true);
      if (inputInvalid !== false) {
        inputInvalid = false;
      }
    }
  }

  let initialWatched = false;
  function watchValue() {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (type === 'range' || type === 'toggle') return;
    if (!app.t4) return;
    updateInputOnDidUpdate = true;
    if (t4Calendar) {
      t4Calendar.setValue(value);
    }
    if (t4ColorPicker) {
      t4ColorPicker.setValue(value);
    }
  }

  $: watchValue(value);

  $: inputType = type === 'datepicker' || type === 'colorpicker' ? 'text' : type;

  $: needsValue = type !== 'file' && type !== 'datepicker' && type !== 'colorpicker';

  $: inputValue = (() => {
    let v;
    if (typeof value !== 'undefined') {
      v = value;
    } else {
      v = domValue();
    }
    if (typeof v === 'undefined' || v === null) return '';
    return v;
  })();

  $: classes = classNames(!wrap && className, {
    resizable: inputType === 'textarea' && resizable,
    'no-store-data': noFormStoreData || noStoreData || ignoreStoreData,
    'input-invalid': (errorMessage && errorMessageForce) || inputInvalid,
    'input-with-value': inputHasValue(),
    'input-focused': inputFocused,
  });

  $: wrapClasses = classNames(
    className,
    'input',
    {
      'input-outline': outline,
      'input-dropdown': dropdown === 'auto' ? type === 'select' : dropdown,
      'input-invalid': (errorMessage && errorMessageForce) || inputInvalid,
    },
    colorClasses($$props),
  );

  $: inputClassName = classNames(!wrap && className, {
    resizable: inputType === 'textarea' && resizable,
    'no-store-data': noFormStoreData || noStoreData || ignoreStoreData,
    'input-invalid': (errorMessage && errorMessageForce) || inputInvalid,
    'input-with-value': inputHasValue(),
    'input-focused': inputFocused,
  });

  // eslint-disable-next-line
  $: hasInfoSlots = $$slots.info;
  // eslint-disable-next-line
  $: hasErrorSlots = $$slots['error-message'];

  function onTextareaResize(event) {
    emit('textareaResize', [event]);
  }

  function onInputNotEmpty(event) {
    emit('inputNotEmpty', [event]);
  }

  function onInputEmpty(event) {
    emit('inputEmpty', [event]);
  }

  function onInputClear(event) {
    emit('inputClear', [event]);
  }

  function onInput(...args) {
    emit('input', [...args]);

    if (!(validateOnBlur || validateOnBlur === '') && (validate || validate === '') && inputEl) {
      validateInput(inputEl);
    }
    if (inputEl && type !== 'texteditor' && type !== 'colorpicker' && type !== 'datepicker') {
      value = inputEl.value;
    }
  }

  function onFocus(...args) {
    emit('focus', [...args]);

    inputFocused = true;
  }

  function onBlur(...args) {
    emit('blur', [...args]);

    if ((validate || validate === '' || validateOnBlur || validateOnBlur === '') && inputEl) {
      validateInput();
    }
    inputFocused = false;
  }

  function onChange(...args) {
    emit('change', [...args]);

    if (type === 'texteditor') {
      emit('textEditorChange', [args[1]]);
      value = args[1];
    }
  }

  onMount(() => {
    t4ready(() => {
      if (type === 'range' || type === 'toggle') return;
      if (!inputEl) return;

      inputEl.addEventListener('input:notempty', onInputNotEmpty, false);
      if (type === 'textarea' && resizable) {
        inputEl.addEventListener('textarea:resize', onTextareaResize, false);
      }
      if (clearButton) {
        inputEl.addEventListener('input:empty', onInputEmpty, false);
        inputEl.addEventListener('input:clear', onInputClear, false);
      }

      if (type === 'datepicker') {
        t4Calendar = app.t4.calendar.create({
          inputEl,
          value,
          on: {
            change(calendar, calendarValue) {
              emit('calendarChange', [calendarValue]);
              value = calendarValue;
            },
          },
          ...(calendarParams || {}),
        });
      }
      if (type === 'colorpicker') {
        t4ColorPicker = app.t4.colorPicker.create({
          inputEl,
          value,
          on: {
            change(colorPicker, colorPickerValue) {
              emit('colorpickerChange', [colorPickerValue]);
              value = colorPickerValue;
            },
          },
          ...(colorPickerParams || {}),
        });
      }

      app.t4.input.checkEmptyState(inputEl);
      if (
        !(validateOnBlur || validateOnBlur === '') &&
        (validate || validate === '') &&
        typeof value !== 'undefined' &&
        value !== null &&
        value !== ''
      ) {
        setTimeout(() => {
          validateInput();
        }, 0);
      }
      if (resizable) {
        app.t4.input.resizeTextarea(inputEl);
      }
    });
  });

  afterUpdate(() => {
    if (!app.t4) return;
    if (updateInputOnDidUpdate) {
      if (!inputEl) return;
      updateInputOnDidUpdate = false;
      app.t4.input.checkEmptyState(inputEl);
      if (validate && !validateOnBlur) {
        validateInput();
      }
      if (resizable) {
        app.t4.input.resizeTextarea(inputEl);
      }
    }
  });

  onDestroy(() => {
    if (type === 'range' || type === 'toggle') return;
    if (!inputEl) return;
    inputEl.removeEventListener('input:notempty', onInputNotEmpty, false);
    if (type === 'textarea' && resizable) {
      inputEl.removeEventListener('textarea:resize', onTextareaResize, false);
    }
    if (clearButton) {
      inputEl.removeEventListener('input:empty', onInputEmpty, false);
      inputEl.removeEventListener('input:clear', onInputClear, false);
    }

    if (t4Calendar && t4Calendar.destroy) {
      t4Calendar.destroy();
    }
    if (t4ColorPicker && t4ColorPicker.destroy) {
      t4ColorPicker.destroy();
    }
    t4Calendar = null;
    t4ColorPicker = null;
  });
</script>

<!-- svelte-ignore a11y-autofocus -->
{#if wrap}
  <div class={wrapClasses} {...restProps($$restProps)}>
    {#if type === 'select'}
      <select
        bind:this={inputEl}
        style={inputStyle}
        {name}
        {placeholder}
        id={inputId}
        {size}
        {accept}
        {autocomplete}
        {autocorrect}
        {autocapitalize}
        {spellcheck}
        {autofocus}
        {autosave}
        {checked}
        {disabled}
        {max}
        {maxlength}
        {min}
        {minlength}
        {step}
        {multiple}
        {readonly}
        {required}
        {pattern}
        validate={typeof validate === 'string' && validate.length ? validate : undefined}
        data-validate={validate === true ||
        validate === '' ||
        validateOnBlur === true ||
        validateOnBlur === ''
          ? true
          : undefined}
        data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
        {tabindex}
        data-error-message={errorMessageForce ? undefined : errorMessage}
        class={inputClassName}
        on:focus={onFocus}
        on:blur={onBlur}
        on:input={onInput}
        on:change={onChange}
        value={inputValue}
      >
        <slot />
      </select>
    {:else if type === 'textarea'}
      <textarea
        bind:this={inputEl}
        style={inputStyle}
        {name}
        {placeholder}
        id={inputId}
        {size}
        {accept}
        {autocomplete}
        {autocorrect}
        {autocapitalize}
        {spellcheck}
        {autofocus}
        {autosave}
        {checked}
        {disabled}
        {max}
        {maxlength}
        {min}
        {minlength}
        {step}
        {multiple}
        {readonly}
        {required}
        {pattern}
        validate={typeof validate === 'string' && validate.length ? validate : undefined}
        data-validate={validate === true ||
        validate === '' ||
        validateOnBlur === true ||
        validateOnBlur === ''
          ? true
          : undefined}
        data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
        {tabindex}
        data-error-message={errorMessageForce ? undefined : errorMessage}
        class={inputClassName}
        on:focus={onFocus}
        on:blur={onBlur}
        on:input={onInput}
        on:change={onChange}
        value={inputValue}
      />
    {:else if type === 'toggle'}
      <Toggle {checked} {readonly} {name} {value} {disabled} id={inputId} on:change={onChange} />
    {:else if type === 'range'}
      <Range
        {value}
        {disabled}
        {min}
        {max}
        {step}
        {name}
        id={inputId}
        input={true}
        on:rangeChange={onChange}
      />
    {:else if type === 'texteditor'}
      <TextEditor
        value={typeof value === 'undefined' ? '' : value}
        {resizable}
        {placeholder}
        onTextEditorFocus={onFocus}
        onTextEditorBlur={onBlur}
        onTextEditorInput={onInput}
        onTextEditorChange={onChange}
        {...textEditorParams}
      />
    {:else}
      <input
        bind:this={inputEl}
        style={inputStyle}
        {name}
        type={inputType}
        {placeholder}
        id={inputId}
        {size}
        {accept}
        {autocomplete}
        {autocorrect}
        {autocapitalize}
        {spellcheck}
        {autofocus}
        {autosave}
        {checked}
        {disabled}
        {max}
        {maxlength}
        {min}
        {minlength}
        {step}
        {multiple}
        {readonly}
        {required}
        {pattern}
        validate={typeof validate === 'string' && validate.length ? validate : undefined}
        data-validate={validate === true ||
        validate === '' ||
        validateOnBlur === true ||
        validateOnBlur === ''
          ? true
          : undefined}
        data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
        tabIndex={tabindex}
        data-error-message={errorMessageForce ? undefined : errorMessage}
        class={inputClassName}
        on:focus={onFocus}
        on:blur={onBlur}
        on:input={onInput}
        on:change={onChange}
        value={type === 'datepicker' || type === 'colorpicker' || type === 'file' ? '' : inputValue}
      />
    {/if}
    {#if (errorMessage || hasErrorSlots) && errorMessageForce}
      <div class="input-error-message">
        {errorMessage}
        <slot name="error-message" />
      </div>
    {/if}
    {#if clearButton}<span class="input-clear-button" />{/if}
    {#if info || hasInfoSlots}
      <div class="input-info">
        {info}
        <slot name="info" />
      </div>
    {/if}
  </div>
{:else if type === 'select'}
  <select
    bind:this={inputEl}
    style={inputStyle}
    {name}
    {placeholder}
    id={inputId}
    {size}
    {accept}
    {autocomplete}
    {autocorrect}
    {autocapitalize}
    {spellcheck}
    {autofocus}
    {autosave}
    {checked}
    {disabled}
    {max}
    {maxlength}
    {min}
    {minlength}
    {step}
    {multiple}
    {readonly}
    {required}
    {pattern}
    validate={typeof validate === 'string' && validate.length ? validate : undefined}
    data-validate={validate === true ||
    validate === '' ||
    validateOnBlur === true ||
    validateOnBlur === ''
      ? true
      : undefined}
    data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
    {tabindex}
    data-error-message={errorMessageForce ? undefined : errorMessage}
    class={inputClassName}
    on:focus={onFocus}
    on:blur={onBlur}
    on:input={onInput}
    on:change={onChange}
    value={inputValue}
    {...restProps($$restProps)}
  >
    <slot />
  </select>
{:else if type === 'textarea'}
  <textarea
    bind:this={inputEl}
    style={inputStyle}
    {name}
    {placeholder}
    id={inputId}
    {size}
    {accept}
    {autocomplete}
    {autocorrect}
    {autocapitalize}
    {spellcheck}
    {autofocus}
    {autosave}
    {checked}
    {disabled}
    {max}
    {maxlength}
    {min}
    {minlength}
    {step}
    {multiple}
    {readonly}
    {required}
    {pattern}
    validate={typeof validate === 'string' && validate.length ? validate : undefined}
    data-validate={validate === true ||
    validate === '' ||
    validateOnBlur === true ||
    validateOnBlur === ''
      ? true
      : undefined}
    data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
    {tabindex}
    data-error-message={errorMessageForce ? undefined : errorMessage}
    class={inputClassName}
    on:focus={onFocus}
    on:blur={onBlur}
    on:input={onInput}
    on:change={onChange}
    value={inputValue}
    {...restProps($$restProps)}
  />
{:else if type === 'toggle'}
  <Toggle
    {checked}
    {readonly}
    {name}
    {value}
    {disabled}
    id={inputId}
    on:change={onChange}
    {...restProps($$restProps)}
  />
{:else if type === 'range'}
  <Range
    {value}
    {disabled}
    {min}
    {max}
    {step}
    {name}
    id={inputId}
    input={true}
    on:rangeChange={onChange}
    {...restProps($$restProps)}
  />
{:else if type === 'texteditor'}
  <TextEditor
    value={typeof value === 'undefined' ? '' : value}
    {resizable}
    {placeholder}
    onTextEditorFocus={onFocus}
    onTextEditorBlur={onBlur}
    onTextEditorInput={onInput}
    onTextEditorChange={onChange}
    {...textEditorParams}
    {...restProps($$restProps)}
  />
{:else}
  <input
    bind:this={inputEl}
    style={inputStyle}
    {name}
    type={inputType}
    {placeholder}
    id={inputId}
    {size}
    {accept}
    {autocomplete}
    {autocorrect}
    {autocapitalize}
    {spellcheck}
    {autofocus}
    {autosave}
    {checked}
    {disabled}
    {max}
    {maxlength}
    {min}
    {minlength}
    {step}
    {multiple}
    {readonly}
    {required}
    {pattern}
    validate={typeof validate === 'string' && validate.length ? validate : undefined}
    data-validate={validate === true ||
    validate === '' ||
    validateOnBlur === true ||
    validateOnBlur === ''
      ? true
      : undefined}
    data-validate-on-blur={validateOnBlur === true || validateOnBlur === '' ? true : undefined}
    tabIndex={tabindex}
    data-error-message={errorMessageForce ? undefined : errorMessage}
    class={inputClassName}
    on:focus={onFocus}
    on:blur={onBlur}
    on:input={onInput}
    on:change={onChange}
    value={type === 'datepicker' || type === 'colorpicker' || type === 'file' ? '' : inputValue}
    {...restProps($$restProps)}
  />
{/if}

// src/vue/components/input.vue
<script>
import { computed, ref, onMounted, onBeforeUnmount, h, watch, onUpdated } from 'vue';
import { classNames, extend, noUndefinedProps } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';

import t4Toggle from './toggle.js';
import t4Range from './range.js';
import t4TextEditor from './text-editor.js';

export default {
  name: 't4-input',
  props: {
    type: String,
    name: String,
    value: {
      type: [String, Number, Array, Date, Object],
      default: undefined,
    },
    inputmode: String,
    placeholder: String,
    inputId: [String, Number],
    size: [String, Number],
    accept: [String, Number],
    autocomplete: [String],
    autocorrect: [String],
    autocapitalize: [String],
    spellcheck: [String],
    autofocus: Boolean,
    autosave: String,
    checked: Boolean,
    disabled: Boolean,
    max: [String, Number],
    min: [String, Number],
    step: [String, Number],
    maxlength: [String, Number],
    minlength: [String, Number],
    multiple: Boolean,
    readonly: Boolean,
    required: Boolean,
    inputStyle: [String, Object],
    pattern: String,
    validate: [Boolean, String],
    validateOnBlur: Boolean,
    onValidate: Function,
    tabindex: [String, Number],
    resizable: Boolean,
    clearButton: Boolean,

    // Form
    noFormStoreData: Boolean,
    noStoreData: Boolean,
    ignoreStoreData: Boolean,

    // Error, Info
    errorMessage: String,
    errorMessageForce: Boolean,
    info: String,

    // Outline
    outline: Boolean,

    // Components
    wrap: {
      type: Boolean,
      default: true,
    },
    dropdown: {
      type: [String, Boolean],
      default: 'auto',
    },

    // Datepicker
    calendarParams: Object,
    // Colorpicker
    colorPickerParams: Object,
    // Text editor
    textEditorParams: Object,
    ...colorProps,
  },
  emits: [
    'input',
    'focus',
    'blur',
    'change',
    'textarea:resize',
    'input:notempty',
    'input:empty',
    'input:clear',
    'texteditor:change',
    'calendar:change',
    'colorpicker:change',
    'update:value',
  ],
  setup(props, { emit, slots }) {
    let t4Calendar = null;
    let t4ColorPicker = null;
    const inputInvalid = ref(false);
    const inputFocused = ref(false);
    const elRef = ref(null);
    const inputElRef = ref(null);

    let updateInputOnDidUpdate = false;

    const getDomValue = () => {
      if (!inputElRef.value) return undefined;
      return inputElRef.value.value;
    };

    const domValue = ref(getDomValue());

    const inputHasValue = computed(() => {
      if (props.type === 'datepicker' && Array.isArray(props.value) && props.value.length === 0) {
        return false;
      }
      return typeof props.value === 'undefined'
        ? domValue.value || domValue.value === 0
        : props.value || props.value === 0;
    });

    const validateInput = () => {
      if (!t4 || !inputElRef.value) return;
      const validity = inputElRef.value.validity;
      if (!validity) return;
      if (!validity.valid) {
        if (props.onValidate) props.onValidate(false);
        if (inputInvalid.value !== true) {
          inputInvalid.value = true;
        }
      } else {
        if (props.onValidate) props.onValidate(true);
        if (inputInvalid.value !== false) {
          inputInvalid.value = false;
        }
      }
    };
    const onTextareaResize = (event) => {
      emit('textarea:resize', event);
    };
    const onInputNotEmpty = (event) => {
      emit('input:notempty', event);
    };
    const onInputEmpty = (event) => {
      emit('input:empty', event);
    };
    const onInputClear = (event) => {
      emit('input:clear', event);
    };
    const onInput = (...args) => {
      emit('input', ...args);
      if (inputElRef.value) {
        domValue.value = inputElRef.value.value;
      }
      if (
        !(props.validateOnBlur || props.validateOnBlur === '') &&
        (props.validate || props.validate === '') &&
        inputElRef.value
      ) {
        validateInput();
      }
      if (
        inputElRef.value &&
        props.type !== 'texteditor' &&
        props.type !== 'colorpicker' &&
        props.type !== 'datepicker'
      ) {
        emit('update:value', inputElRef.value.value);
      }
    };
    const onFocus = (...args) => {
      emit('focus', ...args);
      inputFocused.value = true;
    };
    const onBlur = (...args) => {
      emit('blur', ...args);
      if (
        (props.validate ||
          props.validate === '' ||
          props.validateOnBlur ||
          props.validateOnBlur === '') &&
        inputElRef.value
      ) {
        validateInput();
      }
      inputFocused.value = false;
    };
    const onChange = (...args) => {
      emit('change', ...args);
      if (props.type === 'texteditor') {
        emit('texteditor:change', args[1]);
        emit('update:value', args[1]);
      }
    };

    onMounted(() => {
      const {
        type,
        resizable,
        clearButton,
        value,
        calendarParams,
        colorPickerParams,
        validate,
        validateOnBlur,
      } = props;
      t4ready(() => {
        if (type === 'range' || type === 'toggle') return;

        if (!inputElRef.value) return;

        inputElRef.value.addEventListener('input:notempty', onInputNotEmpty, false);
        if (type === 'textarea' && resizable) {
          inputElRef.value.addEventListener('textarea:resize', onTextareaResize, false);
        }
        if (clearButton) {
          inputElRef.value.addEventListener('input:empty', onInputEmpty, false);
          inputElRef.value.addEventListener('input:clear', onInputClear, false);
        }

        if (type === 'datepicker') {
          t4Calendar = t4.calendar.create({
            inputEl: inputElRef.value,
            value,
            on: {
              change(calendar, calendarValue) {
                emit('calendar:change', calendarValue);
                emit('update:value', calendarValue);
              },
            },
            ...(calendarParams || {}),
          });
        }
        if (type === 'colorpicker') {
          t4ColorPicker = t4.colorPicker.create({
            inputEl: inputElRef.value,
            value,
            on: {
              change(colorPicker, colorPickerValue) {
                emit('colorpicker:change', colorPickerValue);
                emit('update:value', colorPickerValue);
              },
            },
            ...(colorPickerParams || {}),
          });
        }

        t4.input.checkEmptyState(inputElRef.value);

        if (
          !(validateOnBlur || validateOnBlur === '') &&
          (validate || validate === '') &&
          typeof value !== 'undefined' &&
          value !== null &&
          value !== ''
        ) {
          setTimeout(() => {
            validateInput();
          }, 0);
        }
        if (resizable) {
          t4.input.resizeTextarea(inputElRef.value);
        }
      });
    });

    onBeforeUnmount(() => {
      if (props.type === 'range' || props.type === 'toggle') return;

      if (!inputElRef.value) return;

      inputElRef.value.removeEventListener('input:notempty', onInputNotEmpty, false);
      if (props.type === 'textarea' && props.resizable) {
        inputElRef.value.removeEventListener('textarea:resize', onTextareaResize, false);
      }
      if (props.clearButton) {
        inputElRef.value.removeEventListener('input:empty', onInputEmpty, false);
        inputElRef.value.removeEventListener('input:clear', onInputClear, false);
      }

      if (t4Calendar && t4Calendar.destroy) {
        t4Calendar.destroy();
        t4Calendar = null;
      }
      if (t4ColorPicker && t4ColorPicker.destroy) {
        t4ColorPicker.destroy();
        t4ColorPicker = null;
      }
    });

    onUpdated(() => {
      if (!t4) return;
      if (updateInputOnDidUpdate) {
        if (!inputElRef.value) return;
        updateInputOnDidUpdate = false;
        t4.input.checkEmptyState(inputElRef.value);
        if (props.validate && !props.validateOnBlur) {
          validateInput();
        }
        if (props.resizable) {
          t4.input.resizeTextarea(inputElRef.value);
        }
      }
    });

    watch(
      () => props.colorPickerParams,
      (newValue) => {
        if (!t4 || !t4ColorPicker) return;
        extend(t4ColorPicker.params, newValue || {});
      },
    );

    watch(
      () => props.calendarParams,
      (newValue) => {
        if (!t4 || !t4Calendar) return;
        extend(t4Calendar.params, newValue || {});
      },
    );

    watch(
      () => props.value,
      (newValue) => {
        if (props.type === 'range' || props.type === 'toggle' || !t4) return;
        updateInputOnDidUpdate = true;
        if (t4Calendar) {
          t4Calendar.setValue(newValue);
        }
        if (t4ColorPicker) {
          t4ColorPicker.setValue(newValue);
        }
      },
    );

    const createInput = (InputTag, children) => {
      const needsValue =
        props.type !== 'file' && props.type !== 'datepicker' && props.type !== 'colorpicker';
      const needsType = InputTag === 'input';
      let inputType = props.type;
      if (inputType === 'datepicker' || inputType === 'colorpicker') {
        inputType = 'text';
      }
      const inputClassName = classNames({
        resizable: inputType === 'textarea' && props.resizable,
        'no-store-data': props.noFormStoreData || props.noStoreData || props.ignoreStoreData,
        'input-invalid': (props.errorMessage && props.errorMessageForce) || inputInvalid.value,
        'input-with-value': inputHasValue.value,
        'input-focused': inputFocused.value,
      });
      let inputValue;
      if (needsValue) {
        if (typeof props.value !== 'undefined') inputValue = props.value;
        else inputValue = domValue.value;
      }
      const valueProps = {};
      if (props.type !== 'datepicker' && props.type !== 'colorpicker') {
        if ('value' in props) valueProps.value = inputValue;
      }
      const inputProps = noUndefinedProps({
        name: props.name,
        type: needsType ? inputType : undefined,
        placeholder: props.placeholder,
        inputmode: props.inputmode,
        id: props.inputId,
        size: props.size,
        accept: props.accept,
        autocomplete: props.autocomplete,
        autoCorrect: props.autocorrect,
        autocapitalize: props.autocapitalize,
        spellcheck: props.spellcheck,
        autofocus: props.autofocus,
        autoSave: props.autosave,
        checked: props.checked,
        disabled: props.disabled,
        max: props.max,
        maxlength: props.maxlength,
        min: props.min,
        minlength: props.minlength,
        step: props.step,
        multiple: props.multiple,
        readonly: props.readonly,
        required: props.required,
        pattern: props.pattern,
        validate:
          typeof props.validate === 'string' && props.validate.length ? props.validate : undefined,
        tabindex: props.tabindex,
      });
      return h(
        InputTag,
        {
          ref: inputElRef,
          style: props.inputStyle,
          ...inputProps,
          'data-validate':
            props.validate === true ||
            props.validate === '' ||
            props.validateOnBlur === true ||
            props.validateOnBlur === ''
              ? true
              : undefined,
          'data-validate-on-blur':
            props.validateOnBlur === true || props.validateOnBlur === '' ? true : undefined,
          'data-error-message': props.errorMessageForce ? undefined : props.errorMessage,
          class: inputClassName,
          onFocus,
          onBlur,
          onInput,
          onChange,
          ...valueProps,
        },
        [children],
      );
    };

    const wrapClasses = computed(() =>
      classNames(
        'input',
        {
          'input-outline': props.outline,
          'input-dropdown': props.dropdown === 'auto' ? props.type === 'select' : props.dropdown,
          'input-invalid': (props.errorMessage && props.errorMessageForce) || inputInvalid.value,
        },
        colorClasses(props),
      ),
    );

    return () => {
      let inputEl;
      if (props.type === 'select' || props.type === 'textarea' || props.type === 'file') {
        if (props.type === 'select') {
          inputEl = createInput('select', slots.default && slots.default());
        } else if (props.type === 'file') {
          inputEl = createInput('input');
        } else {
          inputEl = createInput('textarea');
        }
      } else if (slots.default || !props.type) {
        inputEl = slots.default();
      } else if (props.type === 'toggle') {
        inputEl = h(t4Toggle, {
          checked: props.checked,
          readonly: props.readonly,
          name: props.name,
          value: props.value,
          disabled: props.disabled,
          id: props.inputId,
          onChange,
        });
      } else if (props.type === 'range') {
        inputEl = h(t4Range, {
          value: props.value,
          disabled: props.disabled,
          min: props.min,
          max: props.max,
          step: props.step,
          name: props.name,
          id: props.inputId,
          input: true,
          onRangeChange: onChange,
        });
      } else if (props.type === 'texteditor') {
        inputEl = h(t4TextEditor, {
          value: props.value,
          resizable: props.resizable,
          placeholder: props.placeholder,
          onTextEditorFocus: onFocus,
          onTextEditorBlur: onBlur,
          onTextEditorInput: onInput,
          onTextEditorChange: onChange,
          ...(props.textEditorParams || {}),
        });
      } else {
        inputEl = createInput('input');
      }
      if (!props.wrap) return inputEl;

      return h('div', { class: wrapClasses.value, ref: elRef }, [
        inputEl,
        (props.errorMessage || slots['error-message']) &&
          props.errorMessageForce &&
          h('div', { class: 'input-error-message' }, [
            props.errorMessage,
            slots['error-message'] && slots['error-message'](),
          ]),
        props.clearButton && h('span', { class: 'input-clear-button' }),
        (props.info || slots.info) &&
          h('div', { class: 'input-info' }, [props.info, slots.info && slots.info()]),
      ]);
    };
  },
};
</script>
