// src/react/components/menu-item.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import { classNames, getExtraAttrs, getSlots, emit } from '../shared/utils.js';
import {
  colorClasses,
  routerAttrs,
  routerClasses,
  actionsClasses,
  actionsAttrs,
} from '../shared/mixins.js';
import { useRouteProps } from '../shared/use-route-props.js';
import { useIcon } from '../shared/use-icon.js';
import { t4ready, t4 } from '../shared/t4.js';
import { useTooltip } from '../shared/use-tooltip.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  text?: string;
  iconOnly?: boolean;
  href?: string;
  link?: boolean;
  target?: string;
  dropdown?: boolean;
  tooltip? : string
  tooltipTrigger? : string
  COLOR_PROPS
  ICON_PROPS
  ROUTER_PROPS
  ACTIONS_PROPS
  onClick? : (event?: any) => void;
  onMenuOpened? : (el?: HTMLElement) => void;
  onMenuClosed? : (el?: HTMLElement) => void;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const MenuItem = forwardRef((props, ref) => {
  const { className, id, style, link, href, target, text, dropdown, iconOnly } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };
  const onOpened = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'menuOpened', el);
  };
  const onClosed = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'menuClosed', el);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useTooltip(elRef, props);

  useRouteProps(elRef, props);

  const attachEvents = () => {
    t4ready(() => {
      t4.on('menuOpened', onOpened);
      t4.on('menuClosed', onClosed);
    });
  };

  const detachEvents = () => {
    t4.off('menuOpened', onOpened);
    t4.off('menuClosed', onOpened);
  };

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    return detachEvents;
  });

  const iconEl = useIcon(props);
  const slots = getSlots(props);

  let iconOnlyComputed;

  if (iconOnly || (!text && slots.text && slots.text.length === 0) || (!text && !slots.text)) {
    iconOnlyComputed = true;
  } else {
    iconOnlyComputed = false;
  }

  const isLink = link || href || href === '';
  const Tag = isLink ? 'a' : 'div';
  const isDropdown = dropdown || dropdown === '';

  const classes = classNames(
    {
      'menu-item': true,
      'menu-item-dropdown': isDropdown,
      'icon-only': iconOnlyComputed,
    },
    className,
    colorClasses(props),
    routerClasses(props),
    actionsClasses(props),
  );

  let hrefComputed = href;
  if (typeof hrefComputed === 'undefined' && link) hrefComputed = '#';

  const attrs = {
    href: hrefComputed,
    target,
    ...routerAttrs(props),
    ...actionsAttrs(props),
  };

  return (
    <Tag
      ref={elRef}
      className={classes}
      id={id}
      style={style}
      {...attrs}
      {...extraAttrs}
      onClick={onClick}
    >
      {(text || (slots.text && slots.text.length) || iconEl) && (
        <div className="menu-item-content">
          {text}
          {iconEl}
          {slots.text}
        </div>
      )}
      {slots.default}
    </Tag>
  );
});

MenuItem.displayName = 't4-menu-item';

export default MenuItem;

// src/vue/components/menu-item.vue
<template>
  <component :is="tag" ref="elRef" :class="classes" v-bind="attrs" @click="onClick">
    <div v-if="text || $slots.text || icon" class="menu-item-content">
      {{ text }}
      <t4-use-icon v-if="icon" :icon="icon" />
      <slot name="text" />
    </div>
    <slot />
  </component>
</template>
<script>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils.js';
import {
  colorClasses,
  colorProps,
  routerProps,
  routerAttrs,
  routerClasses,
  actionsProps,
  actionsClasses,
  actionsAttrs,
  iconProps,
} from '../shared/mixins.js';
import { useRouteProps } from '../shared/use-route-props.js';
import { useIcon } from '../shared/use-icon.js';
import { t4ready, t4 } from '../shared/t4.js';
import { useTooltip } from '../shared/use-tooltip.js';

import t4UseIcon from './use-icon.js';

export default {
  name: 't4-menu-item',
  components: {
    t4UseIcon,
  },
  props: {
    text: String,
    iconOnly: Boolean,
    href: String,
    link: Boolean,
    target: String,
    dropdown: Boolean,
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
    ...routerProps,
    ...actionsProps,
    ...iconProps,
  },
  emits: ['click', 'menu:opened', 'menu:closed'],
  setup(props, { slots, emit }) {
    const elRef = ref(null);

    useTooltip(elRef, props);

    const onClick = (e) => {
      emit('click', e);
    };
    const onOpened = (el) => {
      if (elRef.value !== el) return;
      emit('menu:opened', el);
    };
    const onClosed = (el) => {
      if (elRef.value !== el) return;
      emit('menu:closed', el);
    };

    useRouteProps(elRef, props);

    const attachEvents = () => {
      t4ready(() => {
        t4.on('menuOpened', onOpened);
        t4.on('menuClosed', onClosed);
      });
    };

    const detachEvents = () => {
      t4.off('menuOpened', onOpened);
      t4.off('menuClosed', onOpened);
    };

    onMounted(() => attachEvents());
    onBeforeUnmount(() => detachEvents());

    const icon = computed(() => useIcon(props));

    const tag = computed(() => {
      const isLink = props.link || props.href || props.href === '';
      return isLink ? 'a' : 'div';
    });

    const classes = computed(() => {
      let iconOnlyComputed;

      if (props.iconOnly || (!props.text && !slots.text)) {
        iconOnlyComputed = true;
      } else {
        iconOnlyComputed = false;
      }

      const isDropdown = props.dropdown || props.dropdown === '';

      return classNames(
        {
          'menu-item': true,
          'menu-item-dropdown': isDropdown,
          'icon-only': iconOnlyComputed,
        },
        colorClasses(props),
        routerClasses(props),
        actionsClasses(props),
      );
    });

    const attrs = computed(() => {
      let hrefComputed = props.href;
      if (typeof hrefComputed === 'undefined' && props.link) hrefComputed = '#';

      return {
        href: hrefComputed,
        target: props.target,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    return {
      tag,
      classes,
      attrs,
      icon,
      onClick,
      elRef,
    };
  },
};
</script>
