// src/react/components/nav-title-large.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const NavTitleLarge = forwardRef((props, ref) => {
  const { className, id, style, children } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(className, 'title-large', colorClasses(props));

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      <div className="title-large-text">{children}</div>
    </div>
  );
});

NavTitleLarge.displayName = 't4-nav-title-large';

export default NavTitleLarge;

// src/vue/components/nav-title-large.vue
<template>
  <div :class="classes">
    <div class="title-large-text"><slot /></div>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-nav-title-large',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('title-large', colorClasses(props)));
    return { classes };
  },
};
</script>
