// src/react/components/nav-left.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { useTheme } from '../shared/use-theme.js';

import Link from './link.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  backLink? : boolean | string;
  backLinkUrl? : string;
  backLinkForce? : boolean;
  backLinkShowText? : boolean;
  sliding? : boolean;
  COLOR_PROPS
  onBackClick? : (event?: any) => void;
  onClickBack? : (event?: any) => void;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const NavLeft = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    children,
    backLink,
    backLinkUrl,
    backLinkForce,
    backLinkShowText,
    sliding,
  } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onBackClick = (event) => {
    emit(props, 'backClick clickBack', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const theme = useTheme();

  let linkEl;
  let needBackLinkText = backLinkShowText;
  if (typeof needBackLinkText === 'undefined') needBackLinkText = !theme.md;

  if (backLink) {
    const text = backLink !== true && needBackLinkText ? backLink : undefined;
    linkEl = (
      <Link
        href={backLinkUrl || '#'}
        back
        icon="icon-back"
        force={backLinkForce || undefined}
        className={!text ? 'icon-only' : undefined}
        text={text}
        onClick={onBackClick}
      />
    );
  }
  const classes = classNames(
    className,
    'left',
    {
      sliding,
    },
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {linkEl}
      {children}
    </div>
  );
});

NavLeft.displayName = 't4-nav-left';

export default NavLeft;

// src/vue/components/nav-left.vue
<template>
  <div :class="classes">
    <t4-link
      v-if="backLink"
      :href="backLinkUrl || '#'"
      back
      icon="icon-back"
      :force="backLinkForce || undefined"
      :class="!text ? 'icon-only' : undefined"
      :text="text"
      @click="onBackClick"
    />
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTheme } from '../shared/use-theme.js';

import t4Link from './link.js';

export default {
  name: 't4-nav-left',
  components: {
    t4Link,
  },
  props: {
    backLink: [Boolean, String],
    backLinkUrl: String,
    backLinkForce: Boolean,
    backLinkShowText: {
      type: Boolean,
      default: undefined,
    },
    sliding: Boolean,
    ...colorProps,
  },
  emits: ['back:click', 'click:back'],
  setup(props, { emit }) {
    const onBackClick = (event) => {
      emit('back:click', event);
      emit('click:back', event);
    };
    const theme = useTheme();

    const text = computed(() => {
      let needBackLinkText = props.backLinkShowText;
      if (typeof needBackLinkText === 'undefined') needBackLinkText = !theme.value.md;
      if (props.backLink) {
        return props.backLink !== true && needBackLinkText ? props.backLink : undefined;
      }
      return undefined;
    });

    const classes = computed(() =>
      classNames(
        'left',
        {
          sliding: props.sliding,
        },
        colorClasses(props),
      ),
    );
    return { classes, onBackClick, text };
  },
};
</script>
