// src/react/components/progressbar.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4 } from '../shared/t4.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  progress? : number;
  infinite? : boolean;
  ref?: React.MutableRefObject<{el: HTMLElement | null; set: (progress: number, duration: number) => void}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const Progressbar = forwardRef((props, ref) => {
  const { className, id, style, progress, infinite } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const set = (newProgress, speed) => {
    if (!t4) return;
    t4.progressbar.set(elRef.current, newProgress, speed);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    set,
  }));

  const transformStyle = {
    transform: progress ? `translate3d(${-100 + progress}%, 0, 0)` : '',
    WebkitTransform: progress ? `translate3d(${-100 + progress}%, 0, 0)` : '',
  };

  const classes = classNames(
    className,
    'progressbar',
    {
      'progressbar-infinite': infinite,
    },
    colorClasses(props),
  );

  return (
    <span
      ref={elRef}
      id={id}
      style={style}
      className={classes}
      data-progress={progress}
      {...extraAttrs}
    >
      <span style={transformStyle} />
    </span>
  );
});

Progressbar.displayName = 't4-progressbar';

export default Progressbar;

// src/vue/components/progressbar.vue
<template>
  <span ref="elRef" :class="classes" :data-progress="progress">
    <span :style="transformStyle" />
  </span>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4 } from '../shared/t4.js';

export default {
  name: 't4-progressbar',
  props: {
    progress: Number,
    infinite: Boolean,
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    const set = (newProgress, speed) => {
      if (!t4) return;
      t4.progressbar.set(elRef.value, newProgress, speed);
    };

    const transformStyle = computed(() => ({
      transform: props.progress ? `translate3d(${-100 + props.progress}%, 0, 0)` : '',
      WebkitTransform: props.progress ? `translate3d(${-100 + props.progress}%, 0, 0)` : '',
    }));

    const classes = computed(() =>
      classNames(
        'progressbar',
        {
          'progressbar-infinite': props.infinite,
        },
        colorClasses(props),
      ),
    );
    return { classes, set, transformStyle, elRef };
  },
};
</script>
