// src/react/components/stepper.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import { classNames, getExtraAttrs, emit, noUndefinedProps } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';
import { watchProp } from '../shared/watch-prop.js';

/* dts-imports
import { Stepper } from 'techno4/types';
*/
/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  init? : boolean
  value? : number
  min? : number
  max? : number
  step? : number
  formatValue? : Function
  name? : string
  inputId? : string
  input? : boolean
  inputType? : string
  inputReadonly? : boolean
  autorepeat? : boolean
  autorepeatDynamic? : boolean
  wraps? : boolean
  manualInputMode? : boolean
  decimalPoint? : number
  buttonsEndInputMode? : boolean
  disabled? : boolean
  buttonsOnly? : boolean
  round? : boolean
  roundMd? : boolean
  roundIos? : boolean
  roundAurora? : boolean
  fill? : boolean
  fillMd? : boolean
  fillIos? : boolean
  fillAurora? : boolean
  large? : boolean
  largeMd? : boolean
  largeIos? : boolean
  largeAurora? : boolean
  small? : boolean
  smallMd? : boolean
  smallIos? : boolean
  smallAurora? : boolean
  raised? : boolean
  raisedMd? : boolean
  raisedIos? : boolean
  raisedAurora? : boolean
  COLOR_PROPS
  onStepperChange? : (newValue?: any) => void
  onInput? : (event?: any, stepper?: Stepper.Stepper) => void
  onChange? : (event?: any, stepper?: Stepper.Stepper) => void
  onStepperMinusClick? : (event?: any, stepper?: Stepper.Stepper) => void
  onStepperPlusClick? : (event?: any, stepper?: Stepper.Stepper) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null; t4Stepper: () => Stepper.Stepper;}>;
  children?: React.ReactNode;
*/

const Stepper = forwardRef((props, ref) => {
  const t4Stepper = useRef(null);
  const {
    className,
    id,
    style,
    init = true,
    value = 0,
    min = 0,
    max = 100,
    step = 1,
    formatValue,
    name,
    inputId,
    input = true,
    inputType = 'text',
    inputReadonly = false,
    autorepeat = false,
    autorepeatDynamic = false,
    wraps = false,
    manualInputMode = false,
    decimalPoint = 4,
    buttonsEndInputMode = true,
    disabled,
    buttonsOnly,
    round,
    roundMd,
    roundIos,
    roundAurora,
    fill,
    fillMd,
    fillIos,
    fillAurora,
    large,
    largeMd,
    largeIos,
    largeAurora,
    small,
    smallMd,
    smallIos,
    smallAurora,
    raised,
    raisedMd,
    raisedIos,
    raisedAurora,
  } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const increment = () => {
    if (!t4Stepper.current) return;
    t4Stepper.current.increment();
  };
  const decrement = () => {
    if (!t4Stepper.current) return;
    t4Stepper.current.decrement();
  };
  const setValue = (newValue) => {
    if (t4Stepper.current && t4Stepper.current.setValue) t4Stepper.current.setValue(newValue);
  };
  const getValue = () => {
    if (t4Stepper.current && t4Stepper.current.getValue) {
      return t4Stepper.current.getValue();
    }
    return undefined;
  };
  const onInput = (event) => {
    emit(props, 'input', event, t4Stepper.current);
  };
  const onChange = (event) => {
    emit(props, 'change', event, t4Stepper.current);
  };
  const onMinusClick = (event) => {
    emit(props, 'stepperMinusClick', event, t4Stepper.current);
  };
  const onPlusClick = (event) => {
    emit(props, 'stepperPlusClick', event, t4Stepper.current);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    t4Stepper: () => t4Stepper.current,
    increment,
    decrement,
    setValue,
    getValue,
  }));

  watchProp(value, (newValue) => {
    if (!t4Stepper.current) return;
    t4Stepper.current.setValue(newValue);
  });

  const onStepperChange = (stepper, newValue) => {
    emit(props, 'stepperChange', newValue);
  };

  const stepperEvents = (method) => {
    if (!t4Stepper.current) return;
    t4Stepper.current[method]('change', onStepperChange);
  };

  const onMount = () => {
    t4ready(() => {
      if (!init || !elRef.current) return;
      t4Stepper.current = t4.stepper.create(
        noUndefinedProps({
          el: elRef.current,
          min,
          max,
          value,
          step,
          formatValue,
          autorepeat,
          autorepeatDynamic,
          wraps,
          manualInputMode,
          decimalPoint,
          buttonsEndInputMode,
        }),
      );
      stepperEvents('on');
    });
  };

  const onDestroy = () => {
    if (t4Stepper.current && t4Stepper.current.destroy) {
      t4Stepper.current.destroy();
    }
    t4Stepper.current = null;
  };

  useIsomorphicLayoutEffect(() => {
    stepperEvents('on');
    return () => {
      stepperEvents('off');
    };
  });

  useIsomorphicLayoutEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  let inputWrapEl;
  let valueEl;
  if (input && !buttonsOnly) {
    const inputEl = (
      <input
        name={name}
        id={inputId}
        type={inputType}
        min={inputType === 'number' ? min : undefined}
        max={inputType === 'number' ? max : undefined}
        step={inputType === 'number' ? step : undefined}
        onInput={onInput}
        onChange={onChange}
        value={value}
        readOnly={inputReadonly}
      />
    );

    inputWrapEl = <div className="stepper-input-wrap">{inputEl}</div>;
  }
  if (!input && !buttonsOnly) {
    valueEl = <div className="stepper-value">{value}</div>;
  }

  const classes = classNames(
    className,
    'stepper',
    {
      disabled,
      'stepper-round': round,
      'stepper-round-ios': roundIos,
      'stepper-round-md': roundMd,
      'stepper-round-aurora': roundAurora,
      'stepper-fill': fill,
      'stepper-fill-ios': fillIos,
      'stepper-fill-md': fillMd,
      'stepper-fill-aurora': fillAurora,
      'stepper-large': large,
      'stepper-large-ios': largeIos,
      'stepper-large-md': largeMd,
      'stepper-large-aurora': largeAurora,
      'stepper-small': small,
      'stepper-small-ios': smallIos,
      'stepper-small-md': smallMd,
      'stepper-small-aurora': smallAurora,
      'stepper-raised': raised,
      'stepper-raised-ios': raisedIos,
      'stepper-raised-md': raisedMd,
      'stepper-raised-aurora': raisedAurora,
    },
    colorClasses(props),
  );
  return (
    <div ref={elRef} id={id} style={style} className={classes} {...extraAttrs}>
      <div className="stepper-button-minus" onClick={onMinusClick} />
      {inputWrapEl}
      {valueEl}
      <div className="stepper-button-plus" onClick={onPlusClick} />
    </div>
  );
});

Stepper.displayName = 't4-stepper';

export default Stepper;

// src/vue/components/stepper.vue
<template>
  <div ref="elRef" :class="classes">
    <div class="stepper-button-minus" @click="onMinusClick" />
    <div v-if="input && !buttonsOnly" class="stepper-input-wrap">
      <input
        :id="inputId"
        :name="name"
        :type="inputType"
        :min="inputType === 'number' ? min : undefined"
        :max="inputType === 'number' ? max : undefined"
        :step="inputType === 'number' ? step : undefined"
        :value="value"
        :readonly="inputReadonly"
        @input="onInput"
        @change="onChange"
      />
    </div>
    <div v-if="!input && !buttonsOnly" class="stepper-value">{{ value }}</div>
    <div class="stepper-button-plus" @click="onPlusClick" />
  </div>
</template>
<script>
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { classNames, noUndefinedProps } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';

export default {
  name: 't4-stepper',
  props: {
    init: {
      type: Boolean,
      default: true,
    },
    value: {
      type: Number,
      default: 0,
    },
    min: {
      type: Number,
      default: 0,
    },
    max: {
      type: Number,
      default: 100,
    },
    step: {
      type: Number,
      default: 1,
    },
    formatValue: Function,
    name: String,
    inputId: String,
    input: {
      type: Boolean,
      default: true,
    },
    inputType: {
      type: String,
      default: 'text',
    },
    inputReadonly: {
      type: Boolean,
      default: false,
    },
    autorepeat: {
      type: Boolean,
      default: false,
    },
    autorepeatDynamic: {
      type: Boolean,
      default: false,
    },
    wraps: {
      type: Boolean,
      default: false,
    },
    manualInputMode: {
      type: Boolean,
      default: false,
    },
    decimalPoint: {
      type: Number,
      default: 4,
    },
    buttonsEndInputMode: {
      type: Boolean,
      default: true,
    },
    disabled: Boolean,
    buttonsOnly: Boolean,

    round: Boolean,
    roundMd: Boolean,
    roundIos: Boolean,
    roundAurora: Boolean,
    fill: Boolean,
    fillMd: Boolean,
    fillIos: Boolean,
    fillAurora: Boolean,
    large: Boolean,
    largeMd: Boolean,
    largeIos: Boolean,
    largeAurora: Boolean,
    small: Boolean,
    smallMd: Boolean,
    smallIos: Boolean,
    smallAurora: Boolean,
    raised: Boolean,
    raisedMd: Boolean,
    raisedIos: Boolean,
    raisedAurora: Boolean,
    ...colorProps,
  },
  emits: [
    'input',
    'change',
    'stepper:minusclick',
    'stepper:plusclick',
    'stepper:change',
    'update:value',
  ],
  setup(props, { emit }) {
    let t4Stepper = null;
    const elRef = ref(null);

    const increment = () => {
      if (!t4Stepper) return;
      t4Stepper.increment();
    };
    const decrement = () => {
      if (!t4Stepper) return;
      t4Stepper.decrement();
    };
    const setValue = (newValue) => {
      if (t4Stepper && t4Stepper.setValue) t4Stepper.setValue(newValue);
    };
    const getValue = () => {
      if (t4Stepper && t4Stepper.getValue) {
        return t4Stepper.getValue();
      }
      return undefined;
    };
    const onInput = (event) => {
      emit('input', event, t4Stepper);
    };
    const onChange = (event) => {
      emit('change', event, t4Stepper);
    };
    const onMinusClick = (event) => {
      emit('stepper:minusclick', event, t4Stepper);
    };
    const onPlusClick = (event) => {
      emit('stepper:plusclick', event, t4Stepper);
    };

    watch(
      () => props.value,
      (newValue) => {
        if (!t4Stepper) return;
        t4Stepper.setValue(newValue);
      },
    );

    onMounted(() => {
      t4ready(() => {
        if (!props.init || !elRef.value) return;
        t4Stepper = t4.stepper.create(
          noUndefinedProps({
            el: elRef.value,
            min: props.min,
            max: props.max,
            value: props.value,
            step: props.step,
            formatValue: props.formatValue,
            autorepeat: props.autorepeat,
            autorepeatDynamic: props.autorepeatDynamic,
            wraps: props.wraps,
            manualInputMode: props.manualInputMode,
            decimalPoint: props.decimalPoint,
            buttonsEndInputMode: props.buttonsEndInputMode,
            on: {
              change(stepper, newValue) {
                emit('stepper:change', newValue);
                emit('update:value', newValue);
              },
            },
          }),
        );
      });
    });

    onBeforeUnmount(() => {
      if (t4Stepper && t4Stepper.destroy) {
        t4Stepper.destroy();
      }
      t4Stepper = null;
    });

    const classes = computed(() =>
      classNames(
        'stepper',
        {
          disabled: props.disabled,
          'stepper-round': props.round,
          'stepper-round-ios': props.roundIos,
          'stepper-round-md': props.roundMd,
          'stepper-round-aurora': props.roundAurora,
          'stepper-fill': props.fill,
          'stepper-fill-ios': props.fillIos,
          'stepper-fill-md': props.fillMd,
          'stepper-fill-aurora': props.fillAurora,
          'stepper-large': props.large,
          'stepper-large-ios': props.largeIos,
          'stepper-large-md': props.largeMd,
          'stepper-large-aurora': props.largeAurora,
          'stepper-small': props.small,
          'stepper-small-ios': props.smallIos,
          'stepper-small-md': props.smallMd,
          'stepper-small-aurora': props.smallAurora,
          'stepper-raised': props.raised,
          'stepper-raised-ios': props.raisedIos,
          'stepper-raised-md': props.raisedMd,
          'stepper-raised-aurora': props.raisedAurora,
        },
        colorClasses(props),
      ),
    );

    return {
      elRef,
      classes,
      increment,
      decrement,
      setValue,
      getValue,
      onInput,
      onChange,
      onMinusClick,
      onPlusClick,
    };
  },
};
</script>
