// src/svelte/components/tabs.svelte
<script>
  import { onMount } from 'svelte';

  import { restProps } from '../shared/rest-props.js';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';

  let className = undefined;
  export { className as class };
  export let animated = false;
  export let swipeable = false;
  export let routable = false;
  export let swiperParams = undefined;

  let wrapEl;

  $: classes = classNames(className, colorClasses($$props));
  $: wrapClasses = classNames({
    'tabs-animated-wrap': animated,
    'tabs-swipeable-wrap': swipeable,
  });
  $: tabsClasses = classNames({
    tabs: true,
    'tabs-routable': routable,
  });

  onMount(() => {
    if (swipeable && swiperParams && wrapEl) {
      wrapEl.t4SwiperParams = swiperParams;
    }
  });
</script>

{#if animated || swipeable}
  <div class={classNames(wrapClasses, classes)} bind:this={wrapEl} {...restProps($$restProps)}>
    <div class={tabsClasses}>
      <slot />
    </div>
  </div>
{:else}
  <div class={classNames(tabsClasses, classes)} {...restProps($$restProps)}>
    <slot />
  </div>
{/if}

// src/vue/components/tabs.vue
<template>
  <div v-if="animated || swipeable" ref="elRef" :class="classNames(wrapClasses, classes)">
    <div :class="tabsClasses">
      <slot />
    </div>
  </div>
  <div v-else ref="elRef" :class="classNames(tabsClasses, classes)">
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-tabs',
  props: {
    animated: Boolean,
    swipeable: Boolean,
    routable: Boolean,
    swiperParams: {
      type: Object,
      default: undefined,
    },
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    onMounted(() => {
      if (!props.swipeable || !props.swiperParams) return;
      if (!elRef.value) return;
      elRef.value.t4SwiperParams = props.swiperParams;
    });

    const classes = computed(() => classNames(colorClasses(props)));
    const wrapClasses = computed(() =>
      classNames({
        'tabs-animated-wrap': props.animated,
        'tabs-swipeable-wrap': props.swipeable,
      }),
    );
    const tabsClasses = computed(() =>
      classNames({
        tabs: true,
        'tabs-routable': props.routable,
      }),
    );

    return {
      elRef,
      classes,
      wrapClasses,
      tabsClasses,
      classNames,
    };
  },
};
</script>
