// src/react/components/tabs.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-imports
import { SwiperOptions } from 'swiper';
*/
/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  animated? : boolean
  swipeable? : boolean
  routable? : boolean
  swiperParams? : SwiperOptions
  COLOR_PROPS
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const Tabs = forwardRef((props, ref) => {
  const { className, id, style, children, animated, swipeable, routable, swiperParams } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useIsomorphicLayoutEffect(() => {
    if (!swipeable || !swiperParams) return;
    if (!elRef.current) return;
    elRef.current.t4SwiperParams = swiperParams;
  }, []);

  const classes = classNames(className, colorClasses(props));
  const wrapClasses = classNames({
    'tabs-animated-wrap': animated,
    'tabs-swipeable-wrap': swipeable,
  });
  const tabsClasses = classNames({
    tabs: true,
    'tabs-routable': routable,
  });

  if (animated || swipeable) {
    return (
      <div
        id={id}
        style={style}
        className={classNames(wrapClasses, classes)}
        ref={elRef}
        {...extraAttrs}
      >
        <div className={tabsClasses}>{children}</div>
      </div>
    );
  }

  return (
    <div
      id={id}
      style={style}
      className={classNames(tabsClasses, classes)}
      ref={elRef}
      {...extraAttrs}
    >
      {children}
    </div>
  );
});

Tabs.displayName = 't4-tabs';

export default Tabs;

// src/vue/components/tabs.vue
<template>
  <div v-if="animated || swipeable" ref="elRef" :class="classNames(wrapClasses, classes)">
    <div :class="tabsClasses">
      <slot />
    </div>
  </div>
  <div v-else ref="elRef" :class="classNames(tabsClasses, classes)">
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-tabs',
  props: {
    animated: Boolean,
    swipeable: Boolean,
    routable: Boolean,
    swiperParams: {
      type: Object,
      default: undefined,
    },
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    onMounted(() => {
      if (!props.swipeable || !props.swiperParams) return;
      if (!elRef.value) return;
      elRef.value.t4SwiperParams = props.swiperParams;
    });

    const classes = computed(() => classNames(colorClasses(props)));
    const wrapClasses = computed(() =>
      classNames({
        'tabs-animated-wrap': props.animated,
        'tabs-swipeable-wrap': props.swipeable,
      }),
    );
    const tabsClasses = computed(() =>
      classNames({
        tabs: true,
        'tabs-routable': props.routable,
      }),
    );

    return {
      elRef,
      classes,
      wrapClasses,
      tabsClasses,
      classNames,
    };
  },
};
</script>
