// src/vue/components/list-index.vue
<template>
  <div ref="elRef" :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';

export default {
  name: 't4-list-index',
  props: {
    init: {
      type: Boolean,
      default: true,
    },
    listEl: [String, Object],
    indexes: {
      type: [String, Array],
      default: 'auto',
    },
    scrollList: {
      type: Boolean,
      default: true,
    },
    label: {
      type: Boolean,
      default: false,
    },
    iosItemHeight: {
      type: Number,
      default: 14,
    },
    mdItemHeight: {
      type: Number,
      default: 14,
    },
    auroraItemHeight: {
      type: Number,
      default: 14,
    },
    ...colorProps,
  },
  emits: ['listindex:select'],
  setup(props, { emit }) {
    let t4ListIndex = null;
    const elRef = ref(null);

    const update = () => {
      if (!t4ListIndex) return;
      t4ListIndex.update();
    };
    const scrollListToIndex = (indexContent) => {
      if (!t4ListIndex) return;
      t4ListIndex.scrollListToIndex(indexContent);
    };

    watch(
      () => props.indexes,
      (newValue) => {
        if (!t4ListIndex) return;
        t4ListIndex.params.indexes = newValue;
        update();
      },
    );

    onMounted(() => {
      if (!props.init) return;
      t4ready(() => {
        t4ListIndex = t4.listIndex.create({
          el: elRef.value,
          listEl: props.listEl,
          indexes: props.indexes,
          iosItemHeight: props.iosItemHeight,
          mdItemHeight: props.mdItemHeight,
          auroraItemHeight: props.auroraItemHeight,
          scrollList: props.scrollList,
          label: props.label,
          on: {
            select(index, itemContent, itemIndex) {
              emit('listindex:select', itemContent, itemIndex);
            },
          },
        });
      });
    });

    onBeforeUnmount(() => {
      if (t4ListIndex && t4ListIndex.destroy) {
        t4ListIndex.destroy();
      }
      t4ListIndex = null;
    });

    const classes = computed(() => classNames('list-index', colorClasses(props)));
    return { elRef, classes, update, scrollListToIndex };
  },
};
</script>

// src/svelte/components/list-index.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let init = true;
  export let listEl = undefined;
  export let indexes = 'auto';
  export let scrollList = true;
  export let label = false;
  export let iosItemHeight = 14;
  export let mdItemHeight = 14;
  export let auroraItemHeight = 14;

  export let t4Slot = 'fixed';

  let el;
  let t4ListIndex;

  export function instance() {
    return t4ListIndex;
  }

  $: classes = classNames(className, 'list-index', colorClasses($$props));

  export function update() {
    if (!t4ListIndex) return;
    t4ListIndex.update();
  }

  export function scrollListToIndex(indexContent) {
    if (!t4ListIndex) return;
    t4ListIndex.scrollListToIndex(indexContent);
  }

  let initialWatched = false;
  function watchIndexes() {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (!t4ListIndex) return;
    t4ListIndex.params.indexes = indexes;
    update();
  }

  $: watchIndexes(indexes);

  onMount(() => {
    if (!init || !el) return;
    t4ready(() => {
      t4ListIndex = app.t4.listIndex.create({
        el,
        listEl,
        indexes,
        iosItemHeight,
        mdItemHeight,
        auroraItemHeight,
        scrollList,
        label,
        on: {
          select(index, itemContent, itemIndex) {
            emit('listIndexSelect', [itemContent, itemIndex]);
          },
        },
      });
    });
  });

  onDestroy(() => {
    if (t4ListIndex && t4ListIndex.destroy) t4ListIndex.destroy();
  });
</script>

<div bind:this={el} class={classes} data-t4-slot={t4Slot} {...restProps($$restProps)}>
  <slot listIndex={t4ListIndex} />
</div>
