// src/vue/components/list-input.vue
<script>
import { computed, h, ref, onMounted, onBeforeUnmount, watch, inject, onUpdated } from 'vue';
import { classNames, extend, noUndefinedProps } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';

import t4TextEditor from './text-editor.js';

export default {
  name: 't4-list-input',
  props: {
    sortable: {
      type: Boolean,
      default: undefined,
    },
    media: String,
    dropdown: {
      type: [String, Boolean],
      default: 'auto',
    },
    wrap: {
      type: Boolean,
      default: true,
    },

    // Inputs
    input: {
      type: Boolean,
      default: true,
    },
    type: {
      type: String,
      default: 'text',
    },
    name: String,
    value: {
      type: [String, Number, Array, Date, Object],
      default: undefined,
    },
    inputmode: String,
    readonly: Boolean,
    required: Boolean,
    disabled: Boolean,
    placeholder: String,
    inputId: [String, Number],
    size: [String, Number],
    accept: [String, Number],
    autocomplete: [String],
    autocorrect: [String],
    autocapitalize: [String],
    spellcheck: [String],
    autofocus: Boolean,
    autosave: String,
    max: [String, Number],
    min: [String, Number],
    step: [String, Number],
    maxlength: [String, Number],
    minlength: [String, Number],
    multiple: Boolean,
    inputStyle: [String, Object],
    pattern: String,
    validate: [Boolean, String],
    validateOnBlur: Boolean,
    onValidate: Function,
    tabindex: [String, Number],
    resizable: Boolean,
    clearButton: Boolean,

    // Form
    noFormStoreData: Boolean,
    noStoreData: Boolean,
    ignoreStoreData: Boolean,

    // Error, Info
    errorMessage: String,
    errorMessageForce: Boolean,
    info: String,

    // Outline
    outline: Boolean,

    // Label
    label: [String, Number],
    inlineLabel: Boolean,
    floatingLabel: Boolean,

    // Datepicker
    calendarParams: Object,
    // Colorpicker
    colorPickerParams: Object,
    // Text editor
    textEditorParams: Object,
    ...colorProps,
  },
  emits: [
    'textarea:resize',
    'input:notempty',
    'input:empty',
    'input:clear',
    'texteditor:change',
    'calendar:change',
    'colorpicker:change',
    'change',
    'focus',
    'blur',
    'input',
    'update:value',
  ],
  setup(props, { emit, slots }) {
    const inputInvalid = ref(false);
    const inputFocused = ref(false);

    const ListContext = inject('ListContext', {
      value: {
        listIsMedia: false,
        listIsSortable: false,
        listIsSortableOpposite: false,
        listIsSimple: false,
      },
    });

    let t4Calendar = null;
    let t4ColorPicker = null;
    const elRef = ref(null);
    const inputElRef = ref(null);
    const itemContentElRef = ref(null);
    let updateInputOnDidUpdate = false;

    const getDomValue = () => {
      if (!inputElRef.value) return undefined;
      return inputElRef.value.value;
    };

    const domValue = ref(getDomValue());

    const inputHasValue = computed(() => {
      if (props.type === 'datepicker' && Array.isArray(props.value) && props.value.length === 0) {
        return false;
      }
      return typeof props.value === 'undefined'
        ? domValue.value || domValue.value === 0
        : props.value || props.value === 0;
    });

    const validateInput = () => {
      if (!t4 || !inputElRef.value) return;
      const validity = inputElRef.value.validity;
      if (!validity) return;
      if (!validity.valid) {
        if (props.onValidate) props.onValidate(false);
        if (inputInvalid.value !== true) {
          inputInvalid.value = true;
        }
      } else {
        if (props.onValidate) props.onValidate(true);
        if (inputInvalid.value !== false) {
          inputInvalid.value = false;
        }
      }
    };

    const onTextareaResize = (event) => {
      emit('textarea:resize', event);
    };
    const onInputNotEmpty = (event) => {
      emit('input:notempty', event);
    };
    const onInputEmpty = (event) => {
      emit('input:empty', event);
    };
    const onInputClear = (event) => {
      emit('input:clear', event);
    };
    const onInput = (...args) => {
      emit('input', ...args);
      if (inputElRef.value) {
        domValue.value = inputElRef.value.value;
      }
      if (
        !(props.validateOnBlur || props.validateOnBlur === '') &&
        (props.validate || props.validate === '') &&
        inputElRef.value
      ) {
        validateInput(inputElRef.value);
      }
      if (
        inputElRef.value &&
        props.type !== 'texteditor' &&
        props.type !== 'colorpicker' &&
        props.type !== 'datepicker'
      ) {
        emit('update:value', inputElRef.value.value);
      }
    };
    const onFocus = (...args) => {
      emit('focus', ...args);
      inputFocused.value = true;
    };
    const onBlur = (...args) => {
      emit('blur', ...args);
      if (
        (props.validate ||
          props.validate === '' ||
          props.validateOnBlur ||
          props.validateOnBlur === '') &&
        inputElRef.value
      ) {
        validateInput(inputElRef.value);
      }
      inputFocused.value = false;
    };
    const onChange = (...args) => {
      emit('change', ...args);
      if (props.type === 'texteditor') {
        emit('texteditor:change', args[0]);
        emit('update:value', args[0]);
      }
    };

    onMounted(() => {
      if (!elRef.value && !itemContentElRef.value) return;

      t4ready(() => {
        if (!inputElRef.value) return;

        inputElRef.value.addEventListener('input:notempty', onInputNotEmpty, false);
        inputElRef.value.addEventListener('textarea:resize', onTextareaResize, false);
        inputElRef.value.addEventListener('input:empty', onInputEmpty, false);
        inputElRef.value.addEventListener('input:clear', onInputClear, false);

        if (props.type === 'datepicker') {
          t4Calendar = t4.calendar.create({
            inputEl: inputElRef.value,
            value: props.value,
            on: {
              change(calendar, calendarValue) {
                emit('update:value', calendarValue);
                emit('calendar:change', calendarValue);
              },
            },
            ...(props.calendarParams || {}),
          });
        }
        if (props.type === 'colorpicker') {
          t4ColorPicker = t4.colorPicker.create({
            inputEl: inputElRef.value,
            value: props.value,
            on: {
              change(colorPicker, colorPickerValue) {
                emit('update:value', colorPickerValue);
                emit('colorpicker:change', colorPickerValue);
              },
            },
            ...(props.colorPickerParams || {}),
          });
        }
        if (
          !(props.validateOnBlur || props.validateOnBlur === '') &&
          (props.validate || props.validate === '') &&
          typeof props.value !== 'undefined' &&
          props.value !== null &&
          props.value !== ''
        ) {
          setTimeout(() => {
            validateInput();
          }, 0);
        }
        if (props.type === 'textarea' && props.resizable) {
          t4.input.resizeTextarea(inputElRef.value);
        }
      });
    });

    onBeforeUnmount(() => {
      if (inputElRef.value) {
        inputElRef.value.removeEventListener('input:notempty', onInputNotEmpty, false);
        inputElRef.value.removeEventListener('textarea:resize', onTextareaResize, false);
        inputElRef.value.removeEventListener('input:empty', onInputEmpty, false);
        inputElRef.value.removeEventListener('input:clear', onInputClear, false);
      }

      if (t4Calendar && t4Calendar.destroy) {
        t4Calendar.destroy();
        t4Calendar = null;
      }
      if (t4ColorPicker && t4ColorPicker.destroy) {
        t4ColorPicker.destroy();
        t4ColorPicker = null;
      }
    });

    onUpdated(() => {
      if (!t4) return;
      if (updateInputOnDidUpdate) {
        if (!inputElRef.value) return;
        updateInputOnDidUpdate = false;
        if (props.validate && !props.validateOnBlur) {
          validateInput();
        }
        if (props.type === 'textarea' && props.resizable) {
          t4.input.resizeTextarea(inputElRef.value);
        }
      }
    });

    watch(
      () => props.colorPickerParams,
      (newValue) => {
        if (!t4 || !t4ColorPicker) return;
        extend(t4ColorPicker.params, newValue || {});
      },
    );

    watch(
      () => props.calendarParams,
      (newValue) => {
        if (!t4 || !t4Calendar) return;
        extend(t4Calendar.params, newValue || {});
      },
    );

    watch(
      () => props.value,
      (newValue) => {
        if (!t4) return;
        updateInputOnDidUpdate = true;
        if (t4Calendar) {
          t4Calendar.setValue(newValue);
        }
        if (t4ColorPicker) {
          t4ColorPicker.setValue(newValue);
        }
      },
    );

    const isSortableComputed = computed(() =>
      props.sortable === true || props.sortable === false
        ? props.sortable
        : ListContext.value.listIsSortable || false,
    );

    const createInput = (InputTag, children) => {
      const needsValue =
        props.type !== 'file' && props.type !== 'datepicker' && props.type !== 'colorpicker';
      const needsType = InputTag === 'input';
      let inputType = props.type;
      if (inputType === 'datepicker' || inputType === 'colorpicker') {
        inputType = 'text';
      }
      const inputClassName = classNames({
        resizable: inputType === 'textarea' && props.resizable,
        'no-store-data': props.noFormStoreData || props.noStoreData || props.ignoreStoreData,
        'input-invalid': (props.errorMessage && props.errorMessageForce) || inputInvalid.value,
        'input-with-value': inputHasValue.value,
        'input-focused': inputFocused.value,
      });
      let inputValue;
      if (needsValue) {
        if (typeof props.value !== 'undefined') inputValue = props.value;
        else inputValue = domValue.value;
      }
      const valueProps = {};
      if (props.type !== 'datepicker' && props.type !== 'colorpicker') {
        if ('value' in props) valueProps.value = inputValue;
      }
      const inputProps = noUndefinedProps({
        name: props.name,
        type: needsType ? inputType : undefined,
        placeholder: props.placeholder,
        inputmode: props.inputmode,
        id: props.inputId,
        size: props.size,
        accept: props.accept,
        autocomplete: props.autocomplete,
        autocorrect: props.autocorrect,
        autocapitalize: props.autocapitalize,
        spellcheck: props.spellcheck,
        autofocus: props.autofocus,
        autosave: props.autosave,
        disabled: props.disabled,
        max: props.max,
        maxlength: props.maxlength,
        min: props.min,
        minlength: props.minlength,
        step: props.step,
        multiple: props.multiple,
        readonly: props.readonly,
        required: props.required,
        pattern: props.pattern,
        validate:
          typeof props.validate === 'string' && props.validate.length ? props.validate : undefined,
        tabindex: props.tabindex,
      });
      return h(
        InputTag,
        {
          ref: inputElRef,
          style: props.inputStyle,
          ...inputProps,
          'data-validate':
            props.validate === true ||
            props.validate === '' ||
            props.validateOnBlur === true ||
            props.validateOnBlur === ''
              ? true
              : undefined,
          'data-validate-on-blur':
            props.validateOnBlur === true || props.validateOnBlur === '' ? true : undefined,
          'data-error-message': props.errorMessageForce ? undefined : props.errorMessage,
          class: inputClassName,
          onFocus,
          onBlur,
          onInput,
          onChange,
          ...valueProps,
        },
        [children],
      );
    };

    return () => {
      let inputEl;
      if (props.input) {
        if (props.type === 'select' || props.type === 'textarea' || props.type === 'file') {
          if (props.type === 'select') {
            inputEl = createInput('select', slots.default && slots.default());
          } else if (props.type === 'file') {
            inputEl = createInput('input');
          } else {
            inputEl = createInput('textarea');
          }
        } else if (props.type === 'texteditor') {
          inputEl = h(t4TextEditor, {
            value: props.value,
            resizable: props.resizable,
            placeholder: props.placeholder,
            onTexteditorFocus: onFocus,
            onTexteditorBlur: onBlur,
            onTexteditorInput: onInput,
            onTexteditorChange: onChange,
            ...(props.textEditorParams || {}),
          });
        } else {
          inputEl = createInput('input');
        }
      }
      const hasErrorMessage = !!props.errorMessage || slots['error-message'];
      const ItemContent = h(
        'div',
        {
          ref: itemContentElRef,
          class: classNames(
            'item-content item-input',
            !props.wrap && { disabled: props.disabled },
            !props.wrap && colorClasses(props),
            {
              'inline-label': props.inlineLabel,
              'item-input-outline': props.outline,
              'item-input-focused': inputFocused.value,
              'item-input-with-info': !!props.info || slots.info,
              'item-input-with-value': inputHasValue.value,
              'item-input-with-error-message':
                (hasErrorMessage && props.errorMessageForce) || inputInvalid.value,
              'item-input-invalid':
                (hasErrorMessage && props.errorMessageForce) || inputInvalid.value,
            },
          ),
        },
        [
          slots['content-start'] && slots['content-start'](),
          (props.media || slots.media) &&
            h('div', { class: 'item-media' }, [
              props.media && h('img', { src: props.media }),
              slots.media && slots.media(),
            ]),
          h('div', { class: 'item-inner' }, [
            slots['inner-start'] && slots['inner-start'](),
            (props.label || slots.label) &&
              h(
                'div',
                {
                  class: classNames('item-title item-label', {
                    'item-floating-label': props.floatingLabel,
                  }),
                },
                [props.label, slots.label && slots.label()],
              ),
            h(
              'div',
              {
                class: classNames('item-input-wrap', {
                  'input-dropdown':
                    props.dropdown === 'auto' ? props.type === 'select' : props.dropdown,
                }),
              },
              [
                inputEl,
                slots.input && slots.input(),
                hasErrorMessage &&
                  props.errorMessageForce &&
                  h('div', { class: 'item-input-error-message' }, [
                    props.errorMessage,
                    slots['error-message'] && slots['error-message'](),
                  ]),
                props.clearButton && h('span', { class: 'input-clear-button' }),
                (props.info || slots.info) &&
                  h('div', { class: 'item-input-info' }, [props.info, slots.info && slots.info()]),
              ],
            ),
            slots.inner && slots.inner(),
            slots['inner-end'] && slots['inner-end'](),
          ]),
          slots.content && slots.content(),
          slots['content-end'] && slots['content-end'](),
        ],
      );
      if (!props.wrap) return ItemContent;

      return h(
        'li',
        { ref: elRef, class: classNames({ disabled: props.disabled }, colorClasses(props)) },
        [
          slots['root-start'] && slots['root-start'](),
          ItemContent,
          isSortableComputed.value && h('div', { class: 'sortable-handler' }),
          slots.root && slots.root(),
          slots['root-end'] && slots['root-end'](),
        ],
      );
    };
  },
};
</script>

// src/svelte/components/list-input.svelte
<script>
  import { createEventDispatcher, onMount, afterUpdate, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, extend, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';
  import { getReactiveContext } from '../shared/get-reactive-context.js';

  import TextEditor from './text-editor.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let sortable = undefined;
  export let sortableOpposite = undefined;
  export let media = undefined;
  export let dropdown = 'auto';
  export let wrap = true;

  // Inputs
  export let input = true;
  export let type = 'text';
  export let name = undefined;
  export let value = undefined;
  export let inputmode = undefined;
  export let readonly = undefined;
  export let required = undefined;
  export let disabled = undefined;
  export let placeholder = undefined;
  export let inputId = undefined;
  export let size = undefined;
  export let accept = undefined;
  export let autocomplete = undefined;
  export let autocorrect = undefined;
  export let autocapitalize = undefined;
  export let spellcheck = undefined;
  export let autofocus = undefined;
  export let autosave = undefined;
  export let max = undefined;
  export let min = undefined;
  export let step = undefined;
  export let maxlength = undefined;
  export let minlength = undefined;
  export let multiple = undefined;
  export let inputStyle = undefined;
  export let pattern = undefined;
  export let validate = undefined;
  export let validateOnBlur = undefined;
  export let onValidate = undefined;
  export let tabindex = undefined;
  export let resizable = undefined;
  export let clearButton = undefined;

  // Form
  export let noFormStoreData = undefined;
  export let noStoreData = undefined;
  export let ignoreStoreData = undefined;

  // Error, Info
  export let errorMessage = undefined;
  export let errorMessageForce = undefined;
  export let info = undefined;

  // Outline
  export let outline = undefined;

  // Label
  export let label = undefined;
  export let inlineLabel = undefined;
  export let floatingLabel = undefined;

  // Datepicker
  export let calendarParams = undefined;
  // Colorpicker
  export let colorPickerParams = undefined;
  // Text editor
  export let textEditorParams = undefined;

  // State
  let inputEl;
  let inputFocused = false;
  let inputInvalid = false;
  let updateInputOnDidUpdate = false;
  let t4Calendar;
  let t4ColorPicker;

  export function calendarInstance() {
    return t4Calendar;
  }

  export function colorPickerInstance() {
    return t4ColorPicker;
  }

  let ListContext =
    getReactiveContext('ListContext', (newValue) => {
      ListContext = newValue || {};
    }) || {};

  $: isSortable = sortable === true || sortable === false ? sortable : ListContext.listIsSortable;
  $: isSortableOpposite = sortableOpposite || ListContext.listIsSortableOpposite;

  function domValue() {
    if (!inputEl) return undefined;
    return inputEl.value;
  }

  function inputHasValue() {
    if (type === 'datepicker' && Array.isArray(value) && value.length === 0) {
      return false;
    }
    const domV = domValue();
    return typeof value === 'undefined' ? domV || domV === 0 : value || value === 0;
  }

  function validateInput() {
    if (!app.t4 || !inputEl) return;
    const validity = inputEl.validity;
    if (!validity) return;

    if (!validity.valid) {
      if (onValidate) onValidate(false);
      if (inputInvalid !== true) {
        inputInvalid = true;
      }
    } else {
      if (onValidate) onValidate(true);
      if (inputInvalid !== false) {
        inputInvalid = false;
      }
    }
  }

  let initialWatched = false;
  function watchValue() {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (type === 'range' || type === 'toggle') return;
    if (!app.t4) return;
    updateInputOnDidUpdate = true;
    if (t4Calendar) {
      t4Calendar.setValue(value);
    }
    if (t4ColorPicker) {
      t4ColorPicker.setValue(value);
    }
  }

  function watchColorPickerParams() {
    if (!app.t4 || !t4ColorPicker) return;
    extend(t4ColorPicker.params, colorPickerParams || {});
  }

  function watchCalendarParams() {
    if (!app.t4 || !t4Calendar) return;
    extend(t4Calendar.params, calendarParams || {});
  }

  $: watchValue(value);
  $: watchColorPickerParams(colorPickerParams);
  $: watchCalendarParams(calendarParams);

  $: inputType = type === 'datepicker' || type === 'colorpicker' ? 'text' : type;

  $: needsValue = type !== 'file' && type !== 'datepicker' && type !== 'colorpicker';

  $: inputValue = (() => {
    let v;
    if (typeof value !== 'undefined') {
      v = value;
    } else {
      v = domValue();
    }
    if (typeof v === 'undefined' || v === null) return '';
    return v;
  })();

  $: hasInfoSlots = $$slots.info;
  $: hasErrorSlots = $$slots['error-message'];
  $: hasMediaSlots = $$slots.media;
  $: hasLabelSlots = $$slots.label;

  $: hasErrorMessage = !!errorMessage || hasErrorSlots;

  $: inputClasses = classNames({
    resizable: inputType === 'textarea' && resizable,
    'no-store-data': noFormStoreData || noStoreData || ignoreStoreData,
    'input-invalid': (errorMessage && errorMessageForce) || inputInvalid,
    'input-with-value': inputHasValue(),
    'input-focused': inputFocused,
  });

  $: itemContentClasses = classNames(
    'item-content item-input',
    !wrap && className,
    !wrap && { disabled },
    !wrap && colorClasses($$props),
    {
      'inline-label': inlineLabel,
      'item-input-outline': outline,
      'item-input-focused': inputFocused,
      'item-input-with-info': !!info || hasInfoSlots,
      'item-input-with-value': inputHasValue(),
      'item-input-with-error-message': (hasErrorMessage && errorMessageForce) || inputInvalid,
      'item-input-invalid': (hasErrorMessage && errorMessageForce) || inputInvalid,
    },
  );

  $: labelClasses = classNames('item-title item-label', {
    'item-floating-label': floatingLabel,
  });

  $: inputWrapClasses = classNames('item-input-wrap', {
    'input-dropdown': dropdown === 'auto' ? type === 'select' : dropdown,
  });

  $: classes = classNames(className, { disabled }, colorClasses($$props));

  function onTextareaResize(event) {
    emit('textareaResize', [event]);
  }

  function onInputNotEmpty(event) {
    emit('inputNotEmpty', [event]);
  }

  function onInputEmpty(event) {
    emit('inputEmpty', [event]);
  }

  function onInputClear(event) {
    emit('inputClear', [event]);
  }

  function onInput(...args) {
    emit('input', [...args]);

    if (!(validateOnBlur || validateOnBlur === '') && (validate || validate === '') && inputEl) {
      validateInput(inputEl);
    }
    if (inputEl && type !== 'texteditor' && type !== 'colorpicker' && type !== 'datepicker') {
      value = inputEl.value;
    }
  }

  function onFocus(...args) {
    emit('focus', [...args]);

    inputFocused = true;
  }

  function onBlur(...args) {
    emit('blur', [...args]);

    if ((validate || validate === '' || validateOnBlur || validateOnBlur === '') && inputEl) {
      validateInput();
    }
    inputFocused = false;
  }

  function onChange(...args) {
    emit('change', [...args]);

    if (type === 'texteditor') {
      emit('textEditorChange', [args[0]]);
      value = args[0];
    }
  }

  onMount(() => {
    t4ready(() => {
      if (type === 'range' || type === 'toggle') return;
      if (!inputEl) return;

      inputEl.addEventListener('input:notempty', onInputNotEmpty, false);
      if (type === 'textarea' && resizable) {
        inputEl.addEventListener('textarea:resize', onTextareaResize, false);
      }
      if (clearButton) {
        inputEl.addEventListener('input:empty', onInputEmpty, false);
        inputEl.addEventListener('input:clear', onInputClear, false);
      }

      if (type === 'datepicker') {
        t4Calendar = app.t4.calendar.create({
          inputEl,
          value,
          on: {
            change(calendar, calendarValue) {
              emit('calendarChange', [calendarValue]);
              value = calendarValue;
            },
          },
          ...(calendarParams || {}),
        });
      }
      if (type === 'colorpicker') {
        t4ColorPicker = app.t4.colorPicker.create({
          inputEl,
          value,
          on: {
            change(colorPicker, colorPickerValue) {
              emit('colorPickerChange', [colorPickerValue]);
              value = colorPickerValue;
            },
          },
          ...(colorPickerParams || {}),
        });
      }

      app.t4.input.checkEmptyState(inputEl);
      if (
        !(validateOnBlur || validateOnBlur === '') &&
        (validate || validate === '') &&
        typeof value !== 'undefined' &&
        value !== null &&
        value !== ''
      ) {
        setTimeout(() => {
          validateInput();
        }, 0);
      }
      if (resizable) {
        app.t4.input.resizeTextarea(inputEl);
      }
    });
  });

  afterUpdate(() => {
    if (!app.t4) return;
    if (updateInputOnDidUpdate) {
      if (!inputEl) return;
      updateInputOnDidUpdate = false;
      app.t4.input.checkEmptyState(inputEl);
      if (validate && !validateOnBlur) {
        validateInput();
      }
      if (resizable) {
        app.t4.input.resizeTextarea(inputEl);
      }
    }
  });

  onDestroy(() => {
    if (type === 'range' || type === 'toggle') return;
    if (!inputEl) return;
    inputEl.removeEventListener('input:notempty', onInputNotEmpty, false);
    if (type === 'textarea' && resizable) {
      inputEl.removeEventListener('textarea:resize', onTextareaResize, false);
    }
    if (clearButton) {
      inputEl.removeEventListener('input:empty', onInputEmpty, false);
      inputEl.removeEventListener('input:clear', onInputClear, false);
    }

    if (t4Calendar && t4Calendar.destroy) {
      t4Calendar.destroy();
    }
    if (t4ColorPicker && t4ColorPicker.destroy) {
      t4ColorPicker.destroy();
    }
    t4Calendar = null;
    t4ColorPicker = null;
  });
</script>

<!-- svelte-ignore a11y-autofocus -->
<!-- svelte-ignore a11y-missing-attribute -->
{#if wrap}
  <li class={classes} {...restProps($$restProps)}>
    <slot name="root-start" />
    <div class={itemContentClasses}>
      <slot name="content-start" />
      {#if isSortable && isSortableOpposite}
        <div class="sortable-handler" />
      {/if}

      {#if media || hasMediaSlots}
        <div class="item-media">
          {#if typeof media !== 'undefined'}<img src={media} />{/if}
          <slot name="media" />
        </div>
      {/if}
      <div class="item-inner">
        <slot name="inner-start" />
        {#if typeof label !== 'undefined' || hasLabelSlots}
          <div class={labelClasses}>
            {plainText(label)}
            <slot name="label" />
          </div>
        {/if}
        <div class={inputWrapClasses}>
          {#if input}
            {#if type === 'select'}
              <select
                bind:this={inputEl}
                style={inputStyle}
                {name}
                {placeholder}
                id={inputId}
                {size}
                {accept}
                {autocomplete}
                {autocorrect}
                {autocapitalize}
                {spellcheck}
                {autofocus}
                {autosave}
                {disabled}
                {max}
                {maxlength}
                {min}
                {minlength}
                {step}
                {multiple}
                {readonly}
                {required}
                {pattern}
                validate={typeof validate === 'string' && validate.length ? validate : undefined}
                data-validate={validate === true ||
                validate === '' ||
                validateOnBlur === true ||
                validateOnBlur === ''
                  ? true
                  : undefined}
                data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                  ? true
                  : undefined}
                {tabindex}
                data-error-message={errorMessageForce ? undefined : errorMessage}
                class={inputClasses}
                on:focus={onFocus}
                on:blur={onBlur}
                on:input={onInput}
                on:change={onChange}
                value={inputValue}
              >
                <slot />
              </select>
            {:else if type === 'textarea'}
              <textarea
                bind:this={inputEl}
                style={inputStyle}
                {name}
                {placeholder}
                id={inputId}
                {size}
                {inputmode}
                {accept}
                {autocomplete}
                {autocorrect}
                {autocapitalize}
                {spellcheck}
                {autofocus}
                {autosave}
                {disabled}
                {max}
                {maxlength}
                {min}
                {minlength}
                {step}
                {multiple}
                {readonly}
                {required}
                {pattern}
                validate={typeof validate === 'string' && validate.length ? validate : undefined}
                data-validate={validate === true ||
                validate === '' ||
                validateOnBlur === true ||
                validateOnBlur === ''
                  ? true
                  : undefined}
                data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                  ? true
                  : undefined}
                {tabindex}
                data-error-message={errorMessageForce ? undefined : errorMessage}
                class={inputClasses}
                on:focus={onFocus}
                on:blur={onBlur}
                on:input={onInput}
                on:change={onChange}
                value={inputValue}
              />
            {:else if type === 'texteditor'}
              <TextEditor
                value={typeof value === 'undefined' ? '' : value}
                {resizable}
                {placeholder}
                onTextEditorFocus={onFocus}
                onTextEditorBlur={onBlur}
                onTextEditorInput={onInput}
                onTextEditorChange={onChange}
                {...textEditorParams}
              />
            {:else}
              <input
                bind:this={inputEl}
                style={inputStyle}
                {name}
                type={inputType}
                {inputmode}
                {placeholder}
                id={inputId}
                {size}
                {accept}
                {autocomplete}
                {autocorrect}
                {autocapitalize}
                {spellcheck}
                {autofocus}
                {autosave}
                {disabled}
                {max}
                {maxlength}
                {min}
                {minlength}
                {step}
                {multiple}
                {readonly}
                {required}
                {pattern}
                validate={typeof validate === 'string' && validate.length ? validate : undefined}
                data-validate={validate === true ||
                validate === '' ||
                validateOnBlur === true ||
                validateOnBlur === ''
                  ? true
                  : undefined}
                data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                  ? true
                  : undefined}
                tabIndex={tabindex}
                data-error-message={errorMessageForce ? undefined : errorMessage}
                class={inputClasses}
                on:focus={onFocus}
                on:blur={onBlur}
                on:input={onInput}
                on:change={onChange}
                value={type === 'datepicker' || type === 'colorpicker' || type === 'file'
                  ? ''
                  : inputValue}
              />
            {/if}
          {/if}
          <slot name="input" />
          {#if hasErrorMessage && errorMessageForce}
            <div class="item-input-error-message">
              {plainText(errorMessage)}
              <slot name="error-message" />
            </div>
          {/if}
          {#if clearButton}<span class="input-clear-button" />{/if}
          {#if typeof info !== 'undefined' || hasInfoSlots}
            <div class="item-input-info">
              {plainText(info)}
              <slot name="info" />
            </div>
          {/if}
        </div>
        <slot name="inner" />
        <slot name="inner-end" />
      </div>
      <slot name="content" />
      <slot name="content-end" />
    </div>
    {#if isSortable && !isSortableOpposite}
      <div class="sortable-handler" />
    {/if}
    <slot name="root" />
    <slot name="root-end" />
  </li>
{:else}
  <div class={itemContentClasses} {...restProps($$restProps)}>
    <slot name="content-start" />
    {#if isSortable && isSortableOpposite}
      <div class="sortable-handler" />
    {/if}

    {#if media || hasMediaSlots}
      <div class="item-media">
        {#if typeof media !== 'undefined'}<img src={media} />{/if}
        <slot name="media" />
      </div>
    {/if}
    <div class="item-inner">
      <slot name="inner-start" />
      {#if typeof label !== 'undefined' || hasLabelSlots}
        <div class={labelClasses}>
          {plainText(label)}
          <slot name="label" />
        </div>
      {/if}
      <div class={inputWrapClasses}>
        {#if input}
          {#if type === 'select'}
            <select
              bind:this={inputEl}
              style={inputStyle}
              {name}
              {placeholder}
              id={inputId}
              {size}
              {accept}
              {autocomplete}
              {autocorrect}
              {autocapitalize}
              {spellcheck}
              {autofocus}
              {autosave}
              {disabled}
              {max}
              {maxlength}
              {min}
              {minlength}
              {step}
              {multiple}
              {readonly}
              {required}
              {pattern}
              validate={typeof validate === 'string' && validate.length ? validate : undefined}
              data-validate={validate === true ||
              validate === '' ||
              validateOnBlur === true ||
              validateOnBlur === ''
                ? true
                : undefined}
              data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                ? true
                : undefined}
              {tabindex}
              data-error-message={errorMessageForce ? undefined : errorMessage}
              class={inputClasses}
              on:focus={onFocus}
              on:blur={onBlur}
              on:input={onInput}
              on:change={onChange}
              value={inputValue}
            >
              <slot />
            </select>
          {:else if type === 'textarea'}
            <textarea
              bind:this={inputEl}
              style={inputStyle}
              {name}
              {placeholder}
              id={inputId}
              {size}
              {inputmode}
              {accept}
              {autocomplete}
              {autocorrect}
              {autocapitalize}
              {spellcheck}
              {autofocus}
              {autosave}
              {disabled}
              {max}
              {maxlength}
              {min}
              {minlength}
              {step}
              {multiple}
              {readonly}
              {required}
              {pattern}
              validate={typeof validate === 'string' && validate.length ? validate : undefined}
              data-validate={validate === true ||
              validate === '' ||
              validateOnBlur === true ||
              validateOnBlur === ''
                ? true
                : undefined}
              data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                ? true
                : undefined}
              {tabindex}
              data-error-message={errorMessageForce ? undefined : errorMessage}
              class={inputClasses}
              on:focus={onFocus}
              on:blur={onBlur}
              on:input={onInput}
              on:change={onChange}
              value={inputValue}
            />
          {:else if type === 'texteditor'}
            <TextEditor
              value={typeof value === 'undefined' ? '' : value}
              {resizable}
              {placeholder}
              onTextEditorFocus={onFocus}
              onTextEditorBlur={onBlur}
              onTextEditorInput={onInput}
              onTextEditorChange={onChange}
              {...textEditorParams}
            />
          {:else}
            <input
              bind:this={inputEl}
              style={inputStyle}
              {name}
              type={inputType}
              {inputmode}
              {placeholder}
              id={inputId}
              {size}
              {accept}
              {autocomplete}
              {autocorrect}
              {autocapitalize}
              {spellcheck}
              {autofocus}
              {autosave}
              {disabled}
              {max}
              {maxlength}
              {min}
              {minlength}
              {step}
              {multiple}
              {readonly}
              {required}
              {pattern}
              validate={typeof validate === 'string' && validate.length ? validate : undefined}
              data-validate={validate === true ||
              validate === '' ||
              validateOnBlur === true ||
              validateOnBlur === ''
                ? true
                : undefined}
              data-validate-on-blur={validateOnBlur === true || validateOnBlur === ''
                ? true
                : undefined}
              tabIndex={tabindex}
              data-error-message={errorMessageForce ? undefined : errorMessage}
              class={inputClasses}
              on:focus={onFocus}
              on:blur={onBlur}
              on:input={onInput}
              on:change={onChange}
              value={type === 'datepicker' || type === 'colorpicker' || type === 'file'
                ? ''
                : inputValue}
            />
          {/if}
        {/if}
        <slot name="input" />
        {#if hasErrorMessage && errorMessageForce}
          <div class="item-input-error-message">
            {plainText(errorMessage)}
            <slot name="error-message" />
          </div>
        {/if}
        {#if clearButton}<span class="input-clear-button" />{/if}
        {#if typeof info !== 'undefined' || hasInfoSlots}
          <div class="item-input-info">
            {plainText(info)}
            <slot name="info" />
          </div>
        {/if}
      </div>
      <slot name="inner" />
      <slot name="inner-end" />
    </div>
    <slot name="content" />
    <slot name="content-end" />
  </div>
{/if}
