// src/react/components/navbar.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import { classNames, getExtraAttrs, emit, getSlots } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';
import { useTheme } from '../shared/use-theme.js';

import NavLeft from './nav-left.js';
import NavTitle from './nav-title.js';
import NavRight from './nav-right.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  backLink? : boolean | string
  backLinkUrl? : string
  backLinkForce? : boolean
  backLinkShowText? : boolean
  sliding? : boolean
  title? : string
  subtitle? : string
  hidden? : boolean
  noShadow? : boolean
  noHairline? : boolean
  innerClass? : string
  innerClassName? : string
  large? : boolean
  largeTransparent? : boolean
  transparent? : boolean
  titleLarge? : string
  COLOR_PROPS
  onNavbarHide? : (...args: any[]) => void
  onNavbarShow? : (...args: any[]) => void
  onNavbarExpand? : (...args: any[]) => void
  onNavbarCollapse? : (...args: any[]) => void
  onNavbarTransparentShow? : (...args: any[]) => void
  onNavbarTransparentHide? : (...args: any[]) => void
  onBackClick? : (event?: any) => void
  onClickBack? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const Navbar = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    sliding = true,
    large,
    largeTransparent,
    transparent,
    hidden,
    noShadow,
    noHairline,
    backLink,
    backLinkForce,
    backLinkUrl,
    backLinkShowText,
    title,
    subtitle,
    titleLarge,
    innerClass,
    innerClassName,
  } = props;
  const routerPositionClass = useRef('');
  const largeCollapsed = useRef(false);
  const routerNavbarRole = useRef(null);
  const routerNavbarRoleDetailRoot = useRef(false);
  const routerNavbarMasterStack = useRef(false);
  const transparentVisible = useRef(false);
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const theme = useTheme();

  const onHide = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    emit(props, 'navbarHide');
  };
  const onShow = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    emit(props, 'navbarShow');
  };
  const onExpand = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    largeCollapsed.current = false;
    emit(props, 'navbarExpand');
  };
  const onCollapse = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    largeCollapsed.current = true;
    emit(props, 'navbarCollapse');
  };
  const onNavbarTransparentShow = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    transparentVisible.current = true;
    emit(props, 'navbarTransparentShow');
  };
  const onNavbarTransparentHide = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    transparentVisible.current = false;
    emit(props, 'navbarTransparentHide');
  };
  const onNavbarPosition = (navbarEl, position) => {
    if (elRef.current !== navbarEl) return;
    routerPositionClass.current = position ? `navbar-${position}` : '';
  };
  const onNavbarRole = (navbarEl, rolesData) => {
    if (elRef.current !== navbarEl) return;
    routerNavbarRole.current = rolesData.role;
    routerNavbarRoleDetailRoot.current = rolesData.detailRoot;
  };
  const onNavbarMasterStack = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    routerNavbarMasterStack.current = true;
  };
  const onNavbarMasterUnstack = (navbarEl) => {
    if (elRef.current !== navbarEl) return;
    routerNavbarMasterStack.current = false;
  };
  const hide = (animate) => {
    if (!t4) return;
    t4.navbar.hide(elRef.current, animate);
  };
  const show = (animate) => {
    if (!t4) return;
    t4.navbar.show(elRef.current, animate);
  };
  const size = () => {
    if (!t4) return;
    t4.navbar.size(elRef.current);
  };
  const onBackClick = (event) => {
    emit(props, 'backClick clickBack', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    hide,
    show,
    size,
  }));

  const attachEvents = () => {
    if (!elRef.current) return;
    t4ready(() => {
      t4.navbar.size(elRef.current);
      t4.on('navbarShow', onShow);
      t4.on('navbarHide', onHide);
      t4.on('navbarCollapse', onCollapse);
      t4.on('navbarExpand', onExpand);
      t4.on('navbarPosition', onNavbarPosition);
      t4.on('navbarRole', onNavbarRole);
      t4.on('navbarMasterStack', onNavbarMasterStack);
      t4.on('navbarMasterUnstack', onNavbarMasterUnstack);
      t4.on('navbarTransparentShow', onNavbarTransparentShow);
      t4.on('navbarTransparentHide', onNavbarTransparentHide);
    });
  };

  const detachEvents = () => {
    if (!t4) return;
    t4.off('navbarShow', onShow);
    t4.off('navbarHide', onHide);
    t4.off('navbarCollapse', onCollapse);
    t4.off('navbarExpand', onExpand);
    t4.off('navbarPosition', onNavbarPosition);
    t4.off('navbarRole', onNavbarRole);
    t4.off('navbarMasterStack', onNavbarMasterStack);
    t4.off('navbarMasterUnstack', onNavbarMasterUnstack);
    t4.off('navbarTransparentShow', onNavbarTransparentShow);
    t4.off('navbarTransparentHide', onNavbarTransparentHide);
  };

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    return detachEvents;
  });

  const slots = getSlots(props);

  let leftEl;
  let titleEl;
  let rightEl;
  let titleLargeEl;

  const addLeftTitleClass = theme && theme.ios && t4 && !t4.params.navbar.iosCenterTitle;
  const addCenterTitleClass =
    (theme && theme.md && t4 && t4.params.navbar.mdCenterTitle) ||
    (theme && theme.aurora && t4 && t4.params.navbar.auroraCenterTitle);

  const isLarge = large || largeTransparent;
  const isTransparent = transparent || (isLarge && largeTransparent);
  const isTransparentVisible = isTransparent && transparentVisible.current;

  const classes = classNames(
    className,
    'navbar',
    routerPositionClass.current,
    {
      'navbar-hidden': hidden,
      'navbar-large': isLarge,
      'navbar-large-collapsed': isLarge && largeCollapsed.current,
      'navbar-transparent': isTransparent,
      'navbar-transparent-visible': isTransparentVisible,
      'navbar-master': routerNavbarRole.current === 'master',
      'navbar-master-detail': routerNavbarRole.current === 'detail',
      'navbar-master-detail-root': routerNavbarRoleDetailRoot.current === true,
      'navbar-master-stacked': routerNavbarMasterStack.current === true,
      'no-shadow': noShadow,
      'no-hairline': noHairline,
    },
    colorClasses(props),
  );

  if (backLink || slots['nav-left'] || slots.left) {
    leftEl = (
      <NavLeft
        backLink={backLink}
        backLinkUrl={backLinkUrl}
        backLinkForce={backLinkForce}
        backLinkShowText={backLinkShowText}
        onBackClick={onBackClick}
      >
        {slots['nav-left']}
        {slots.left}
      </NavLeft>
    );
  }
  if (title || subtitle || slots.title) {
    titleEl = (
      <NavTitle title={title} subtitle={subtitle}>
        {slots.title}
      </NavTitle>
    );
  }
  if (slots['nav-right'] || slots.right) {
    rightEl = (
      <NavRight>
        {slots['nav-right']}
        {slots.right}
      </NavRight>
    );
  }
  let largeTitle = titleLarge;
  if (!largeTitle && large && title) largeTitle = title;
  if (largeTitle || slots['title-large']) {
    titleLargeEl = (
      <div className="title-large">
        <div className="title-large-text">
          {largeTitle || ''}
          {slots['title-large']}
        </div>
      </div>
    );
  }
  const innerEl = (
    <div
      className={classNames('navbar-inner', innerClass, innerClassName, {
        sliding,
        'navbar-inner-left-title': addLeftTitleClass,
        'navbar-inner-centered-title': addCenterTitleClass,
      })}
    >
      {leftEl}
      {titleEl}
      {rightEl}
      {titleLargeEl}
      {slots.default}
    </div>
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      <div className="navbar-bg" />
      {slots['before-inner']}
      {innerEl}
      {slots['after-inner']}
    </div>
  );
});

Navbar.displayName = 't4-navbar';

export default Navbar;

// src/svelte/components/navbar.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy, afterUpdate } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { t4ready, app } from '../shared/t4.js';
  import { useTheme } from '../shared/use-theme.js';

  import NavLeft from './nav-left.svelte';
  import NavTitle from './nav-title.svelte';
  import NavRight from './nav-right.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let backLink = undefined;
  export let backLinkUrl = undefined;
  export let backLinkForce = false;
  export let backLinkShowText = undefined;
  export let sliding = true;
  export let title = undefined;
  export let subtitle = undefined;
  export let hidden = false;
  export let noShadow = false;
  export let noHairline = false;
  export let innerClass = undefined;
  export let innerClassName = undefined;
  export let large = false;
  export let largeTransparent = false;
  export let transparent = false;
  export let titleLarge = undefined;

  export let t4Slot = 'fixed';

  let el;
  let theme = useTheme((t) => {
    theme = t;
  });
  let routerPositionClass = '';
  let largeCollapsed = false;
  let routerNavbarRole = null;
  let routerNavbarRoleDetailRoot = false;
  let routerNavbarMasterStack = false;
  let transparentVisible = false;

  export function hide(animate) {
    app.t4.navbar.hide(el, animate);
  }
  export function show(animate) {
    app.t4.navbar.show(el, animate);
  }
  export function size() {
    app.t4.navbar.size(el);
  }

  // eslint-disable-next-line
  $: hasLeftSlots = $$slots['nav-left'] || $$slots['left'];
  // eslint-disable-next-line
  $: hasRightSlots = $$slots['nav-right'] || $$slots['right'];
  // eslint-disable-next-line
  $: hasTitleSlots = $$slots['title'];

  $: largeTitle = titleLarge || (large && title);
  // eslint-disable-next-line
  $: hasTitleLargeSlots = $$slots['title-large'];

  $: addLeftTitleClass = theme && theme.ios && app.t4 && !app.t4.params.navbar.iosCenterTitle;
  $: addCenterTitleClass =
    (theme && theme.md && app.t4 && app.t4.params.navbar.mdCenterTitle) ||
    (theme && theme.aurora && app.t4 && app.t4.params.navbar.auroraCenterTitle);

  $: isLarge = large || largeTransparent;
  $: isTransparent = transparent || (isLarge && largeTransparent);
  $: isTransparentVisible = isTransparent && transparentVisible;

  $: classes = classNames(
    className,
    'navbar',
    routerPositionClass,
    {
      'navbar-hidden': hidden,
      'navbar-large': isLarge,
      'navbar-large-collapsed': isLarge && largeCollapsed,
      'navbar-transparent': isTransparent,
      'navbar-transparent-visible': isTransparentVisible,
      'navbar-master': routerNavbarRole === 'master',
      'navbar-master-detail': routerNavbarRole === 'detail',
      'navbar-master-detail-root': routerNavbarRoleDetailRoot === true,
      'navbar-master-stacked': routerNavbarMasterStack === true,
      'no-shadow': noShadow,
      'no-hairline': noHairline,
    },
    colorClasses($$props),
  );

  $: innerClasses = classNames('navbar-inner', innerClass, innerClassName, {
    sliding,
    'navbar-inner-left-title': addLeftTitleClass,
    'navbar-inner-centered-title': addCenterTitleClass,
  });

  function onHide(navbarEl) {
    if (el !== navbarEl) return;
    emit('navbarHide');
  }
  function onShow(navbarEl) {
    if (el !== navbarEl) return;
    emit('navbarShow');
  }
  function onNavbarTransparentShow(navbarEl) {
    if (el !== navbarEl) return;
    transparentVisible = true;
    emit('navbarTransparentShow');
  }
  function onNavbarTransparentHide(navbarEl) {
    if (el !== navbarEl) return;
    transparentVisible = false;
    emit('navbarTransparentHide');
  }
  function onExpand(navbarEl) {
    if (el !== navbarEl) return;
    largeCollapsed = false;
    emit('navbarExpand');
  }
  function onCollapse(navbarEl) {
    if (el !== navbarEl) return;
    largeCollapsed = true;
    emit('navbarCollapse');
  }
  function onNavbarPosition(navbarEl, position) {
    if (el !== navbarEl) return;
    routerPositionClass = position ? `navbar-${position}` : position;
  }
  function onNavbarRole(navbarEl, rolesData) {
    if (el !== navbarEl) return;
    routerNavbarRole = rolesData.role;
    routerNavbarRoleDetailRoot = rolesData.detailRoot;
  }
  function onNavbarMasterStack(navbarEl) {
    if (el !== navbarEl) return;
    routerNavbarMasterStack = true;
  }
  function onNavbarMasterUnstack(navbarEl) {
    if (el !== navbarEl) return;
    routerNavbarMasterStack = false;
  }
  function onBackClick() {
    emit('clickBack');
  }

  function mountNavbar() {
    app.t4.on('navbarShow', onShow);
    app.t4.on('navbarHide', onHide);
    app.t4.on('navbarCollapse', onCollapse);
    app.t4.on('navbarExpand', onExpand);
    app.t4.on('navbarPosition', onNavbarPosition);
    app.t4.on('navbarRole', onNavbarRole);
    app.t4.on('navbarMasterStack', onNavbarMasterStack);
    app.t4.on('navbarMasterUnstack', onNavbarMasterUnstack);
    app.t4.on('navbarTransparentShow', onNavbarTransparentShow);
    app.t4.on('navbarTransparentHide', onNavbarTransparentHide);
  }
  function destroyNavbar() {
    app.t4.off('navbarShow', onShow);
    app.t4.off('navbarHide', onHide);
    app.t4.off('navbarCollapse', onCollapse);
    app.t4.off('navbarExpand', onExpand);
    app.t4.off('navbarPosition', onNavbarPosition);
    app.t4.off('navbarRole', onNavbarRole);
    app.t4.off('navbarMasterStack', onNavbarMasterStack);
    app.t4.off('navbarMasterUnstack', onNavbarMasterUnstack);
    app.t4.off('navbarTransparentShow', onNavbarTransparentShow);
    app.t4.off('navbarTransparentHide', onNavbarTransparentHide);
  }

  onMount(() => {
    t4ready(() => {
      mountNavbar();
    });
  });
  afterUpdate(() => {
    if (!app.t4) return;
    app.t4.navbar.size(el);
  });
  onDestroy(() => {
    if (!app.t4) return;
    destroyNavbar();
  });
</script>

<div class={classes} bind:this={el} data-t4-slot={t4Slot} {...restProps($$restProps)}>
  <div class="navbar-bg" />
  <slot name="before-inner" />
  <div class={innerClasses}>
    {#if backLink || hasLeftSlots}
      <NavLeft {backLink} {backLinkUrl} {backLinkForce} {backLinkShowText} {onBackClick}>
        <slot name="nav-left" />
        <slot name="left" />
      </NavLeft>
    {/if}
    {#if title || subtitle || hasTitleSlots}
      <NavTitle {title} {subtitle}>
        <slot name="title" />
      </NavTitle>
    {/if}
    {#if hasRightSlots}
      <NavRight>
        <slot name="nav-right" />
        <slot name="right" />
      </NavRight>
    {/if}
    {#if largeTitle || hasTitleLargeSlots}
      <div class="title-large">
        <div class="title-large-text">
          {plainText(largeTitle)}
          <slot name="title-large" />
        </div>
      </div>
    {/if}
    <slot />
  </div>
  <slot name="after-inner" />
</div>
