// src/vue/components/popover.vue
<template>
  <div ref="elRef" :class="classes">
    <div class="popover-angle" />
    <div class="popover-inner"><slot /></div>
  </div>
</template>
<script>
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';
import { modalStateClasses } from '../shared/modal-state-classes.js';

export default {
  name: 't4-popover',
  props: {
    opened: Boolean,
    animate: {
      type: Boolean,
      default: undefined,
    },
    targetEl: {
      type: [String, Object],
      default: undefined,
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    backdropEl: {
      type: [String, Object],
      default: undefined,
    },
    closeByBackdropClick: {
      type: Boolean,
      default: undefined,
    },
    closeByOutsideClick: {
      type: Boolean,
      default: undefined,
    },
    closeOnEscape: {
      type: Boolean,
      default: undefined,
    },
    containerEl: {
      type: [String, Object],
      default: undefined,
    },
    verticalPosition: {
      type: String,
      default: undefined,
    },
    ...colorProps,
  },
  emits: ['popover:open', 'popover:opened', 'popover:close', 'popover:closed', 'update:opened'],
  setup(props, { emit }) {
    const t4Popover = ref(null);
    // eslint-disable-next-line
    let isOpened = props.opened;
    let isClosing = false;
    const elRef = ref(null);

    const onOpen = (instance) => {
      isOpened = true;
      isClosing = false;
      emit('popover:open', instance);
      emit('update:opened', true);
    };
    const onOpened = (instance) => {
      emit('popover:opened', instance);
    };
    const onClose = (instance) => {
      isOpened = false;
      isClosing = true;
      emit('popover:close', instance);
    };
    const onClosed = (instance) => {
      isClosing = false;
      emit('popover:closed', instance);
      emit('update:opened', false);
    };

    watch(
      () => props.opened,
      (value) => {
        if (!t4Popover.value) return;
        if (value) {
          t4Popover.value.open();
        } else {
          t4Popover.value.close();
        }
      },
    );

    onMounted(() => {
      if (!elRef.value) return;
      const popoverParams = {
        el: elRef.value,
        on: {
          open: onOpen,
          opened: onOpened,
          close: onClose,
          closed: onClosed,
        },
      };
      const {
        targetEl,
        closeByBackdropClick,
        closeByOutsideClick,
        closeOnEscape,
        backdrop,
        backdropEl,
        containerEl,
        verticalPosition,
      } = props;
      if (typeof targetEl !== 'undefined') popoverParams.targetEl = targetEl;
      if (typeof closeByBackdropClick !== 'undefined')
        popoverParams.closeByBackdropClick = closeByBackdropClick;
      if (typeof closeByOutsideClick !== 'undefined')
        popoverParams.closeByOutsideClick = closeByOutsideClick;
      if (typeof closeOnEscape !== 'undefined') popoverParams.closeOnEscape = closeOnEscape;
      if (typeof backdrop !== 'undefined') popoverParams.backdrop = backdrop;
      if (typeof backdropEl !== 'undefined') popoverParams.backdropEl = backdropEl;
      if (typeof containerEl !== 'undefined') popoverParams.containerEl = containerEl;
      if (typeof verticalPosition !== 'undefined')
        popoverParams.verticalPosition = verticalPosition;

      t4ready(() => {
        t4Popover.value = t4.popover.create(popoverParams);
        if (props.opened) {
          t4Popover.value.open(targetEl, false);
        }
      });
    });

    onBeforeUnmount(() => {
      if (t4Popover.value) {
        t4Popover.value.destroy();
      }
      t4Popover.value = null;
    });

    const classes = computed(() =>
      classNames('popover', modalStateClasses({ isOpened, isClosing }), colorClasses(props)),
    );

    return {
      elRef,
      classes,
    };
  },
};
</script>

// src/svelte/components/popover.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';
  import { modalStateClasses } from '../shared/modal-state-classes.js';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let opened = undefined;
  export let animate = undefined;
  export let targetEl = undefined;
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let closeByBackdropClick = undefined;
  export let closeByOutsideClick = undefined;
  export let closeOnEscape = undefined;
  export let containerEl = undefined;
  export let verticalPosition = undefined;

  let el;
  let t4Popover;

  const state = {
    isOpened: opened,
    isClosing: false,
  };

  export function instance() {
    return t4Popover;
  }

  $: classes = classNames(className, 'popover', modalStateClasses(state), colorClasses($$props));

  function onOpen(instance) {
    Object.assign(state, {
      isOpened: true,
      isClosing: false,
    });
    emit('popoverOpen', [instance]);
    opened = true;
  }
  function onOpened(instance) {
    emit('popoverOpened', [instance]);
  }
  function onClose(instance) {
    Object.assign(state, {
      isOpened: false,
      isClosing: true,
    });
    emit('popoverClose', [instance]);
  }
  function onClosed(instance) {
    Object.assign(state, {
      isClosing: false,
    });
    emit('popoverClosed', [instance]);
    opened = false;
  }

  let initialWatched = false;
  function watchOpened(openedPassed) {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (!t4Popover) return;
    if (openedPassed) t4Popover.open();
    else t4Popover.close();
  }

  $: watchOpened(opened);

  onMount(() => {
    const params = {
      el,
      on: {
        open: onOpen,
        opened: onOpened,
        close: onClose,
        closed: onClosed,
      },
    };
    if (targetEl) params.targetEl = targetEl;

    if (typeof animate !== 'undefined') params.animate = animate;
    if (typeof closeByBackdropClick !== 'undefined')
      params.closeByBackdropClick = closeByBackdropClick;
    if (typeof closeByOutsideClick !== 'undefined')
      params.closeByOutsideClick = closeByOutsideClick;
    if (typeof closeOnEscape !== 'undefined') params.closeOnEscape = closeOnEscape;
    if (typeof backdrop !== 'undefined') params.backdrop = backdrop;
    if (typeof backdropEl !== 'undefined') params.backdropEl = backdropEl;
    if (typeof containerEl !== 'undefined') params.containerEl = containerEl;
    if (typeof verticalPosition !== 'undefined') params.verticalPosition = verticalPosition;

    t4ready(() => {
      t4Popover = app.t4.popover.create(params);
      if (opened) {
        t4Popover.open(targetEl, false);
      }
    });
  });

  onDestroy(() => {
    if (t4Popover) t4Popover.destroy();
    t4Popover = null;
  });
</script>

<div class={classes} bind:this={el} {...restProps($$restProps)}>
  <div class="popover-angle" />
  <div class="popover-inner">
    <slot popover={t4Popover} />
  </div>
</div>
