// src/react/components/preloader.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, extend } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { useTheme } from '../shared/use-theme.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  size? : number | string;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const Preloader = forwardRef((props, ref) => {
  const theme = useTheme();
  const { className, id, style, size } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const preloaderStyle = {};
  let sizeComputed = size;
  if (sizeComputed && typeof sizeComputed === 'string' && sizeComputed.indexOf('px') >= 0) {
    sizeComputed = sizeComputed.replace('px', '');
  }
  if (sizeComputed) {
    preloaderStyle.width = `${sizeComputed}px`;
    preloaderStyle.height = `${sizeComputed}px`;
    preloaderStyle['--t4-preloader-size'] = `${sizeComputed}px`;
  }
  if (style) extend(preloaderStyle, style || {});

  let innerEl;
  if (theme && theme.md) {
    innerEl = (
      <span className="preloader-inner">
        <svg viewBox="0 0 36 36">
          <circle cx="18" cy="18" r="16" />
        </svg>
      </span>
    );
  } else if (theme && theme.ios) {
    innerEl = (
      <span className="preloader-inner">
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
        <span className="preloader-inner-line" />
      </span>
    );
  } else if (theme && theme.aurora) {
    innerEl = (
      <span className="preloader-inner">
        <span className="preloader-inner-circle" />
      </span>
    );
  } else if (!theme) {
    innerEl = <span className="preloader-inner" />;
  }

  const classes = classNames(className, 'preloader', colorClasses(props));
  return (
    <span id={id} style={preloaderStyle} className={classes} ref={elRef} {...extraAttrs}>
      {innerEl}
    </span>
  );
});

Preloader.displayName = 't4-preloader';

export default Preloader;

// src/svelte/components/preloader.svelte
<script>
  import { restProps } from '../shared/rest-props.js';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { useTheme } from '../shared/use-theme.js';

  export let style = undefined;

  let className = undefined;
  export { className as class };
  export let size = undefined;

  let theme = useTheme((t) => {
    theme = t;
  });

  $: sizeComputed =
    size && typeof size === 'string' && size.indexOf('px') >= 0 ? size.replace('px', '') : size;

  $: preloaderStyle = (
    (style || '') +
    (sizeComputed
      ? `;width: ${sizeComputed}px; height: ${sizeComputed}px; --t4-preloader-size: ${sizeComputed}px`
      : '')
  ).replace(';;', ';');

  $: classes = classNames(className, 'preloader', colorClasses($$props));
</script>

<span style={preloaderStyle} class={classes} {...restProps($$restProps)}>
  {#if theme && theme.md}
    <span class="preloader-inner">
      <svg viewBox="0 0 36 36">
        <circle cx="18" cy="18" r="16" />
      </svg>
    </span>
  {:else if theme && theme.ios}
    <span class="preloader-inner">
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
    </span>
  {:else if theme && theme.aurora}
    <span class="preloader-inner"> <span class="preloader-inner-circle" /> </span>
  {:else}<span class="preloader-inner" />{/if}
</span>
