// src/vue/components/preloader.vue
<template>
  <div :class="classes" :style="style">
    <span v-if="theme && theme.md" class="preloader-inner">
      <svg viewBox="0 0 36 36">
        <circle cx="18" cy="18" r="16" />
      </svg>
    </span>
    <span v-else-if="theme && theme.ios" class="preloader-inner">
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
    </span>
    <span v-else-if="theme && theme.aurora" class="preloader-inner">
      <span class="preloader-inner-circle" />
    </span>
    <span v-else-if="!theme" class="preloader-inner" />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTheme } from '../shared/use-theme.js';

export default {
  name: 't4-preloader',
  props: {
    size: [Number, String],
    ...colorProps,
  },
  setup(props) {
    const theme = useTheme();
    const classes = computed(() => classNames('preloader', colorClasses(props)));
    const style = computed(() => {
      const preloaderStyle = {};
      let sizeComputed = props.size;
      if (sizeComputed && typeof sizeComputed === 'string' && sizeComputed.indexOf('px') >= 0) {
        sizeComputed = sizeComputed.replace('px', '');
      }
      if (sizeComputed) {
        preloaderStyle.width = `${sizeComputed}px`;
        preloaderStyle.height = `${sizeComputed}px`;
        preloaderStyle['--t4-preloader-size'] = `${sizeComputed}px`;
      }
      return preloaderStyle;
    });
    return { classes, style, theme };
  },
};
</script>

// src/svelte/components/preloader.svelte
<script>
  import { restProps } from '../shared/rest-props.js';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { useTheme } from '../shared/use-theme.js';

  export let style = undefined;

  let className = undefined;
  export { className as class };
  export let size = undefined;

  let theme = useTheme((t) => {
    theme = t;
  });

  $: sizeComputed =
    size && typeof size === 'string' && size.indexOf('px') >= 0 ? size.replace('px', '') : size;

  $: preloaderStyle = (
    (style || '') +
    (sizeComputed
      ? `;width: ${sizeComputed}px; height: ${sizeComputed}px; --t4-preloader-size: ${sizeComputed}px`
      : '')
  ).replace(';;', ';');

  $: classes = classNames(className, 'preloader', colorClasses($$props));
</script>

<span style={preloaderStyle} class={classes} {...restProps($$restProps)}>
  {#if theme && theme.md}
    <span class="preloader-inner">
      <svg viewBox="0 0 36 36">
        <circle cx="18" cy="18" r="16" />
      </svg>
    </span>
  {:else if theme && theme.ios}
    <span class="preloader-inner">
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
      <span class="preloader-inner-line" />
    </span>
  {:else if theme && theme.aurora}
    <span class="preloader-inner"> <span class="preloader-inner-circle" /> </span>
  {:else}<span class="preloader-inner" />{/if}
</span>
