// src/vue/components/progressbar.vue
<template>
  <span ref="elRef" :class="classes" :data-progress="progress">
    <span :style="transformStyle" />
  </span>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4 } from '../shared/t4.js';

export default {
  name: 't4-progressbar',
  props: {
    progress: Number,
    infinite: Boolean,
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    const set = (newProgress, speed) => {
      if (!t4) return;
      t4.progressbar.set(elRef.value, newProgress, speed);
    };

    const transformStyle = computed(() => ({
      transform: props.progress ? `translate3d(${-100 + props.progress}%, 0, 0)` : '',
      WebkitTransform: props.progress ? `translate3d(${-100 + props.progress}%, 0, 0)` : '',
    }));

    const classes = computed(() =>
      classNames(
        'progressbar',
        {
          'progressbar-infinite': props.infinite,
        },
        colorClasses(props),
      ),
    );
    return { classes, set, transformStyle, elRef };
  },
};
</script>

// src/svelte/components/progressbar.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app } from '../shared/t4.js';

  let className = undefined;
  export { className as class };

  export let progress = 0;
  export let infinite = false;

  let el;

  export function set(progress, speed) {
    if (!app.t4) return;
    app.t4.progressbar.set(el, progress, speed);
  }

  $: classes = classNames(
    className,
    'progressbar',
    {
      'progressbar-infinite': infinite,
    },
    colorClasses($$props),
  );

  $: transformStyle = {
    transform: progress ? `translate3d(${-100 + progress}%, 0, 0)` : '',
    WebkitTransform: progress ? `translate3d(${-100 + progress}%, 0, 0)` : '',
  };
</script>

<span bind:this={el} class={classes} data-progress={progress} {...restProps($$restProps)}>
  <span style={transformStyle} />
</span>
