// src/vue/components/subnavbar.vue
<template>
  <div :class="classes">
    <div v-if="inner" class="subnavbar-inner">
      <div v-if="title" class="subnavbar-title">{{ title }}</div>
      <slot />
    </div>
    <slot v-else />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-subnavbar',
  props: {
    sliding: Boolean,
    title: String,
    inner: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'subnavbar',
        {
          sliding: props.sliding,
        },
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>

// src/svelte/components/subnavbar.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  export let sliding = undefined;
  export let title = undefined;
  export let inner = true;
  export let t4Slot = 'fixed';

  $: classes = classNames(
    className,
    'subnavbar',
    {
      sliding,
    },
    colorClasses($$props),
  );
</script>

<div class={classes} data-t4-slot={t4Slot} {...restProps($$restProps)}>
  {#if inner}
    <div class="subnavbar-inner">
      {#if title}
        <div class="subnavbar-title">{title}</div>
      {/if}
      <slot />
    </div>
  {:else}
    <slot />
  {/if}
</div>
