// src/vue/components/treeview-item.vue
<template>
  <div ref="elRef" :class="classes">
    <component :is="itemRootTag" :class="itemRootClasses" v-bind="itemRootAttrs" @click="onClick">
      <slot name="root-start" />
      <div v-if="needToggle" className="treeview-toggle" />
      <div className="treeview-item-content">
        <slot name="content-start" />
        <t4-use-icon v-if="icon" :icon="icon" />
        <slot name="media" />
        <div className="treeview-item-label">
          <slot name="label-start" />
          {{ label }}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </component>
    <div v-if="hasChildren" className="treeview-item-children">
      <slot name="children-start" />
      <slot />
      <slot name="children" />
    </div>
  </div>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils.js';
import {
  colorClasses,
  colorProps,
  actionsAttrs,
  actionsProps,
  actionsClasses,
  routerAttrs,
  routerProps,
  routerClasses,
  iconProps,
} from '../shared/mixins.js';
import { useIcon } from '../shared/use-icon.js';
import { t4ready, t4 } from '../shared/t4.js';

import t4UseIcon from './use-icon.js';

export default {
  name: 't4-treeview-item',
  components: {
    t4UseIcon,
  },
  props: {
    toggle: {
      type: Boolean,
      default: undefined,
    },
    itemToggle: Boolean,
    selectable: Boolean,
    selected: Boolean,
    opened: Boolean,
    label: String,
    loadChildren: Boolean,
    link: {
      type: [Boolean, String],
      default: undefined,
    },
    ...colorProps,
    ...actionsProps,
    ...iconProps,
    ...routerProps,
  },
  emits: ['click', 'treeview:open', 'treeview:close', 'treeview:loadchildren'],
  setup(props, { slots, emit }) {
    const elRef = ref(null);

    const hasChildren = computed(() => {
      return slots.default || slots.children || slots['children-start'];
    });

    const needToggle = computed(() =>
      typeof props.toggle === 'undefined' ? hasChildren.value : props.toggle,
    );

    const icon = computed(() => useIcon(props));

    const onClick = (event) => {
      emit('click', event);
    };
    const onOpen = (el) => {
      if (elRef.value !== el) return;
      emit('treeview:open', el);
    };
    const onClose = (el) => {
      if (elRef.value !== el) return;
      emit('treeview:close', el);
    };
    const onLoadChildren = (el, done) => {
      if (elRef.value !== el) return;
      emit('treeview:loadchildren', el, done);
    };

    const attachEvents = () => {
      if (!elRef.value) return;
      t4ready(() => {
        t4.on('treeviewOpen', onOpen);
        t4.on('treeviewClose', onClose);
        t4.on('treeviewLoadChildren', onLoadChildren);
      });
    };

    const detachEvents = () => {
      if (!t4) return;
      t4.off('treeviewOpen', onOpen);
      t4.off('treeviewClose', onClose);
      t4.off('treeviewLoadChildren', onLoadChildren);
    };

    onMounted(() => attachEvents());
    onBeforeUnmount(() => detachEvents());

    const classes = computed(() =>
      classNames(
        'treeview-item',
        {
          'treeview-item-opened': props.opened,
          'treeview-load-children': props.loadChildren,
        },
        colorClasses(props),
      ),
    );

    const itemRootClasses = computed(() =>
      classNames(
        'treeview-item-root',
        {
          'treeview-item-selectable': props.selectable,
          'treeview-item-selected': props.selected,
          'treeview-item-toggle': props.itemToggle,
        },
        routerClasses(props),
        actionsClasses(props),
      ),
    );

    const itemRootTag = computed(() => (props.link || props.link === '' ? 'a' : 'div'));

    const itemRootAttrs = computed(() => {
      let href = props.link;
      if (props.link === true) href = '#';
      if (props.link === false) href = undefined; // no href attribute
      return {
        href,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    return {
      itemRootTag,
      itemRootAttrs,
      itemRootClasses,
      classes,
      icon,
      onClick,
      hasChildren,
      needToggle,
      elRef,
    };
  },
};
</script>

// src/svelte/components/treeview-item.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import {
    colorClasses,
    routerAttrs,
    routerClasses,
    actionsClasses,
    actionsAttrs,
  } from '../shared/mixins.js';
  import { classNames, extend, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';
  import { app, t4ready } from '../shared/t4.js';
  import { useIcon } from '../shared/use-icon.js';

  import UseIcon from './use-icon.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let toggle = undefined;
  export let itemToggle = false;
  export let selectable = false;
  export let selected = false;
  export let opened = false;
  export let label = undefined;
  export let loadChildren = false;
  export let link = undefined;

  let el;

  $: classes = classNames(
    className,
    'treeview-item',
    {
      'treeview-item-opened': opened,
      'treeview-load-children': loadChildren,
    },
    colorClasses($$props),
  );

  $: itemRootClasses = classNames(
    'treeview-item-root',
    {
      'treeview-item-selectable': selectable,
      'treeview-item-selected': selected,
      'treeview-item-toggle': itemToggle,
    },
    routerClasses($$props),
    actionsClasses($$props),
  );

  $: itemRootAttrs = extend(
    {
      href: link === true ? '#' : link || undefined,
    },
    routerAttrs($$props),
    actionsAttrs($$props),
  );

  /* eslint-disable no-undef */
  $: hasChildren = $$slots.default || $$slots.children || $$slots['children-start'];
  /* eslint-enable no-undef */

  $: needToggle = typeof toggle === 'undefined' ? hasChildren : toggle;

  $: icon = useIcon($$props);

  $: treeviewRootTag = link || link === '' ? 'a' : 'div';

  function onClick(e) {
    emit('click', [e]);
  }
  function onOpen(itemEl) {
    if (itemEl !== el) return;
    emit('treeviewOpen', [el]);
  }
  function onClose(itemEl) {
    if (itemEl !== el) return;
    emit('treeviewClose', [el]);
  }
  function onLoadChildren(itemEl, done) {
    if (itemEl !== el) return;
    emit('treeviewLoadChildren', [el, done]);
  }

  onMount(() => {
    if (!el) return;
    t4ready(() => {
      app.t4.on('treeviewOpen', onOpen);
      app.t4.on('treeviewClose', onClose);
      app.t4.on('treeviewLoadChildren', onLoadChildren);
    });
  });

  onDestroy(() => {
    if (!el || !app.t4) return;
    app.t4.off('treeviewOpen', onOpen);
    app.t4.off('treeviewClose', onClose);
    app.t4.off('treeviewLoadChildren', onLoadChildren);
  });
</script>

<!-- svelte-ignore a11y-missing-attribute -->
<div bind:this={el} class={classes} {...restProps($$restProps)}>
  {#if treeviewRootTag === 'div'}
    <div on:click={onClick} class={itemRootClasses} {...itemRootAttrs}>
      <slot name="root-start" />
      {#if needToggle}
        <div class="treeview-toggle" />
      {/if}
      <div class="treeview-item-content">
        <slot name="content-start" />
        {#if icon}
          <UseIcon {icon} />
        {/if}
        <slot name="media" />
        <div class="treeview-item-label">
          <slot name="label-start" />
          {plainText(label)}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </div>
  {:else}
    <a on:click={onClick} class={itemRootClasses} {...itemRootAttrs}>
      <slot name="root-start" />
      {#if needToggle}
        <div class="treeview-toggle" />
      {/if}
      <div class="treeview-item-content">
        <slot name="content-start" />
        {#if icon}
          <UseIcon {icon} />
        {/if}
        <slot name="media" />
        <div class="treeview-item-label">
          <slot name="label-start" />
          {plainText(label)}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </a>
  {/if}
  {#if hasChildren}
    <div class="treeview-item-children">
      <slot name="children-start" />
      <slot />
      <slot name="children" />
    </div>
  {/if}
</div>
