// boonker/svelte/src/app.svelte
<script>
  import { App, Panel, View } from 'techno4-svelte';
  import routes from './routes';
  import store from './store';

  // Demo Theme
  let theme = 'auto';
  if (document.location.search.indexOf('theme=') >= 0) {
    theme = document.location.search.split('theme=')[1].split('&')[0];
  }

  const t4Params = {
    id: 'io.techno4.testapp',
    theme,
    routes,
    store,
    popup: {
      closeOnEscape: true,
    },
    sheet: {
      closeOnEscape: true,
    },
    popover: {
      closeOnEscape: true,
    },
    actions: {
      closeOnEscape: true,
    },
  };
</script>

<App {...t4Params}>
  <Panel left cover resizable>
    <View url="/panel-left/" links-view=".view-main" />
  </Panel>
  <Panel right reveal resizable>
    <View url="/panel-right/" />
  </Panel>
  <View url="/" main={true} class="safe-areas" masterDetailBreakpoint={768} />
</App>

// boonker/vue/src/app.vue
<template>
  <t4-app v-bind="t4Params">
    <t4-panel left cover resizable>
      <t4-view url="/panel-left/" links-view=".view-main"></t4-view>
    </t4-panel>
    <t4-panel right reveal resizable>
      <t4-view url="/panel-right/"></t4-view>
    </t4-panel>
    <t4-view url="/" :main="true" class="safe-areas" :master-detail-breakpoint="768"></t4-view>
  </t4-app>
</template>
<script>
import { t4App, t4Panel, t4View } from 'techno4-vue';
import routes from './routes';
import store from './store';

export default {
  components: {
    t4App,
    t4Panel,
    t4View,
  },
  data() {
    // Demo Theme
    let theme = 'auto';
    if (document.location.search.indexOf('theme=') >= 0) {
      theme = document.location.search.split('theme=')[1].split('&')[0];
    }

    return {
      t4Params: {
        id: 'io.techno4.testapp',
        theme,
        routes,
        store,
        popup: {
          closeOnEscape: true,
        },
        sheet: {
          closeOnEscape: true,
        },
        popover: {
          closeOnEscape: true,
        },
        actions: {
          closeOnEscape: true,
        },
      },
    };
  },
};
</script>
