// boonker/svelte/src/pages/home.svelte
<script>
  import {
    t4,
    theme,
    Page,
    Navbar,
    NavLeft,
    NavTitle,
    NavTitleLarge,
    NavRight,
    BlockTitle,
    List,
    ListItem,
    Link,
    Searchbar,
  } from 'techno4-svelte';
  import { onMount } from 'svelte';

  export let t4router;

  const onResize = () => {
    const $el = t4.$('.page-home');
    if (t4.width >= 768) {
      $el.find('.list:not(.searchbar-not-found)').addClass('menu-list');
    } else {
      $el.find('.list:not(.searchbar-not-found)').removeClass('menu-list');
    }
  };

  const onPageAfterIn = () => {
    if (!theme.aurora) return;
    if (t4.width >= 768) {
      t4router.navigate('/about/', { reloadDetail: true });
    }
  };

  onMount(() => {
    if (theme.aurora) {
      const $el = t4.$('.page-home');
      onResize();

      t4.on('resize', onResize);

      t4router.on('routeChange', (route) => {
        const url = route.url;
        if (!$el) return;
        const $linkEl = $el.find(`a[href="${url}"]`);
        if (!$linkEl.length) return;
        $el.find('.item-selected').removeClass('item-selected');
        $linkEl.addClass('item-selected');
      });
    }
  });
</script>

<Page class="page-home" {onPageAfterIn}>
  <Navbar large transparent sliding={false}>
    <NavLeft>
      <Link panelOpen="left" iconIos="t4:menu" iconAurora="t4:menu" iconMd="material:menu" />
    </NavLeft>
    <NavTitle sliding>techno4 Svelte</NavTitle>
    <NavRight>
      <Link
        searchbarEnable=".searchbar-components"
        iconIos="t4:search"
        iconAurora="t4:search"
        iconMd="material:search"
      />
    </NavRight>
    <NavTitleLarge>techno4 Svelte</NavTitleLarge>
    <Searchbar
      class="searchbar-components"
      searchContainer=".components-list"
      searchIn="a"
      expandable
      disableButton={!theme.aurora}
    />
  </Navbar>

  <List class="searchbar-hide-on-search">
    <ListItem title="About techno4" reloadDetail={theme.aurora} link="/about/">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
  </List>

  <BlockTitle medium class="searchbar-found">Components</BlockTitle>
  <List class="components-list searchbar-found">
    <ListItem reloadDetail={theme.aurora} link="/accordion/" title="Accordion">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/action-sheet/" title="Action Sheet">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/appbar/" title="Appbar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/area-chart/" title="Area Chart">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/autocomplete/" title="Autocomplete">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/badge/" title="Badge">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/breadcrumbs/" title="Breadcrumbs">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/buttons/" title="Buttons">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/calendar/" title="Calendar / Date Picker">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/cards/" title="Cards">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/cards-expandable/" title="Cards Expandable">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/checkbox/" title="Checkbox">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/chips/" title="Chips/Tags">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/color-picker/" title="Color Picker">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/contacts-list/" title="Contacts List">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/content-block/" title="Content Block">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/data-table/" title="Data Table">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/dialog/" title="Dialog">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/elevation/" title="Elevation">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/fab/" title="FAB">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/fab-morph/" title="FAB Morph">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/form-storage/" title="Form Storage">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/gauge/" title="Gauge">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/grid/" title="Grid / Layout Grid">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/icons/" title="Icons">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/infinite-scroll/" title="Infinite Scroll">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/inputs/" title="Inputs">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/lazy-load/" title="Lazy Load">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/list/" title="List View">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/list-index/" title="List Index">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/login-screen/" title="Login Screen">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/menu/" title="Menu">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/menu-list/" title="Menu List">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/messages/" title="Messages">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/navbar/" title="Navbar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/notifications/" title="Notifications">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/panel/" title="Panel / Side Panels">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/photo-browser/" title="Photo Browser">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/picker/" title="Picker">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/pie-chart/" title="Pie Chart">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/popover/" title="Popover">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/popup/" title="Popup">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/preloader/" title="Preloader">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/progressbar/" title="Progress Bar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/pull-to-refresh/" title="Pull To Refresh">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/radio/" title="Radio">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/range/" title="Range Slider">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/searchbar/" title="Searchbar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem
      reloadDetail={theme.aurora}
      link="/searchbar-expandable/"
      title="Searchbar Expandable"
    >
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/sheet-modal/" title="Sheet Modal">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/skeleton/" title="Skeleton (Ghost) Elements">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/smart-select/" title="Smart Select">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/sortable/" title="Sortable List">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/stepper/" title="Stepper">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/subnavbar/" title="Subnavbar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/swipeout/" title="Swipeout (Swipe To Delete)">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/swiper/" title="Swiper Slider">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/tabs/" title="Tabs">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/text-editor/" title="Text Editor">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/timeline/" title="Timeline">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/toast/" title="Toast">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/toggle/" title="Toggle">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/toolbar-tabbar/" title="Toolbar & Tabbar">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/tooltip/" title="Tooltip">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/treeview/" title="Treeview">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
    <ListItem reloadDetail={theme.aurora} link="/virtual-list/" title="Virtual List">
      <i class="icon icon-t4" slot="media" />
    </ListItem>
  </List>
  <List class="searchbar-not-found">
    <ListItem title="Nothing found" />
  </List>
  <BlockTitle medium class="searchbar-hide-on-search">Themes</BlockTitle>
  <List class="searchbar-hide-on-search">
    <ListItem title="iOS Theme" external link="./index.html?theme=ios" />
    <ListItem title="Material (MD) Theme" external link="./index.html?theme=md" />
    <ListItem title="Aurora Desktop Theme" external link="./index.html?theme=aurora" />
    <ListItem title="Color Themes" reloadDetail={theme.aurora} link="/color-themes/" />
  </List>
  <BlockTitle medium class="searchbar-hide-on-search">Page Loaders & Router</BlockTitle>
  <List class="searchbar-hide-on-search">
    <ListItem title="Page Transitions" reloadDetail={theme.aurora} link="/page-transitions/" />
    <ListItem title="Routable Modals" reloadDetail={theme.aurora} link="/routable-modals/" />
    <ListItem
      title="Default Route (404)"
      reloadDetail={theme.aurora}
      link="/load-something-that-doesnt-exist/"
    />
    {#if !theme.aurora}
      <ListItem title="Master-Detail (Split View)" link="/master-detail/" />
    {/if}
    <ListItem title="Store" reloadDetail={theme.aurora} link="/store/" />
  </List>
</Page>

// boonker/react/src/pages/home.jsx
import React, { useEffect } from 'react';
import {
  Page,
  Navbar,
  NavLeft,
  NavTitle,
  NavTitleLarge,
  NavRight,
  BlockTitle,
  List,
  ListItem,
  Link,
  Searchbar,
  Icon,
  t4,
  theme,
} from 'techno4-react';

export default ({ t4router }) => {
  const onResize = () => {
    const $el = t4.$('.page-home');
    if (t4.width >= 768) {
      $el.find('.list:not(.searchbar-not-found)').addClass('menu-list');
    } else {
      $el.find('.list:not(.searchbar-not-found)').removeClass('menu-list');
    }
  };

  const onPageAfterIn = () => {
    if (!theme.aurora) return;
    if (t4.width >= 768) {
      t4router.navigate('/about/', { reloadDetail: true });
    }
  };
  useEffect(() => {
    if (theme.aurora) {
      const $el = t4.$('.page-home');
      onResize();

      t4.on('resize', onResize);

      t4router.on('routeChange', (route) => {
        const url = route.url;
        if (!$el) return;
        const $linkEl = $el.find(`a[href="${url}"]`);
        if (!$linkEl.length) return;
        $el.find('.item-selected').removeClass('item-selected');
        $linkEl.addClass('item-selected');
      });
    }
  }, []);

  return (
    <Page className="page-home" onPageAfterIn={onPageAfterIn}>
      <Navbar large transparent sliding={false}>
        <NavLeft>
          <Link panelOpen="left" iconIos="t4:menu" iconAurora="t4:menu" iconMd="material:menu" />
        </NavLeft>
        <NavTitle sliding>techno4 React</NavTitle>
        <NavRight>
          <Link
            searchbarEnable=".searchbar-components"
            iconIos="t4:search"
            iconAurora="t4:search"
            iconMd="material:search"
          />
        </NavRight>
        <NavTitleLarge>techno4 React</NavTitleLarge>
        <Searchbar
          className="searchbar-components"
          searchContainer=".components-list"
          searchIn="a"
          expandable
          disableButton={!theme.aurora}
        />
      </Navbar>

      <List className="searchbar-hide-on-search">
        <ListItem title="About techno4" reloadDetail link="/about/">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
      </List>

      <BlockTitle medium className="searchbar-found">
        Components
      </BlockTitle>
      <List className="components-list searchbar-found">
        <ListItem reloadDetail link="/accordion/" title="Accordion">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/action-sheet/" title="Action Sheet">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/appbar/" title="Appbar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/area-chart/" title="Area Chart">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/autocomplete/" title="Autocomplete">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/badge/" title="Badge">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/breadcrumbs/" title="Breadcrumbs">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/buttons/" title="Buttons">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/calendar/" title="Calendar / Date Picker">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/cards/" title="Cards">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/cards-expandable/" title="Cards Expandable">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/checkbox/" title="Checkbox">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/chips/" title="Chips/Tags">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/color-picker/" title="Color Picker">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/contacts-list/" title="Contacts List">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/content-block/" title="Content Block">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/data-table/" title="Data Table">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/dialog/" title="Dialog">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/elevation/" title="Elevation">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/fab/" title="FAB">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/fab-morph/" title="FAB Morph">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/form-storage/" title="Form Storage">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/gauge/" title="Gauge">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/grid/" title="Grid / Layout Grid">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/icons/" title="Icons">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/infinite-scroll/" title="Infinite Scroll">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/inputs/" title="Inputs">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/lazy-load/" title="Lazy Load">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/list/" title="List View">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/list-index/" title="List Index">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/login-screen/" title="Login Screen">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/menu/" title="Menu">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/menu-list/" title="Menu List">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/messages/" title="Messages">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/navbar/" title="Navbar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/notifications/" title="Notifications">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/panel/" title="Panel / Side Panels">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/photo-browser/" title="Photo Browser">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/picker/" title="Picker">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/pie-chart/" title="Pie Chart">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/popover/" title="Popover">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/popup/" title="Popup">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/preloader/" title="Preloader">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/progressbar/" title="Progress Bar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/pull-to-refresh/" title="Pull To Refresh">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/radio/" title="Radio">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/range/" title="Range Slider">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/searchbar/" title="Searchbar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/searchbar-expandable/" title="Searchbar Expandable">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/sheet-modal/" title="Sheet Modal">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/skeleton/" title="Skeleton (Ghost) Elements">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/smart-select/" title="Smart Select">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/sortable/" title="Sortable List">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/stepper/" title="Stepper">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/subnavbar/" title="Subnavbar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/swipeout/" title="Swipeout (Swipe To Delete)">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/swiper/" title="Swiper Slider">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/tabs/" title="Tabs">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/text-editor/" title="Text Editor">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/timeline/" title="Timeline">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/toast/" title="Toast">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/toggle/" title="Toggle">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/toolbar-tabbar/" title="Toolbar & Tabbar">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/tooltip/" title="Tooltip">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/treeview/" title="Treeview">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
        <ListItem reloadDetail link="/virtual-list/" title="Virtual List">
          <Icon slot="media" icon="icon-t4" />
        </ListItem>
      </List>
      <List className="searchbar-not-found">
        <ListItem title="Nothing found" />
      </List>
      <BlockTitle medium className="searchbar-hide-on-search">
        Themes
      </BlockTitle>
      <List className="searchbar-hide-on-search">
        <ListItem title="iOS Theme" external link="./index.html?theme=ios" />
        <ListItem title="Material (MD) Theme" external link="./index.html?theme=md" />
        <ListItem title="Aurora Desktop Theme" external link="./index.html?theme=aurora" />
        <ListItem title="Color Themes" reloadDetail link="/color-themes/" />
      </List>
      <BlockTitle medium className="searchbar-hide-on-search">
        Page Loaders & Router
      </BlockTitle>
      <List className="searchbar-hide-on-search">
        <ListItem title="Page Transitions" reloadDetail link="/page-transitions/" />
        <ListItem title="Routable Modals" reloadDetail link="/routable-modals/" />
        <ListItem
          title="Default Route (404)"
          reloadDetail
          link="/load-something-that-doesnt-exist/"
        />
        {!theme.aurora && <ListItem title="Master-Detail (Split View)" link="/master-detail/" />}
        <ListItem title="Store" reloadDetail link="/store/" />
      </List>
    </Page>
  );
};
