// boonker/vue/src/pages/preloader.vue
<template>
  <t4-page>
    <t4-navbar title="Preloader" back-link="Back"></t4-navbar>
    <t4-block>
      <p>
        How about an activity indicator? techno4 has a nice one. The t4 Preloader is made with
        SVG and animated with CSS so it can be easily resized.
      </p>
    </t4-block>

    <t4-block-title>Default</t4-block-title>
    <t4-block strong class="row demo-preloaders align-items-stretch text-align-center">
      <t4-col>
        <t4-preloader />
      </t4-col>
      <t4-col style="background: #000">
        <t4-preloader color="white" />
      </t4-col>
      <t4-col>
        <t4-preloader :size="42" />
      </t4-col>
      <t4-col style="background: #000">
        <t4-preloader :size="42" color="white" />
      </t4-col>
    </t4-block>

    <t4-block-title>Color Preloaders</t4-block-title>
    <t4-block strong class="row text-align-center">
      <t4-col>
        <t4-preloader color="red" />
      </t4-col>
      <t4-col>
        <t4-preloader color="green" />
      </t4-col>
      <t4-col>
        <t4-preloader color="orange" />
      </t4-col>
      <t4-col>
        <t4-preloader color="blue" />
      </t4-col>
    </t4-block>

    <t4-block-title>Multi-color</t4-block-title>
    <t4-block strong class="text-align-center">
      <t4-preloader color="multi" />
    </t4-block>

    <t4-block-title>Preloader Modals</t4-block-title>
    <t4-block strong>
      <p>With <b>app.preloader.show()</b> you can show small overlay with preloader indicator.</p>
      <p>
        <a class="button button-fill" @click="openIndicator">Open Small Indicator</a>
      </p>
      <p>With <b>app.dialog.preloader()</b> you can show dialog modal with preloader indicator.</p>
      <p>
        <a class="button button-fill" @click="openDialog">Open Dialog Preloader</a>
      </p>
      <p>
        With <b>app.dialog.preloader('My text...')</b> you can show dialog preloader modal with
        custom title.
      </p>
      <p>
        <a class="button button-fill" @click="openCustomDialog">Open Dialog Preloader</a>
      </p>
    </t4-block>
  </t4-page>
</template>
<script>
import { t4Navbar, t4Page, t4BlockTitle, t4Block, t4Preloader, t4Col, t4 } from 'techno4-vue';

export default {
  components: {
    t4Navbar,
    t4Page,
    t4BlockTitle,
    t4Block,
    t4Preloader,
    t4Col,
  },
  methods: {
    openIndicator() {
      t4.preloader.show();
      setTimeout(() => {
        t4.preloader.hide();
      }, 2000);
    },
    openDialog() {
      t4.dialog.preloader();
      setTimeout(() => {
        t4.dialog.close();
      }, 2000);
    },
    openCustomDialog() {
      t4.dialog.preloader('My text...');
      setTimeout(() => {
        t4.dialog.close();
      }, 2000);
    },
  },
};
</script>

// boonker/react/src/pages/preloader.jsx
import React from 'react';
import { Navbar, Page, BlockTitle, Block, Preloader, Col, t4 } from 'techno4-react';

export default () => {
  const openIndicator = () => {
    t4.preloader.show();
    setTimeout(() => {
      t4.preloader.hide();
    }, 2000);
  };
  const openDialog = () => {
    t4.dialog.preloader();
    setTimeout(() => {
      t4.dialog.close();
    }, 2000);
  };
  const openCustomDialog = () => {
    t4.dialog.preloader('My text...');
    setTimeout(() => {
      t4.dialog.close();
    }, 2000);
  };
  return (
    <Page>
      <Navbar title="Preloader" backLink="Back"></Navbar>
      <Block>
        <p>
          How about an activity indicator? techno4 has a nice one. The t4 Preloader is made with
          SVG and animated with CSS so it can be easily resized.
        </p>
      </Block>

      <BlockTitle>Default</BlockTitle>
      <Block strong className="row demo-preloaders align-items-stretch text-align-center">
        <Col>
          <Preloader />
        </Col>
        <Col style={{ background: '#000' }}>
          <Preloader color="white" />
        </Col>
        <Col>
          <Preloader size={42} />
        </Col>
        <Col style={{ background: '#000' }}>
          <Preloader size={42} color="white" />
        </Col>
      </Block>

      <BlockTitle>Color Preloaders</BlockTitle>
      <Block strong className="row text-align-center">
        <Col>
          <Preloader color="red" />
        </Col>
        <Col>
          <Preloader color="green" />
        </Col>
        <Col>
          <Preloader color="orange" />
        </Col>
        <Col>
          <Preloader color="blue" />
        </Col>
      </Block>

      <BlockTitle>Multi-color</BlockTitle>
      <Block strong className="text-align-center">
        <Preloader color="multi" />
      </Block>

      <BlockTitle>Preloader Modals</BlockTitle>
      <Block strong>
        <p>
          With <b>app.preloader.show()</b> you can show small overlay with preloader indicator.
        </p>
        <p>
          <a className="button button-fill" onClick={openIndicator}>
            Open Small Indicator
          </a>
        </p>
        <p>
          With <b>app.dialog.preloader()</b> you can show dialog modal with preloader indicator.
        </p>
        <p>
          <a className="button button-fill" onClick={openDialog}>
            Open Dialog Preloader
          </a>
        </p>
        <p>
          With <b>app.dialog.preloader('My text...')</b> you can show dialog preloader modal with
          custom title.
        </p>
        <p>
          <a className="button button-fill" onClick={openCustomDialog}>
            Open Dialog Preloader
          </a>
        </p>
      </Block>
    </Page>
  );
};
