// boonker/vue/src/pages/swiper.vue
<template>
  <t4-page>
    <t4-navbar title="Swiper Slider" back-link="Back"></t4-navbar>
    <div class="block">
      <p>
        techno4 comes with powerful and most modern touch slider ever -
        <a href="https://swiperjs.com" class="external" target="_blank">Swiper Slider</a>
        with super flexible configuration and lot, lot of features. Just check the following demos:
      </p>
    </div>
    <div class="list links-list">
      <ul>
        <li>
          <a href="swiper-horizontal/">Swiper Horizontal</a>
        </li>
        <li>
          <a href="swiper-vertical/">Swiper Vertical</a>
        </li>
        <li>
          <a href="swiper-space-between/">Space Between Slides</a>
        </li>
        <li>
          <a href="swiper-multiple/">Multiple Per Page</a>
        </li>
        <li>
          <a href="swiper-nested/">Nested Swipers</a>
        </li>
        <li>
          <a href="swiper-loop/">Infinite Loop Mode</a>
        </li>
        <li>
          <a href="swiper-3d-cube/">3D Cube Effect</a>
        </li>
        <li>
          <a href="swiper-3d-coverflow/">3D Coverflow Effect</a>
        </li>
        <li>
          <a href="swiper-3d-flip/">3D Flip Effect</a>
        </li>
        <li>
          <a href="swiper-fade/">Fade Effect</a>
        </li>
        <li>
          <a href="swiper-scrollbar/">With Scrollbar</a>
        </li>
        <li>
          <a href="swiper-gallery/">Thumbs Gallery</a>
        </li>
        <li>
          <a href="swiper-custom-controls/">Custom Controls</a>
        </li>
        <li>
          <a href="swiper-parallax/">Parallax</a>
        </li>
        <li>
          <a href="swiper-lazy/">Lazy Loading</a>
        </li>
        <li>
          <a href="swiper-pagination-progress/">Progress Pagination</a>
        </li>
        <li>
          <a href="swiper-pagination-fraction/">Fraction Pagination</a>
        </li>
        <li>
          <a href="swiper-zoom/">Zoom</a>
        </li>
      </ul>
    </div>
  </t4-page>
</template>
<script>
import { t4Navbar, t4Page } from 'techno4-vue';

export default {
  components: {
    t4Navbar,
    t4Page,
  },
};
</script>

// boonker/react/src/pages/swiper.jsx
import React from 'react';
import { Navbar, Page, Block, List, ListItem } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Swiper Slider" backLink="Back"></Navbar>
    <Block>
      <p>
        techno4 comes with powerful and most modern touch slider ever -<span> </span>
        <a href="https://swiperjs.com" className="external" target="_blank">
          Swiper Slider
        </a>
        <span> </span>
        with super flexible configuration and lot, lot of features. Just check the following demos:
      </p>
    </Block>
    <List>
      <ListItem link="swiper-horizontal/" title="Swiper Horizontal" />
      <ListItem link="swiper-vertical/" title="Swiper Vertical" />
      <ListItem link="swiper-space-between/" title="Space Between Slides" />
      <ListItem link="swiper-multiple/" title="Multiple Per Page" />
      <ListItem link="swiper-nested/" title="Nested Swipers" />
      <ListItem link="swiper-loop/" title="Infinite Loop Mode" />
      <ListItem link="swiper-3d-cube/" title="3D Cube Effect" />
      <ListItem link="swiper-3d-coverflow/" title="3D Coverflow Effect" />
      <ListItem link="swiper-3d-flip/" title="3D Flip Effect" />
      <ListItem link="swiper-fade/" title="Fade Effect" />
      <ListItem link="swiper-scrollbar/" title="With Scrollbar" />
      <ListItem link="swiper-gallery/" title="Thumbs Gallery" />
      <ListItem link="swiper-custom-controls/" title="Custom Controls" />
      <ListItem link="swiper-parallax/" title="Parallax" />
      <ListItem link="swiper-lazy/" title="Lazy Loading" />
      <ListItem link="swiper-pagination-progress/" title="Progress Pagination" />
      <ListItem link="swiper-pagination-fraction/" title="Fraction Pagination" />
      <ListItem link="swiper-zoom/" title="Zoom" />
    </List>
  </Page>
);
