// src/vue/components/actions-button.vue
<template>
  <div ref="elRef" :class="classes" @click="onClick">
    <div v-if="hasMedia" class="actions-button-media">
      <slot name="media" />
    </div>
    <div class="actions-button-text">
      <slot />
    </div>
  </div>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4 } from '../shared/t4.js';

export default {
  name: 't4-actions-button',
  props: {
    bold: Boolean,
    close: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { slots, emit }) {
    const elRef = ref(null);

    const onClick = (e) => {
      if (elRef.value && props.close && t4) {
        t4.actions.close(t4.$(elRef.value).parents('.actions-modal'));
      }
      emit('click', e);
    };

    const hasMedia = computed(() => slots && !!slots.media);

    const classes = computed(() =>
      classNames(
        {
          'actions-button': true,
          'actions-button-bold': props.bold,
        },
        colorClasses(props),
      ),
    );
    return { classes, elRef, hasMedia, onClick };
  },
};
</script>

// src/react/components/actions-button.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, getSlots, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4 } from '../shared/t4.js';

/* dts-props
  id: string | number;
  className: string;
  style: React.CSSProperties;
  bold: boolean;
  close: boolean;
  onClick? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const ComponentName = forwardRef((props, ref) => {
  const { className, id, style, bold, close = true } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(
    className,
    {
      'actions-button': true,
      'actions-button-bold': bold,
    },
    colorClasses(props),
  );

  let mediaEl;

  const slots = getSlots(props);

  if (slots.media && slots.media.length) {
    mediaEl = <div className="actions-button-media">{slots.media}</div>;
  }

  const onClick = (e) => {
    if (elRef.current && close && t4) {
      t4.actions.close(t4.$(elRef.current).parents('.actions-modal'));
    }
    emit(props, 'click', e);
  };

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs} onClick={onClick}>
      {mediaEl}
      <div className="actions-button-text">{slots.default}</div>
    </div>
  );
});

ComponentName.displayName = 't4-actions-button';

export default ComponentName;
