// src/vue/components/badge.vue
<template>
  <span ref="elRef" :class="classes">
    <slot />
  </span>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

export default {
  name: 't4-badge',
  props: {
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    useTooltip(elRef, props);

    const classes = computed(() => classNames('badge', colorClasses(props)));

    return {
      elRef,
      classes,
    };
  },
};
</script>

// src/react/components/badge.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

/* dts-imports
import { Tooltip } from 'techno4/types';
*/

/* dts-instance
t4Tooltip: Tooltip.Tooltip
*/

/* dts-props
  id: string | number;
  className: string;
  style: React.CSSProperties;
  tooltip: string;
  tooltipTrigger: string;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const Badge = forwardRef((props, ref) => {
  const { className, id, style, children } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useTooltip(elRef, props);

  const classes = classNames(className, 'badge', colorClasses(props));

  return (
    <span id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {children}
    </span>
  );
});

Badge.displayName = 't4-badge';

export default Badge;
