// src/vue/components/card-content.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-card-content',
  props: {
    padding: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'card-content',
        {
          'card-content-padding': props.padding,
        },
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>

// src/react/components/card-content.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id: string | number;
  className: string;
  style: React.CSSProperties;
  padding: boolean;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const CardContent = forwardRef((props, ref) => {
  const { className, id, style, children, padding = true } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(
    className,
    'card-content',
    {
      'card-content-padding': padding,
    },
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {children}
    </div>
  );
});

CardContent.displayName = 't4-card-content';

export default CardContent;
