// src/vue/components/fab-buttons.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-fab-buttons',
  props: {
    position: {
      type: String,
      default: 'top',
    },
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames('fab-buttons', `fab-buttons-${props.position}`, colorClasses(props)),
    );
    return { classes };
  },
};
</script>

// src/react/components/fab-buttons.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  position?: string;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const FabButtons = forwardRef((props, ref) => {
  const { className, id, style, children, position } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(
    className,
    'fab-buttons',
    `fab-buttons-${position}`,
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {children}
    </div>
  );
});

FabButtons.displayName = 't4-fab-buttons';

export default FabButtons;
