// src/vue/components/link.vue
<template>
  <a ref="elRef" :class="classes" v-bind="attrs">
    <t4-use-icon v-if="icon" :icon="icon" />
    <span v-if="text" :class="isTabbarLabel ? 'tabbar-label' : ''">
      {{ text }}
      <t4-badge v-if="badge" :color="badgeColor">{{ badge }}</t4-badge>
    </span>
    <slot />
  </a>
</template>
<script>
import { computed, ref, inject } from 'vue';
import { classNames, isStringProp } from '../shared/utils.js';
import {
  colorClasses,
  routerAttrs,
  routerClasses,
  actionsAttrs,
  actionsClasses,
  colorProps,
  actionsProps,
  routerProps,
  iconProps,
} from '../shared/mixins.js';

import { useIcon } from '../shared/use-icon.js';
import { useRouteProps } from '../shared/use-route-props.js';
import { useTooltip } from '../shared/use-tooltip.js';
import { useSmartSelect } from '../shared/use-smart-select.js';
import t4Badge from './badge.js';
import t4UseIcon from './use-icon.js';

export default {
  name: 't4-link',
  components: {
    t4Badge,
    t4UseIcon,
  },
  props: {
    noLinkClass: Boolean,
    text: String,
    tabLink: [Boolean, String],
    tabLinkActive: Boolean,
    tabbarLabel: Boolean,
    iconOnly: Boolean,
    badge: [String, Number],
    badgeColor: [String],
    href: {
      type: [String, Boolean],
      default: '#',
    },
    target: String,
    tooltip: String,
    tooltipTrigger: String,
    smartSelect: Boolean,
    smartSelectParams: Object,
    ...iconProps,
    ...colorProps,
    ...actionsProps,
    ...routerProps,
  },
  setup(props, { slots }) {
    const elRef = ref(null);
    let t4SmartSelect = null;

    useTooltip(elRef, props);

    useRouteProps(elRef, props);

    useSmartSelect(
      props,
      (instance) => {
        t4SmartSelect = instance;
      },
      () => {
        return elRef.value;
      },
    );

    const TabbarContext = inject('TabbarContext', { value: {} });

    const isTabbarLabel = computed(() => props.tabbarLabel || TabbarContext.value.tabbarHasLabels);

    const attrs = computed(() => {
      const { href, tabLink, target } = props;
      let hrefComputed = href;
      if (href === true) hrefComputed = '#';
      if (href === false) hrefComputed = undefined; // no href attribute
      return {
        href: hrefComputed,
        target,
        'data-tab': (isStringProp(tabLink) && tabLink) || undefined,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    const classes = computed(() => {
      const { iconOnly, text, noLinkClass, tabLink, tabLinkActive, smartSelect } = props;
      let iconOnlyComputed;
      const hasChildren = slots && slots.default;
      if (iconOnly || (!text && !hasChildren)) {
        iconOnlyComputed = true;
      } else {
        iconOnlyComputed = false;
      }
      return classNames(
        {
          link: !(noLinkClass || isTabbarLabel.value),
          'icon-only': iconOnlyComputed,
          'tab-link': tabLink || tabLink === '',
          'tab-link-active': tabLinkActive,
          'smart-select': smartSelect,
        },
        colorClasses(props),
        routerClasses(props),
        actionsClasses(props),
      );
    });

    const icon = computed(() => useIcon(props));

    return {
      elRef,
      icon,
      isTabbarLabel,
      attrs,
      classes,
      t4SmartSelect,
    };
  },
};
</script>

// src/react/components/link.jsx
import React, { forwardRef, useRef, useImperativeHandle, useContext } from 'react';
import { classNames, getExtraAttrs, isStringProp, emit } from '../shared/utils.js';
import {
  colorClasses,
  routerAttrs,
  routerClasses,
  actionsAttrs,
  actionsClasses,
} from '../shared/mixins.js';
import { useIcon } from '../shared/use-icon.js';
import { useRouteProps } from '../shared/use-route-props.js';
import { useTooltip } from '../shared/use-tooltip.js';
import { TabbarContext } from '../shared/tabbar-context.js';

import Badge from './badge.js';
import { useSmartSelect } from '../shared/use-smart-select.js';

/* dts-imports
import { SmartSelect } from 'techno4/types';
*/

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  noLinkClass? : boolean
  text? : string
  tabLink? : boolean | string
  tabLinkActive? : boolean
  tabbarLabel? : boolean
  iconOnly? : boolean
  badge? : string | number
  badgeColor? : string
  iconBadge? : string | number
  href? : string | boolean
  target? : string
  tooltip? : string
  tooltipTrigger? : string
  smartSelect? : boolean
  smartSelectParams? : SmartSelect.Parameters;
  COLOR_PROPS
  ICON_PROPS
  ACTIONS_PROPS
  ROUTER_PROPS
  onClick? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null; t4SmartSelect: () => SmartSelect.SmartSelect}>;
  children?: React.ReactNode;
*/

const Link = forwardRef((props, ref) => {
  const t4SmartSelect = useRef(null);
  const {
    className,
    id,
    style,
    children,
    noLinkClass,
    text,
    tabLink,
    tabLinkActive,
    tabbarLabel,
    iconOnly,
    badge,
    badgeColor,
    href = '#',
    target,
    // Smart Select
    smartSelect,
    smartSelectParams,
  } = props;

  const tabbarContext = useContext(TabbarContext);

  const isTabbarLabel = tabbarLabel || tabbarContext.tabbarHasLabels;

  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    t4SmartSelect: () => t4SmartSelect.current,
  }));

  useTooltip(elRef, props);

  useRouteProps(elRef, props);

  useSmartSelect(smartSelect, smartSelectParams, t4SmartSelect, () => {
    return elRef.current;
  });

  let textEl;
  let badgeEl;

  if (text) {
    if (badge) badgeEl = <Badge color={badgeColor}>{badge}</Badge>;
    textEl = (
      <span className={isTabbarLabel ? 'tabbar-label' : ''}>
        {text}
        {badgeEl}
      </span>
    );
  }
  const iconEl = useIcon(props);
  let iconOnlyComputed;
  if (iconOnly || (!text && children && children.length === 0) || (!text && !children)) {
    iconOnlyComputed = true;
  } else {
    iconOnlyComputed = false;
  }

  const classes = classNames(
    className,
    {
      link: !(noLinkClass || isTabbarLabel),
      'icon-only': iconOnlyComputed,
      'tab-link': tabLink || tabLink === '',
      'tab-link-active': tabLinkActive,
      'smart-select': smartSelect,
    },
    colorClasses(props),
    routerClasses(props),
    actionsClasses(props),
  );

  let hrefComputed = href;
  if (href === true) hrefComputed = '#';
  if (href === false) hrefComputed = undefined; // no href attribute
  const attrs = {
    href: hrefComputed,
    target,
    'data-tab': (isStringProp(tabLink) && tabLink) || undefined,
    ...routerAttrs(props),
    ...actionsAttrs(props),
  };

  return (
    <a
      ref={elRef}
      id={id}
      style={style}
      className={classes}
      {...attrs}
      {...extraAttrs}
      onClick={onClick}
    >
      {iconEl}
      {textEl}
      {children}
    </a>
  );
});

Link.displayName = 't4-link';

export default Link;
