// src/vue/components/list.vue
<script>
import { computed, ref, onMounted, onBeforeUnmount, h, provide, toRaw } from 'vue';
import { classNames, extend } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4, t4ready } from '../shared/t4.js';
import { useTab } from '../shared/use-tab.js';

export default {
  name: 't4-list',
  props: {
    inset: Boolean,
    xsmallInset: Boolean,
    smallInset: Boolean,
    mediumInset: Boolean,
    largeInset: Boolean,
    xlargeInset: Boolean,
    mediaList: Boolean,
    sortable: Boolean,
    sortableTapHold: Boolean,
    sortableEnabled: Boolean,
    sortableMoveElements: {
      type: Boolean,
      default: undefined,
    },
    sortableOpposite: Boolean,
    accordionList: Boolean,
    accordionOpposite: Boolean,
    contactsList: Boolean,
    simpleList: Boolean,
    linksList: Boolean,
    menuList: Boolean,

    noHairlines: Boolean,
    noHairlinesBetween: Boolean,
    noHairlinesMd: Boolean,
    noHairlinesBetweenMd: Boolean,
    noHairlinesIos: Boolean,
    noHairlinesBetweenIos: Boolean,
    noHairlinesAurora: Boolean,
    noHairlinesBetweenAurora: Boolean,

    // Links Chevron (Arrow) Icon
    noChevron: Boolean,
    chevronCenter: Boolean,

    // Tab
    tab: Boolean,
    tabActive: Boolean,

    // Form
    form: Boolean,
    formStoreData: Boolean,
    inlineLabels: Boolean,

    // Virtual List
    virtualList: Boolean,
    virtualListParams: Object,
    ...colorProps,
  },
  emits: [
    'submit',
    'sortable:enable',
    'sortable:disable',
    'sortable:sort',
    'sortable:move',
    'virtual:itembeforeinsert',
    'virtual:beforeclear',
    'virtual:itemsbeforeinsert',
    'virtual:itemsafterinsert',
    'tab:hide',
    'tab:show',
  ],
  setup(props, { emit, slots }) {
    let t4VirtualList = null;
    const elRef = ref(null);

    const onSubmit = (event) => {
      emit('submit', event);
    };
    const onSortableEnable = (el) => {
      if (elRef.value !== el) return;
      emit('sortable:enable');
    };
    const onSortableDisable = (el) => {
      if (elRef.value !== el) return;
      emit('sortable:disable');
    };
    const onSortableSort = (el, sortData, listEl) => {
      if (elRef.value !== listEl) return;
      emit('sortable:sort', sortData);
    };
    const onSortableMove = (el, listEl) => {
      if (elRef.value !== listEl) return;
      emit('sortable:move', el, listEl);
    };

    useTab(elRef, emit);

    onMounted(() => {
      t4ready(() => {
        t4.on('sortableEnable', onSortableEnable);
        t4.on('sortableDisable', onSortableDisable);
        t4.on('sortableSort', onSortableSort);
        t4.on('sortableMove', onSortableMove);

        if (!props.virtualList) return;
        const vlParams = props.virtualListParams || {};
        if (!vlParams.renderItem && !vlParams.renderExternal) return;
        if (vlParams.items) vlParams.items = toRaw(vlParams.items);

        t4VirtualList = t4.virtualList.create(
          extend(
            {
              el: elRef.value,
              on: {
                itemBeforeInsert(itemEl, item) {
                  const vl = this;
                  emit('virtual:itembeforeinsert', vl, itemEl, item);
                },
                beforeClear(fragment) {
                  const vl = this;
                  emit('virtual:beforeclear', vl, fragment);
                },
                itemsBeforeInsert(fragment) {
                  const vl = this;
                  emit('virtual:itemsbeforeinsert', vl, fragment);
                },
                itemsAfterInsert(fragment) {
                  const vl = this;
                  emit('virtual:itemsafterinsert', vl, fragment);
                },
              },
            },
            vlParams,
          ),
        );
      });
    });

    onBeforeUnmount(() => {
      if (!t4) return;
      t4.off('sortableEnable', onSortableEnable);
      t4.off('sortableDisable', onSortableDisable);
      t4.off('sortableSort', onSortableSort);
      t4.off('sortableMove', onSortableMove);

      if (!(props.virtualList && t4VirtualList)) return;
      if (t4VirtualList.destroy) t4VirtualList.destroy();
      t4VirtualList = null;
    });

    const classes = computed(() =>
      classNames(
        'list',
        {
          inset: props.inset,
          'xsmall-inset': props.xsmallInset,
          'small-inset': props.smallInset,
          'medium-inset': props.mediumInset,
          'large-inset': props.largeInset,
          'xlarge-inset': props.xlargeInset,
          'media-list': props.mediaList,
          'simple-list': props.simpleList,
          'links-list': props.linksList,
          'menu-list': props.menuList,
          sortable: props.sortable,
          'sortable-tap-hold': props.sortableTapHold,
          'sortable-enabled': props.sortableEnabled,
          'sortable-opposite': props.sortableOpposite,
          'accordion-list': props.accordionList,
          'accordion-opposite': props.accordionOpposite,
          'contacts-list': props.contactsList,
          'virtual-list': props.virtualList,
          tab: props.tab,
          'tab-active': props.tabActive,
          'no-hairlines': props.noHairlines,
          'no-hairlines-md': props.noHairlinesMd,
          'no-hairlines-ios': props.noHairlinesIos,
          'no-hairlines-aurora': props.noHairlinesAurora,
          'no-hairlines-between': props.noHairlinesBetween,
          'no-hairlines-between-md': props.noHairlinesBetweenMd,
          'no-hairlines-between-ios': props.noHairlinesBetweenIos,
          'no-hairlines-between-aurora': props.noHairlinesBetweenAurora,
          'form-store-data': props.formStoreData,
          'inline-labels': props.inlineLabels,
          'no-chevron': props.noChevron,
          'chevron-center': props.chevronCenter,
        },
        colorClasses(props),
      ),
    );

    const ListTag = computed(() => (props.form ? 'form' : 'div'));

    const ListContext = computed(() => ({
      listIsMedia: props.mediaList,
      listIsSimple: props.simpleList,
      listIsSortable: props.sortable,
      listIsSortableOpposite: props.sortableOpposite,
    }));

    provide('ListContext', ListContext);

    return () => {
      const { list: slotsList, default: slotsDefault } = slots;
      const rootChildrenBeforeList = [];
      const rootChildrenAfterList = [];
      const ulChildren = slotsList || [];
      let wasUlChild = false;
      if (slotsDefault) {
        slotsDefault().forEach((vnode) => {
          if (typeof vnode === 'undefined') return;
          const tag = vnode.type && vnode.type.name ? vnode.type.name : vnode.type;
          if (tag && typeof tag === 'symbol') {
            wasUlChild = true;
            ulChildren.push(vnode);
          } else if (
            !tag ||
            (tag &&
              !(
                tag === 'li' ||
                tag.indexOf('t4-list-item') >= 0 ||
                tag.indexOf('t4-list-button') >= 0 ||
                tag.indexOf('t4-list-input') >= 0
              ))
          ) {
            if (wasUlChild) rootChildrenAfterList.push(vnode);
            else rootChildrenBeforeList.push(vnode);
          } else if (tag) {
            wasUlChild = true;
            ulChildren.push(vnode);
          }
        });
      }

      return h(
        ListTag.value,
        {
          ref: elRef,
          class: classes.value,
          'data-sortable-move-elements':
            typeof props.sortableMoveElements !== 'undefined'
              ? props.sortableMoveElements.toString()
              : undefined,
          onSubmit,
        },
        [
          slots['before-list'] && slots['before-list'](),
          rootChildrenBeforeList,
          ulChildren.length > 0 && h('ul', ulChildren),
          slots['after-list'] && slots['after-list'](),
          rootChildrenAfterList,
        ],
      );
    };
  },
};
</script>

// src/react/components/list.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import {
  classNames,
  getExtraAttrs,
  getSlots,
  flattenArray,
  emit,
  extend,
} from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4, t4ready } from '../shared/t4.js';
import { ListContext } from '../shared/list-context.js';
import { useTab } from '../shared/use-tab.js';

/* dts-imports
import { VirtualList } from 'techno4/types';
*/
/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  inset? : boolean
  xsmallInset? : boolean
  smallInset? : boolean
  mediumInset? : boolean
  largeInset? : boolean
  xlargeInset? : boolean
  mediaList? : boolean
  sortable? : boolean
  sortableTapHold? : boolean
  sortableEnabled? : boolean
  sortableMoveElements? : boolean
  sortableOpposite? : boolean
  accordionList? : boolean
  accordionOpposite? : boolean
  contactsList? : boolean
  simpleList? : boolean
  linksList? : boolean
  menuList? : boolean
  noHairlines? : boolean
  noHairlinesBetween? : boolean
  noHairlinesMd? : boolean
  noHairlinesBetweenMd? : boolean
  noHairlinesIos? : boolean
  noHairlinesBetweenIos? : boolean
  noHairlinesAurora? : boolean
  noHairlinesBetweenAurora? : boolean
  noChevron? : boolean
  chevronCenter? : boolean
  tab? : boolean
  tabActive? : boolean
  form? : boolean
  formStoreData? : boolean
  inlineLabels? : boolean
  virtualList? : boolean
  virtualListParams? : Object
  COLOR_PROPS
  onVirtualItemBeforeInsert? : (vl?: VirtualList.VirtualList, itemEl?: HTMLElement, item?: any) => void
  onVirtualBeforeClear? : (vl?: VirtualList.VirtualList, fragment?: any) => void
  onVirtualItemsBeforeInsert? : (vl?: VirtualList.VirtualList, fragment?: any) => void
  onVirtualItemsAfterInsert? : (vl?: VirtualList.VirtualList, fragment?: any) => void
  onSubmit? : (event?: any) => void
  onSortableEnable? : (...args: any[]) => void
  onSortableDisable? : (...args: any[]) => void
  onSortableSort? : (sortData?: any) => void
  onSortableMove? : (itemEl?: any) => void
  onTabShow? : (el?: HTMLElement) => void
  onTabHide? : (el?: HTMLElement) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null; t4VirtualList: () => VirtualList.VirtualList}>;
  children?: React.ReactNode;
*/

const List = forwardRef((props, ref) => {
  const t4VirtualList = useRef(null);
  const {
    className,
    id,
    style,
    inset,
    xsmallInset,
    smallInset,
    mediumInset,
    largeInset,
    xlargeInset,
    mediaList,
    sortable,
    sortableTapHold,
    sortableEnabled,
    sortableMoveElements,
    sortableOpposite,
    accordionList,
    accordionOpposite,
    contactsList,
    simpleList,
    linksList,
    menuList,
    noHairlines,
    noHairlinesBetween,
    noHairlinesMd,
    noHairlinesBetweenMd,
    noHairlinesIos,
    noHairlinesBetweenIos,
    noHairlinesAurora,
    noHairlinesBetweenAurora,
    noChevron,
    chevronCenter,
    tab,
    tabActive,
    form,
    formStoreData,
    inlineLabels,
    virtualList,
    virtualListParams,
  } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onSubmit = (event) => {
    emit(props, 'submit', event);
  };
  const onSortableEnable = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'sortableEnable');
  };
  const onSortableDisable = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'sortableDisable');
  };
  const onSortableSort = (el, sortData, listEl) => {
    if (elRef.current !== listEl) return;
    emit(props, 'sortableSort', sortData);
  };

  const onSortableMove = (el, listEl) => {
    if (elRef.current !== listEl) return;
    emit(props, 'sortableMove', el, listEl);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    t4VirtualList: () => t4VirtualList.current,
  }));

  useTab(elRef, props);

  const attachEvents = () => {
    t4ready(() => {
      t4.on('sortableEnable', onSortableEnable);
      t4.on('sortableDisable', onSortableDisable);
      t4.on('sortableSort', onSortableSort);
      t4.on('sortableMove', onSortableMove);
    });
  };

  const detachEvents = () => {
    if (!t4) return;
    t4.off('sortableEnable', onSortableEnable);
    t4.off('sortableDisable', onSortableDisable);
    t4.off('sortableSort', onSortableSort);
    t4.off('sortableMove', onSortableMove);
  };

  const onMount = () => {
    t4ready(() => {
      if (!virtualList) return;
      const vlParams = virtualListParams || {};
      if (!vlParams.renderItem && !vlParams.renderExternal) return;

      t4VirtualList.current = t4.virtualList.create(
        extend(
          {
            el: elRef.current,
            on: {
              itemBeforeInsert(itemEl, item) {
                const vl = this;
                emit(props, 'virtualItemBeforeInsert', vl, itemEl, item);
              },
              beforeClear(fragment) {
                const vl = this;
                emit(props, 'virtualBeforeClear', vl, fragment);
              },
              itemsBeforeInsert(fragment) {
                const vl = this;
                emit(props, 'virtualItemsBeforeInsert', vl, fragment);
              },
              itemsAfterInsert(fragment) {
                const vl = this;
                emit(props, 'virtualItemsAfterInsert', vl, fragment);
              },
            },
          },
          vlParams,
        ),
      );
    });
  };

  const onDestroy = () => {
    if (!t4) return;

    if (!(virtualList && t4VirtualList.current)) return;
    if (t4VirtualList.current.destroy) t4VirtualList.current.destroy();
    t4VirtualList.current = null;
  };

  useIsomorphicLayoutEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    return detachEvents;
  });

  const slots = getSlots(props);

  const { list: slotsList, default: slotsDefault } = slots;
  const rootChildrenBeforeList = [];
  const rootChildrenAfterList = [];
  const ulChildren = slotsList || [];
  const flattenSlots = flattenArray(slotsDefault);

  let wasUlChild = false;
  flattenSlots.forEach((child) => {
    if (typeof child === 'undefined') return;
    let tag = child.type && (child.type.displayName || child.type.name);
    if (!tag && typeof child.type === 'string') {
      tag = child.type;
    }

    if (
      !tag ||
      (tag &&
        !(
          tag === 'li' ||
          tag.indexOf('t4-list-item') >= 0 ||
          tag.indexOf('t4-list-button') >= 0 ||
          tag.indexOf('t4-list-input') >= 0
        ))
    ) {
      if (wasUlChild) rootChildrenAfterList.push(child);
      else rootChildrenBeforeList.push(child);
    } else if (tag) {
      wasUlChild = true;
      ulChildren.push(child);
    }
  });
  const ListTag = form ? 'form' : 'div';

  const classes = classNames(
    className,
    'list',
    {
      inset,
      'xsmall-inset': xsmallInset,
      'small-inset': smallInset,
      'medium-inset': mediumInset,
      'large-inset': largeInset,
      'xlarge-inset': xlargeInset,
      'media-list': mediaList,
      'simple-list': simpleList,
      'links-list': linksList,
      'menu-list': menuList,
      sortable,
      'sortable-tap-hold': sortableTapHold,
      'sortable-enabled': sortableEnabled,
      'sortable-opposite': sortableOpposite,
      'accordion-list': accordionList,
      'accordion-opposite': accordionOpposite,
      'contacts-list': contactsList,
      'virtual-list': virtualList,
      tab,
      'tab-active': tabActive,
      'no-hairlines': noHairlines,
      'no-hairlines-md': noHairlinesMd,
      'no-hairlines-ios': noHairlinesIos,
      'no-hairlines-aurora': noHairlinesAurora,
      'no-hairlines-between': noHairlinesBetween,
      'no-hairlines-between-md': noHairlinesBetweenMd,
      'no-hairlines-between-ios': noHairlinesBetweenIos,
      'no-hairlines-between-aurora': noHairlinesBetweenAurora,
      'form-store-data': formStoreData,
      'inline-labels': inlineLabels,
      'no-chevron': noChevron,
      'chevron-center': chevronCenter,
    },
    colorClasses(props),
  );

  return (
    <ListTag
      id={id}
      ref={elRef}
      style={style}
      className={classes}
      {...extraAttrs}
      data-sortable-move-elements={
        typeof sortableMoveElements !== 'undefined' ? sortableMoveElements.toString() : undefined
      }
      onSubmit={onSubmit}
    >
      <ListContext.Provider
        value={{
          listIsMedia: mediaList,
          listIsSimple: simpleList,
          listIsSortable: sortable,
          listIsSortableOpposite: sortableOpposite,
        }}
      >
        {slots['before-list']}
        {rootChildrenBeforeList}

        {ulChildren.length > 0 && <ul>{ulChildren}</ul>}

        {slots['after-list']}
        {rootChildrenAfterList}
      </ListContext.Provider>
    </ListTag>
  );
});

List.displayName = 't4-list';

export default List;
