// src/vue/components/list-item.vue
<script>
import { computed, ref, h, onMounted, onBeforeUnmount, watch, inject } from 'vue';
import { classNames, isStringProp } from '../shared/utils.js';
import {
  colorClasses,
  colorProps,
  actionsProps,
  actionsAttrs,
  actionsClasses,
  routerProps,
  routerAttrs,
  routerClasses,
} from '../shared/mixins.js';

import { useRouteProps } from '../shared/use-route-props.js';
import { useSmartSelect } from '../shared/use-smart-select.js';
import { useTooltip } from '../shared/use-tooltip.js';
import { t4ready, t4 } from '../shared/t4.js';

import t4Badge from './badge.js';

const ListItemContent = ({
  props,
  slots,
  inputElRef,
  onChange,
  onClick,
  isMediaComputed,
  isSortableComputed,
  isSortableOppositeComputed,
  itemContentClasses,
} = {}) => {
  const {
    radio,
    checkbox,
    value,
    name,
    readonly,
    disabled,
    checked,
    required,
    media,
    header,
    footer,
    title,
    subtitle,
    text,
    after,
    badge,
    badgeColor,
    swipeout,
    sortable,
    accordionItem,
  } = props;
  let titleEl;
  let afterWrapEl;
  let afterEl;
  let badgeEl;
  let innerEl;
  let titleRowEl;
  let subtitleEl;
  let textEl;
  let mediaEl;
  let inputEl;
  let inputIconEl;
  let headerEl;
  let footerEl;

  // Input
  if (radio || checkbox) {
    inputEl = h('input', {
      ref: inputElRef,
      value,
      name,
      checked,
      readonly,
      disabled,
      required,
      type: radio ? 'radio' : 'checkbox',
      onChange,
    });
    inputIconEl = h('i', { class: `icon icon-${radio ? 'radio' : 'checkbox'}` });
  }
  // Media
  if (media || slots.media) {
    let mediaImgEl;
    if (media) {
      mediaImgEl = h('img', { src: media });
    }
    mediaEl = h('div', { class: 'item-media' }, [mediaImgEl, slots.media && slots.media()]);
  }
  // Inner Elements
  if (header || slots.header) {
    headerEl = h('div', { class: 'item-header' }, [header, slots.header && slots.header()]);
  }
  if (footer || slots.footer) {
    footerEl = h('div', { class: 'item-footer' }, [footer, slots.footer && slots.footer()]);
  }
  if (
    title ||
    slots.title ||
    (!isMediaComputed.value && headerEl) ||
    (!isMediaComputed.value && footerEl)
  ) {
    titleEl = h('div', { class: 'item-title' }, [
      !isMediaComputed.value && headerEl,
      title,
      slots.title && slots.title(),
      !isMediaComputed.value && footerEl,
    ]);
  }
  if (subtitle || slots.subtitle) {
    subtitleEl = h('div', { class: 'item-subtitle' }, [
      subtitle,
      slots.subtitle && slots.subtitle(),
    ]);
  }
  if (text || slots.text) {
    textEl = h('div', { class: 'item-text' }, [text, slots.text && slots.text()]);
  }
  if (after || badge || slots.after) {
    if (after) {
      afterEl = h('span', [after]);
    }
    if (badge) {
      badgeEl = h(t4Badge, { color: badgeColor }, () => badge);
    }
    afterWrapEl = h('div', { class: 'item-after' }, [
      slots['after-start'] && slots['after-start'](),
      afterEl,
      badgeEl,
      slots.after && slots.after(),
      slots['after-end'] && slots['after-end'](),
    ]);
  }
  if (isMediaComputed.value) {
    titleRowEl = h('div', { class: 'item-title-row' }, [
      slots['before-title'] && slots['before-title'](),
      titleEl,
      slots['after-title'] && slots['after-title'](),
      afterWrapEl,
    ]);

    innerEl = h('div', { class: 'item-inner' }, [
      slots['inner-start'] && slots['inner-start'],
      headerEl,
      titleRowEl,
      subtitleEl,
      textEl,
      swipeout || accordionItem ? null : slots.default && slots.default(),
      slots.inner && slots.inner(),
      footerEl,
      slots['inner-end'] && slots['inner-end'],
    ]);
  } else {
    innerEl = h('div', { class: 'item-inner' }, [
      slots['inner-start'] && slots['inner-start'](),
      slots['before-title'] && slots['before-title'](),
      titleEl,
      slots['after-title'] && slots['after-title'](),
      afterWrapEl,
      swipeout || accordionItem ? null : slots.default && slots.default(),
      slots.inner && slots.inner(),
      slots['inner-end'] && slots['inner-end'](),
    ]);
  }

  const ItemContentTag = checkbox || radio ? 'label' : 'div';

  return h(ItemContentTag, { class: itemContentClasses.value, onClick }, [
    isSortableComputed.value &&
      sortable !== false &&
      isSortableOppositeComputed.value &&
      h('div', { class: 'sortable-handler' }),
    slots['content-start'] && slots['content-start'](),
    inputEl,
    inputIconEl,
    mediaEl,
    innerEl,
    slots.content && slots.content(),
    slots['content-end'] && slots['content-end'](),
  ]);
};

export default {
  name: 't4-list-item',
  props: {
    title: [String, Number],
    text: [String, Number],
    media: String,
    subtitle: [String, Number],
    header: [String, Number],
    footer: [String, Number],

    // Tooltip
    tooltip: String,
    tooltipTrigger: String,

    // Link Props
    link: [Boolean, String],
    target: String,

    tabLink: [Boolean, String],
    tabLinkActive: Boolean,
    selected: Boolean,

    after: [String, Number],
    badge: [String, Number],
    badgeColor: String,

    mediaItem: Boolean,
    mediaList: Boolean,
    divider: Boolean,
    groupTitle: Boolean,
    swipeout: Boolean,
    swipeoutOpened: Boolean,
    sortable: {
      type: Boolean,
      default: undefined,
    },
    sortableOpposite: {
      type: Boolean,
      default: undefined,
    },
    accordionItem: Boolean,
    accordionItemOpened: Boolean,

    // Smart Select
    smartSelect: Boolean,
    smartSelectParams: Object,

    // Links Chevron (Arrow) Icon
    noChevron: Boolean,
    chevronCenter: Boolean,

    // Inputs
    checkbox: Boolean,
    radio: Boolean,
    radioIcon: String,
    checked: Boolean,
    indeterminate: Boolean,
    name: String,
    value: {
      type: [String, Number, Array],
      default: undefined,
    },
    readonly: Boolean,
    required: Boolean,
    disabled: Boolean,
    virtualListIndex: Number,
    ...colorProps,
    ...actionsProps,
    ...routerProps,
  },
  emits: [
    'click',
    'swipeout',
    'swipeout:overswipeenter',
    'swipeout:overswipeexit',
    'swipeout:deleted',
    'swipeout:delete',
    'swipeout:close',
    'swipeout:closed',
    'swipeout:open',
    'swipeout:opened',
    'accordion:beforeclose',
    'accordion:close',
    'accordion:closed',
    'accordion:beforeopen',
    'accordion:open',
    'accordion:opened',
    'change',
    'update:checked',
  ],
  setup(props, { slots, emit }) {
    const ListContext = inject('ListContext', {
      value: {
        listIsMedia: false,
        listIsSortable: false,
        listIsSortableOpposite: false,
        listIsSimple: false,
      },
    });

    const listIsMedia = computed(() => ListContext.value.listIsMedia || false);
    const listIsSortable = computed(() => ListContext.value.listIsSortable || false);
    const listIsSortableOpposite = computed(
      () => ListContext.value.listIsSortableOpposite || false,
    );
    const listIsSimple = computed(() => ListContext.value.listIsSimple || false);

    const elRef = ref(null);
    const linkElRef = ref(null);
    const inputElRef = ref(null);

    const onClick = (event) => {
      if (event.target.tagName.toLowerCase() !== 'input') {
        emit('click', event);
      }
    };
    const onSwipeoutOverswipeEnter = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:overswipeenter');
    };
    const onSwipeoutOverswipeExit = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:overswipeexit');
    };
    const onSwipeoutDeleted = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:deleted');
    };
    const onSwipeoutDelete = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:delete');
    };
    const onSwipeoutClose = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:close');
    };
    const onSwipeoutClosed = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:closed');
    };
    const onSwipeoutOpen = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:open');
    };
    const onSwipeoutOpened = (el) => {
      if (elRef.value !== el) return;
      emit('swipeout:opened');
    };
    const onSwipeout = (el, progress) => {
      if (elRef.value !== el) return;
      emit('swipeout', progress);
    };
    const onAccBeforeClose = (el, prevent) => {
      if (elRef.value !== el) return;
      emit('accordion:beforeclose', prevent);
    };
    const onAccClose = (el) => {
      if (elRef.value !== el) return;
      emit('accordion:close');
    };
    const onAccClosed = (el) => {
      if (elRef.value !== el) return;
      emit('accordion:closed');
    };
    const onAccBeforeOpen = (el, prevent) => {
      if (elRef.value !== el) return;
      emit('accordion:beforeopen', prevent);
    };
    const onAccOpen = (el) => {
      if (elRef.value !== el) return;
      emit('accordion:open');
    };
    const onAccOpened = (el) => {
      if (elRef.value !== el) return;
      emit('accordion:opened');
    };
    const onChange = (event) => {
      emit('change', event);
      emit('update:checked', event.target.checked);
    };

    useTooltip(elRef, props);

    useRouteProps(linkElRef, props);

    useSmartSelect(
      props,
      () => {},
      () => elRef.value.querySelector('a.smart-select'),
    );

    watch(
      () => props.swipeoutOpened,
      (newValue) => {
        if (!props.swipeout || !elRef.value || !t4) return;
        if (newValue) {
          t4.swipeout.open(elRef.value);
        } else {
          t4.swipeout.close(elRef.value);
        }
      },
    );

    onMounted(() => {
      t4ready(() => {
        if (props.swipeout) {
          t4.on('swipeoutOpen', onSwipeoutOpen);
          t4.on('swipeoutOpened', onSwipeoutOpened);
          t4.on('swipeoutClose', onSwipeoutClose);
          t4.on('swipeoutClosed', onSwipeoutClosed);
          t4.on('swipeoutDelete', onSwipeoutDelete);
          t4.on('swipeoutDeleted', onSwipeoutDeleted);
          t4.on('swipeoutOverswipeEnter', onSwipeoutOverswipeEnter);
          t4.on('swipeoutOverswipeExit', onSwipeoutOverswipeExit);
          t4.on('swipeout', onSwipeout);
        }
        if (props.accordionItem) {
          t4.on('accordionBeforeOpen', onAccBeforeOpen);
          t4.on('accordionOpen', onAccOpen);
          t4.on('accordionOpened', onAccOpened);
          t4.on('accordionBeforeClose', onAccBeforeClose);
          t4.on('accordionClose', onAccClose);
          t4.on('accordionClosed', onAccClosed);
        }
        if (props.swipeout && props.swipeoutOpened) {
          t4.swipeout.open(elRef.value);
        }
      });
      if (props.checkbox && inputElRef.value) {
        inputElRef.value.indeterminate = !!props.indeterminate;
      }
    });

    onBeforeUnmount(() => {
      if (!t4) return;
      t4.off('swipeoutOpen', onSwipeoutOpen);
      t4.off('swipeoutOpened', onSwipeoutOpened);
      t4.off('swipeoutClose', onSwipeoutClose);
      t4.off('swipeoutClosed', onSwipeoutClosed);
      t4.off('swipeoutDelete', onSwipeoutDelete);
      t4.off('swipeoutDeleted', onSwipeoutDeleted);
      t4.off('swipeoutOverswipeEnter', onSwipeoutOverswipeEnter);
      t4.off('swipeoutOverswipeExit', onSwipeoutOverswipeExit);
      t4.off('swipeout', onSwipeout);
      t4.off('accordionBeforeOpen', onAccBeforeOpen);
      t4.off('accordionOpen', onAccOpen);
      t4.off('accordionOpened', onAccOpened);
      t4.off('accordionBeforeClose', onAccBeforeClose);
      t4.off('accordionClose', onAccClose);
      t4.off('accordionClosed', onAccClosed);
    });

    watch(
      () => props.indeterminate,
      (newValue) => {
        if (inputElRef.value) {
          inputElRef.value.indeterminate = !!newValue;
        }
      },
    );

    const isMediaComputed = computed(() => props.mediaItem || props.mediaList || listIsMedia.value);
    const isSortableComputed = computed(() =>
      props.sortable === true || props.sortable === false ? props.sortable : listIsSortable.value,
    );
    const isSortableOppositeComputed = computed(
      () => isSortableComputed.value && (props.sortableOpposite || listIsSortableOpposite.value),
    );

    const linkAttrs = computed(() => ({
      href: props.link === true ? '' : props.link || props.href,
      target: props.target,
      'data-tab': (isStringProp(props.tabLink) && props.tabLink) || undefined,
      ...routerAttrs(props),
      ...actionsAttrs(props),
    }));

    const linkClasses = computed(() =>
      classNames(
        {
          'item-link': true,
          'smart-select': props.smartSelect,
          'tab-link': props.tabLink || props.tabLink === '',
          'tab-link-active': props.tabLinkActive,
          'item-selected': props.selected,
        },
        routerClasses(props),
        actionsClasses(props),
      ),
    );

    const itemContentClasses = computed(() =>
      classNames(
        'item-content',
        {
          'item-checkbox': props.checkbox,
          'item-radio': props.radio,
          'item-radio-icon-start': props.radio && props.radioIcon === 'start',
          'item-radio-icon-end': props.radio && props.radioIcon === 'end',
        },
        colorClasses(props),
      ),
    );

    const liClasses = computed(() =>
      classNames(
        {
          'item-divider': props.divider,
          'list-group-title': props.groupTitle,
          'media-item': isMediaComputed.value,
          swipeout: props.swipeout,
          'accordion-item': props.accordionItem,
          'accordion-item-opened': props.accordionItemOpened,
          disabled: props.disabled && !(props.radio || props.checkbox),
          'no-chevron': props.noChevron,
          'chevron-center': props.chevronCenter,
          'disallow-sorting': props.sortable === false,
        },
        colorClasses(props),
      ),
    );

    return () => {
      let linkEl;
      let itemContentEl;
      if (!listIsSimple.value) {
        // Item Content
        itemContentEl = ListItemContent({
          props,
          slots,
          inputElRef,
          onChange,
          onClick:
            props.link || props.href || props.accordionItem || props.smartSelect
              ? undefined
              : onClick,
          isMediaComputed,
          isSortableComputed,
          isSortableOppositeComputed,
          itemContentClasses,
        });

        // Link
        if (props.link || props.href || props.accordionItem || props.smartSelect) {
          linkEl = h(
            'a',
            { ref: linkElRef, class: linkClasses.value, ...linkAttrs.value, onClick },
            [itemContentEl],
          );
        }
      }

      if (props.divider || props.groupTitle) {
        return h(
          'li',
          {
            ref: elRef,
            class: liClasses.value,
            'data-virtual-list-index': props.virtualListIndex,
            onClick,
          },
          [props.title, slots.default && slots.default()],
        );
      }
      if (listIsSimple.value) {
        return h(
          'li',
          {
            ref: elRef,
            class: liClasses.value,
            onClick,
            'data-virtual-list-index': props.virtualListIndex,
          },
          [props.title, slots.default && slots.default()],
        );
      }

      const linkItemEl =
        props.link || props.href || props.smartSelect || props.accordionItem
          ? linkEl
          : itemContentEl;
      return h(
        'li',
        {
          ref: elRef,
          class: liClasses.value,
          'data-virtual-list-index': props.virtualListIndex,
        },
        [
          slots['root-start'] && slots['root-start'](),
          props.swipeout ? h('div', { class: 'swipeout-content' }, [linkItemEl]) : linkItemEl,
          isSortableComputed.value &&
            props.sortable !== false &&
            !isSortableOppositeComputed.value &&
            h('div', { class: 'sortable-handler' }),
          (props.swipeout || props.accordionItem) && slots.default(),
          slots.root && slots.root(),
          slots['root-end'] && slots['root-end'](),
        ],
      );
    };
  },
};
</script>

// src/react/components/list-item.jsx
import React, { forwardRef, useRef, useImperativeHandle, useContext } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';

import { classNames, getExtraAttrs, getSlots, emit, isStringProp } from '../shared/utils.js';
import {
  colorClasses,
  actionsAttrs,
  actionsClasses,
  routerAttrs,
  routerClasses,
} from '../shared/mixins.js';
import { useRouteProps } from '../shared/use-route-props.js';
import { useSmartSelect } from '../shared/use-smart-select.js';
import { useTooltip } from '../shared/use-tooltip.js';
import { watchProp } from '../shared/watch-prop.js';
import { t4ready, t4 } from '../shared/t4.js';

import ListItemContent from './list-item-content.js';
import { ListContext } from '../shared/list-context.js';

/* dts-imports
import { SmartSelect } from 'techno4/types';
*/

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  title? : string | number
  text? : string | number
  media? : string
  subtitle? : string | number
  header? : string | number
  footer? : string | number
  tooltip? : string
  tooltipTrigger? : string
  link? : boolean | string
  target? : string
  tabLink? : boolean | string
  tabLinkActive? : boolean
  selected?: boolean
  after? : string | number
  badge? : string | number
  badgeColor? : string
  mediaItem? : boolean
  mediaList? : boolean
  divider? : boolean
  groupTitle? : boolean
  swipeout? : boolean
  swipeoutOpened? : boolean
  sortable? : boolean
  sortableOpposite? : boolean
  accordionItem? : boolean
  accordionItemOpened? : boolean
  smartSelect? : boolean
  smartSelectParams? : SmartSelect.Parameters
  noChevron? : boolean
  chevronCenter? : boolean
  checkbox? : boolean
  radio? : boolean
  radioIcon? : string
  checked? : boolean
  defaultChecked? : boolean
  indeterminate? : boolean
  name? : string
  value? : string | number | Array<any>
  readonly? : boolean
  required? : boolean
  disabled? : boolean
  virtualListIndex? : number
  COLOR_PROPS
  ROUTER_PROPS
  ACTIONS_PROPS
  onClick? : (event?: any) => void
  onSwipeoutOverswipeEnter? : (...args: any[]) => void
  onSwipeoutOverswipeExit? : (...args: any[]) => void
  onSwipeoutDeleted? : (...args: any[]) => void
  onSwipeoutDelete? : (...args: any[]) => void
  onSwipeoutClose? : (...args: any[]) => void
  onSwipeoutClosed? : (...args: any[]) => void
  onSwipeoutOpen? : (...args: any[]) => void
  onSwipeoutOpened? : (...args: any[]) => void
  onSwipeout? : (progress?: any) => void
  onAccordionBeforeClose? : (prevent?: any) => void
  onAccordionClose? : (...args: any[]) => void
  onAccordionClosed? : (...args: any[]) => void
  onAccordionBeforeOpen? : (prevent?: any) => void
  onAccordionOpen? : (...args: any[]) => void
  onAccordionOpened? : (...args: any[]) => void
  onChange? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null; t4SmartSelect: () => SmartSelect.SmartSelect}>;
  children?: React.ReactNode;
*/

/*
const ListItemContent = ({
  props,
  slots,
  inputElRef,
  onChange,
  onClick,
  isMediaComputed,
  isSortableComputed,
  isSortableOppositeComputed,
} = {}) => {
  const {
    radio,
    checkbox,
    value,
    name,
    readonly,
    disabled,
    checked,
    defaultChecked,
    required,
    media,
    header,
    footer,
    title,
    subtitle,
    text,
    after,
    badge,
    badgeColor,
    radioIcon,
    swipeout,
    sortable,
    accordionItem,
  } = props;

};
*/
const ListItem = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    children,
    title,
    link,
    target,
    tabLink,
    tabLinkActive,
    selected,
    mediaItem,
    mediaList,
    divider,
    groupTitle,
    swipeout,
    swipeoutOpened,
    sortable,
    sortableOpposite,
    accordionItem,
    accordionItemOpened,
    smartSelect,
    smartSelectParams,
    noChevron,
    chevronCenter,
    checkbox,
    radio,
    disabled,
    virtualListIndex,
    href,
  } = props;

  const listContext = useContext(ListContext);

  const {
    listIsMedia = false,
    listIsSortable = false,
    listIsSortableOpposite = false,
    listIsSimple = false,
  } = listContext || {};

  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  const linkElRef = useRef(null);
  const t4SmartSelect = useRef(null);

  const onClick = (event) => {
    if (event.target.tagName.toLowerCase() !== 'input') {
      emit(props, 'click', event);
    }
  };
  const onSwipeoutOverswipeEnter = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutOverswipeEnter');
  };
  const onSwipeoutOverswipeExit = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutOverswipeExit');
  };
  const onSwipeoutDeleted = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutDeleted');
  };
  const onSwipeoutDelete = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutDelete');
  };
  const onSwipeoutClose = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutClose');
  };
  const onSwipeoutClosed = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutClosed');
  };
  const onSwipeoutOpen = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutOpen');
  };
  const onSwipeoutOpened = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeoutOpened');
  };
  const onSwipeout = (el, progress) => {
    if (elRef.current !== el) return;
    emit(props, 'swipeout', progress);
  };
  const onAccBeforeClose = (el, prevent) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionBeforeClose', prevent);
  };
  const onAccClose = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionClose');
  };
  const onAccClosed = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionClosed');
  };
  const onAccBeforeOpen = (el, prevent) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionBeforeOpen', prevent);
  };
  const onAccOpen = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionOpen');
  };
  const onAccOpened = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'accordionOpened');
  };
  const onChange = (event) => {
    emit(props, 'change', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    t4SmartSelect: () => t4SmartSelect.current,
  }));

  useTooltip(elRef, props);

  useRouteProps(linkElRef, props);

  watchProp(swipeoutOpened, (newValue) => {
    if (!swipeout || !elRef.current || !t4) return;
    if (newValue) {
      t4.swipeout.open(elRef.current);
    } else {
      t4.swipeout.close(elRef.current);
    }
  });

  const attachEvents = () => {
    t4ready(() => {
      if (swipeout) {
        t4.on('swipeoutOpen', onSwipeoutOpen);
        t4.on('swipeoutOpened', onSwipeoutOpened);
        t4.on('swipeoutClose', onSwipeoutClose);
        t4.on('swipeoutClosed', onSwipeoutClosed);
        t4.on('swipeoutDelete', onSwipeoutDelete);
        t4.on('swipeoutDeleted', onSwipeoutDeleted);
        t4.on('swipeoutOverswipeEnter', onSwipeoutOverswipeEnter);
        t4.on('swipeoutOverswipeExit', onSwipeoutOverswipeExit);
        t4.on('swipeout', onSwipeout);
      }
      if (accordionItem) {
        t4.on('accordionBeforeOpen', onAccBeforeOpen);
        t4.on('accordionOpen', onAccOpen);
        t4.on('accordionOpened', onAccOpened);
        t4.on('accordionBeforeClose', onAccBeforeClose);
        t4.on('accordionClose', onAccClose);
        t4.on('accordionClosed', onAccClosed);
      }
    });
  };

  const detachEvents = () => {
    if (!t4) return;
    t4.off('swipeoutOpen', onSwipeoutOpen);
    t4.off('swipeoutOpened', onSwipeoutOpened);
    t4.off('swipeoutClose', onSwipeoutClose);
    t4.off('swipeoutClosed', onSwipeoutClosed);
    t4.off('swipeoutDelete', onSwipeoutDelete);
    t4.off('swipeoutDeleted', onSwipeoutDeleted);
    t4.off('swipeoutOverswipeEnter', onSwipeoutOverswipeEnter);
    t4.off('swipeoutOverswipeExit', onSwipeoutOverswipeExit);
    t4.off('swipeout', onSwipeout);
    t4.off('accordionBeforeOpen', onAccBeforeOpen);
    t4.off('accordionOpen', onAccOpen);
    t4.off('accordionOpened', onAccOpened);
    t4.off('accordionBeforeClose', onAccBeforeClose);
    t4.off('accordionClose', onAccClose);
    t4.off('accordionClosed', onAccClosed);
  };

  useSmartSelect(smartSelect, smartSelectParams, t4SmartSelect, () =>
    elRef.current.querySelector('a.smart-select'),
  );

  useIsomorphicLayoutEffect(() => {
    t4ready(() => {
      if (swipeout && swipeoutOpened) {
        t4.swipeout.open(elRef.current);
      }
    });
  }, []);

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    return detachEvents;
  });

  const slots = getSlots(props);

  let linkEl;
  let itemContentEl;

  const isMediaComputed = mediaItem || mediaList || listIsMedia;
  const isSortableComputed = sortable === true || sortable === false ? sortable : listIsSortable;
  const isSortableOppositeComputed =
    isSortableComputed && (sortableOpposite || listIsSortableOpposite);

  if (!listIsSimple) {
    // Item Content
    itemContentEl = (
      <ListItemContent
        {...props}
        slots={slots}
        onChange={onChange}
        onClick={link || href || accordionItem || smartSelect ? undefined : onClick}
        isMediaComputed={isMediaComputed}
        isSortableComputed={isSortableComputed}
        isSortableOppositeComputed={isSortableOppositeComputed}
      />
    );

    // Link
    if (link || href || accordionItem || smartSelect) {
      const linkAttrs = {
        href: link === true ? '' : link || href,
        target,
        'data-tab': (isStringProp(tabLink) && tabLink) || undefined,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
      const linkClasses = classNames(
        {
          'item-link': true,
          'smart-select': smartSelect,
          'tab-link': tabLink || tabLink === '',
          'tab-link-active': tabLinkActive,
          'item-selected': selected,
        },
        routerClasses(props),
        actionsClasses(props),
      );
      linkEl = (
        <a ref={linkElRef} className={linkClasses} {...linkAttrs} onClick={onClick}>
          {itemContentEl}
        </a>
      );
    }
  }

  const liClasses = classNames(
    className,
    {
      'item-divider': divider,
      'list-group-title': groupTitle,
      'media-item': isMediaComputed,
      swipeout,
      'accordion-item': accordionItem,
      'accordion-item-opened': accordionItemOpened,
      disabled: disabled && !(radio || checkbox),
      'no-chevron': noChevron,
      'chevron-center': chevronCenter,
      'disallow-sorting': sortable === false,
    },
    colorClasses(props),
  );

  if (divider || groupTitle) {
    return (
      <li
        ref={elRef}
        id={id}
        style={style}
        className={liClasses}
        data-virtual-list-index={virtualListIndex}
        onClick={onClick}
      >
        <span>
          {title}
          {children}
        </span>
      </li>
    );
  }
  if (listIsSimple) {
    return (
      <li
        ref={elRef}
        id={id}
        style={style}
        className={liClasses}
        data-virtual-list-index={virtualListIndex}
        onClick={onClick}
      >
        {title}
        {children}
      </li>
    );
  }

  const linkItemEl = link || href || smartSelect || accordionItem ? linkEl : itemContentEl;

  return (
    <li
      ref={elRef}
      id={id}
      style={style}
      className={liClasses}
      data-virtual-list-index={virtualListIndex}
      {...extraAttrs}
    >
      {slots['root-start']}
      {swipeout ? <div className="swipeout-content">{linkItemEl}</div> : linkItemEl}
      {isSortableComputed && sortable !== false && !isSortableOppositeComputed && (
        <div className="sortable-handler" />
      )}
      {(swipeout || accordionItem) && slots.default}
      {slots.root}
      {slots['root-end']}
    </li>
  );
});

ListItem.displayName = 't4-list-item';

export default ListItem;
