// src/vue/components/menu-dropdown.vue
<template>
  <div :class="classes">
    <div class="menu-dropdown-content" :style="{ height: contentHeight }">
      <slot />
    </div>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-menu-dropdown',
  props: {
    contentHeight: String,
    position: String,
    left: Boolean,
    center: Boolean,
    right: Boolean,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => {
      let positionComputed = props.position || 'left';
      if (props.left) positionComputed = 'left';
      if (props.center) positionComputed = 'center';
      if (props.right) positionComputed = 'right';
      return classNames('menu-dropdown', `menu-dropdown-${positionComputed}`, colorClasses(props));
    });

    return { classes };
  },
};
</script>

// src/react/components/menu-dropdown.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  contentHeight? : string
  position? : string
  left? : boolean
  center? : boolean
  right? : boolean
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const MenuDropdown = forwardRef((props, ref) => {
  const { className, id, style, children, contentHeight, position, left, center, right } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  let positionComputed = position || 'left';
  if (left) positionComputed = 'left';
  if (center) positionComputed = 'center';
  if (right) positionComputed = 'right';

  const classes = classNames(
    'menu-dropdown',
    `menu-dropdown-${positionComputed}`,
    colorClasses(props),
    className,
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      <div className="menu-dropdown-content" style={{ height: contentHeight }}>
        {children}
      </div>
    </div>
  );
});

MenuDropdown.displayName = 't4-menu-dropdown';

export default MenuDropdown;
