// src/vue/components/menu-dropdown-item.vue
<template>
  <div ref="elRef" :class="classes" v-bind="attrs" @click="onClick">
    {{ text }}
    <slot />
  </div>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import {
  colorClasses,
  colorProps,
  routerProps,
  routerAttrs,
  routerClasses,
  actionsProps,
  actionsAttrs,
  actionsClasses,
} from '../shared/mixins.js';
import { useRouteProps } from '../shared/use-route-props.js';

export default {
  name: 't4-menu-dropdown-item',
  props: {
    text: String,
    link: Boolean,
    href: String,
    target: String,
    divider: Boolean,
    ...colorProps,
    ...routerProps,
    ...actionsProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const elRef = ref(null);

    const onClick = (e) => {
      emit('click', e);
    };

    useRouteProps(elRef, props);

    const isLink = computed(() => props.link || props.href || props.href === '');

    const tag = computed(() => (isLink.value ? 'a' : 'div'));

    const classes = computed(() => {
      return classNames(
        {
          'menu-dropdown-link': isLink.value && !props.divider,
          'menu-dropdown-item': !isLink.value && !props.divider,
          'menu-dropdown-divider': props.divider,
        },
        colorClasses(props),
        routerClasses(props),
        actionsClasses(props),
        {
          'menu-close': typeof props.menuClose === 'undefined',
        },
      );
    });

    const attrs = computed(() => {
      let hrefComputed = props.href;
      if (typeof hrefComputed === 'undefined' && props.link) hrefComputed = '#';
      return {
        href: hrefComputed,
        target: props.target,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    return {
      classes,
      attrs,
      tag,
      onClick,
      elRef,
    };
  },
};
</script>

// src/react/components/menu-dropdown-item.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import {
  colorClasses,
  routerAttrs,
  routerClasses,
  actionsAttrs,
  actionsClasses,
} from '../shared/mixins.js';
import { useRouteProps } from '../shared/use-route-props.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  text? : string;
  link? : boolean;
  href? : string;
  target? : string;
  divider? : boolean;
  COLOR_PROPS
  ROUTER_PROPS
  ACTIONS_PROPS
  onClick? : (event?: any) => void;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const MenuDropdownItem = forwardRef((props, ref) => {
  const { className, id, style, children, link, href, target, text, divider, menuClose } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useRouteProps(elRef, props);

  const isLink = link || href || href === '';
  const Tag = isLink ? 'a' : 'div';

  const classes = classNames(
    {
      'menu-dropdown-link': isLink && !divider,
      'menu-dropdown-item': !isLink && !divider,
      'menu-dropdown-divider': divider,
    },
    className,
    colorClasses(props),
    routerClasses(props),
    actionsClasses(props),
    {
      'menu-close': typeof menuClose === 'undefined',
    },
  );

  let hrefComputed = href;
  if (typeof hrefComputed === 'undefined' && link) hrefComputed = '#';
  const attrs = {
    href: hrefComputed,
    target,
    ...routerAttrs(props),
    ...actionsAttrs(props),
  };

  return (
    <Tag
      className={classes}
      id={id}
      style={style}
      ref={elRef}
      {...attrs}
      {...extraAttrs}
      onClick={onClick}
    >
      {text}
      {children}
    </Tag>
  );
});

MenuDropdownItem.displayName = 't4-menu-dropdown-item';

export default MenuDropdownItem;
