// src/vue/components/messagebar-attachment.vue
<template>
  <div :class="classes" @click="onClick">
    <img v-if="image" :src="image" />
    <span v-if="deletable" class="messagebar-attachment-delete" @click="onDeleteClick" />
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-messagebar-attachment',
  props: {
    image: String,
    deletable: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  emits: ['attachment:click', 'attachment:delete'],
  setup(props, { emit }) {
    const onClick = (event) => {
      emit('attachment:click', event);
    };
    const onDeleteClick = (event) => {
      emit('attachment:delete', event);
    };
    const classes = computed(() => classNames('messagebar-attachment', colorClasses(props)));
    return {
      classes,
      onClick,
      onDeleteClick,
    };
  },
};
</script>

// src/react/components/messagebar-attachment.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  image? : string
  deletable? : boolean
  COLOR_PROPS
  onAttachmentClick? : (event?: any) => void
  onAttachmentDelete? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const MessagebarAttachment = forwardRef((props, ref) => {
  const { className, id, style, children, image, deletable = true } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'attachmentClick', event);
  };
  const onDeleteClick = (event) => {
    emit(props, 'attachmentDelete', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(className, 'messagebar-attachment', colorClasses(props));

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs} onClick={onClick}>
      {image && <img src={image} />}
      {deletable && <span className="messagebar-attachment-delete" onClick={onDeleteClick} />}
      {children}
    </div>
  );
});

MessagebarAttachment.displayName = 't4-messagebar-attachment';

export default MessagebarAttachment;
