// src/vue/components/radio.vue
<template>
  <label :class="classes">
    <input
      ref="inputElRef"
      type="radio"
      :name="name"
      :value="value"
      :disabled="disabled"
      :readonly="readonly"
      :checked="checked"
      @change="onChange"
    />
    <i class="icon-radio" />
    <slot />
  </label>
</template>
<script>
import { ref, computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 't4-radio',
  props: {
    checked: Boolean,
    name: [Number, String],
    value: {
      type: [Number, String, Boolean],
      default: undefined,
    },
    disabled: Boolean,
    readonly: Boolean,
    ...colorProps,
  },
  emits: ['update:checked', 'change'],
  setup(props, { emit }) {
    const inputElRef = ref(null);

    const onChange = (event) => {
      emit('update:checked', event.target.checked);
      emit('change', event);
    };

    const classes = computed(() =>
      classNames(
        {
          radio: true,
          disabled: props.disabled,
        },
        colorClasses(props),
      ),
    );

    return { inputElRef, classes, onChange };
  },
};
</script>

// src/react/components/radio.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  checked? : boolean
  name? : number | string
  value? : number | string | boolean
  disabled? : boolean
  readonly? : boolean
  defaultChecked? : boolean
  COLOR_PROPS
  onChange? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const Radio = forwardRef((props, ref) => {
  const { className, id, style, children, value, disabled, readonly, checked, defaultChecked } =
    props;

  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onChange = (event) => {
    emit(props, 'change', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const inputEl = (
    <input
      type="radio"
      name={name}
      value={value}
      disabled={disabled}
      readOnly={readonly}
      checked={checked}
      defaultChecked={defaultChecked}
      onChange={onChange}
    />
  );

  const iconEl = <i className="icon-radio" />;

  const classes = classNames(
    className,
    'radio',
    {
      disabled,
    },
    colorClasses(props),
  );

  return (
    <label id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {inputEl}
      {iconEl}
      {children}
    </label>
  );
});

Radio.displayName = 't4-radio';

export default Radio;
