// src/vue/components/toggle.vue
<template>
  <label ref="elRef" :class="classes">
    <input
      type="checkbox"
      :name="name"
      :disabled="disabled"
      :readonly="readonly"
      :checked="checked"
      :value="value"
      @change="onChange"
    />
    <span class="toggle-icon" />
  </label>
</template>
<script>
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';
import { useTooltip } from '../shared/use-tooltip.js';

export default {
  name: 't4-toggle',
  props: {
    init: {
      type: Boolean,
      default: true,
    },
    checked: Boolean,
    disabled: Boolean,
    readonly: Boolean,
    name: String,
    value: [String, Number, Array],
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
  },
  emits: ['change', 'toggle:change', 'update:checked'],
  setup(props, { emit }) {
    let t4Toggle = null;
    const elRef = ref(null);

    useTooltip(elRef, props);

    const onChange = (event) => {
      emit('change', event);
    };

    watch(
      () => props.checked,
      (newValue) => {
        if (!t4Toggle) return;
        t4Toggle.checked = newValue;
      },
    );

    onMounted(() => {
      t4ready(() => {
        if (!props.init || !elRef.value) return;
        t4Toggle = t4.toggle.create({
          el: elRef.value,
          on: {
            change(toggleInstance) {
              emit('toggle:change', toggleInstance.checked);
              emit('update:checked', toggleInstance.checked);
            },
          },
        });
      });
    });

    onBeforeUnmount(() => {
      if (t4Toggle && t4Toggle.destroy && t4Toggle.$el) {
        t4Toggle.destroy();
      }
      t4Toggle = null;
    });

    const classes = computed(() =>
      classNames(
        'toggle',
        {
          disabled: props.disabled,
        },
        colorClasses(props),
      ),
    );
    return {
      classes,
      elRef,
      t4Toggle,
      onChange,
    };
  },
};
</script>

// src/react/components/toggle.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect.js';
import { classNames, getExtraAttrs, emit } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { t4ready, t4 } from '../shared/t4.js';
import { watchProp } from '../shared/watch-prop.js';
import { useTooltip } from '../shared/use-tooltip.js';

/* dts-imports
import { Toggle } from 'techno4/types';
*/
/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  init? : boolean
  checked? : boolean
  defaultChecked? : boolean
  disabled? : boolean
  readonly? : boolean
  name? : string
  value? : string | number | Array<any>
  tooltip? : string
  tooltipTrigger? : string
  COLOR_PROPS
  onToggleChange? : (...args: any[]) => void
  onChange? : (event?: any) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null; t4Toggle: () => Toggle.Toggle;}>;
  children?: React.ReactNode;
*/

const Toggle = forwardRef((props, ref) => {
  const t4Toggle = useRef(null);
  const {
    className,
    id,
    style,
    init = true,
    checked,
    defaultChecked,
    disabled,
    readonly,
    name,
    value,
  } = props;

  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  const inputElRef = useRef(null);

  const onChange = (event) => {
    emit(props, 'change', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    t4Toggle: () => t4Toggle.current,
  }));

  useTooltip(elRef, props);

  watchProp(checked, (newValue) => {
    if (!t4Toggle.current) return;
    t4Toggle.current.checked = newValue;
  });

  const onToggleChange = (toggleInstance) => {
    emit(props, 'toggleChange', toggleInstance.checked);
  };

  const toggleEvents = (method) => {
    if (!t4Toggle.current) return;
    t4Toggle.current[method]('toggleChange', onToggleChange);
  };

  const onMount = () => {
    t4ready(() => {
      if (!init || !elRef.current) return;
      t4Toggle.current = t4.toggle.create({
        el: elRef.current,
      });
      toggleEvents('on');
    });
  };

  const onDestroy = () => {
    if (t4Toggle.current && t4Toggle.current.destroy && t4Toggle.current.$el) {
      t4Toggle.current.destroy();
    }
    t4Toggle.current = null;
  };

  useIsomorphicLayoutEffect(() => {
    toggleEvents('on');
    if (inputElRef.current) {
      inputElRef.current.addEventListener('change', onChange);
    }
    return () => {
      toggleEvents('off');
      if (inputElRef.current) {
        inputElRef.current.removeEventListener('change', onChange);
      }
    };
  });

  useIsomorphicLayoutEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  const labelClasses = classNames(
    'toggle',
    className,
    {
      disabled,
    },
    colorClasses(props),
  );
  const inputEl = (
    <input
      ref={inputElRef}
      type="checkbox"
      name={name}
      disabled={disabled}
      readOnly={readonly}
      checked={checked}
      defaultChecked={defaultChecked}
      value={value}
      onChange={() => {}}
    />
  );

  return (
    <label id={id} style={style} className={labelClasses} ref={elRef} {...extraAttrs}>
      {inputEl}
      <span className="toggle-icon" />
    </label>
  );
});

Toggle.displayName = 't4-toggle';

export default Toggle;
