// boonker/vue/src/pages/login-screen-page.vue
<template>
  <t4-page no-toolbar no-navbar no-swipeback login-screen>
    <t4-login-screen-title>techno4</t4-login-screen-title>
    <t4-list form>
      <t4-list-input
        label="Username"
        type="text"
        placeholder="Your username"
        :value="username"
        @input="username = $event.target.value"
      ></t4-list-input>
      <t4-list-input
        label="Password"
        type="password"
        placeholder="Your password"
        :value="password"
        @input="password = $event.target.value"
      ></t4-list-input>
    </t4-list>
    <t4-list>
      <t4-list-button @click="signIn">Sign In</t4-list-button>
      <t4-block-footer
        >Some text about login information.<br />Lorem ipsum dolor sit amet, consectetur adipiscing
        elit.</t4-block-footer
      >
    </t4-list>
  </t4-page>
</template>
<script>
import {
  t4Page,
  t4LoginScreenTitle,
  t4List,
  t4ListButton,
  t4BlockFooter,
  t4ListInput,
  t4,
} from 'techno4-vue';

export default {
  components: {
    t4Page,
    t4LoginScreenTitle,
    t4List,
    t4ListButton,
    t4BlockFooter,
    t4ListInput,
  },
  props: {
    t4router: Object,
  },
  data() {
    return {
      username: '',
      password: '',
    };
  },
  methods: {
    signIn() {
      const self = this;
      t4.dialog.alert(`Username: ${self.username}<br>Password: ${self.password}`, () => {
        this.t4router.back();
      });
    },
  },
};
</script>

// boonker/svelte/src/pages/login-screen-page.svelte
<script>
  import {
    t4,
    Page,
    LoginScreenTitle,
    List,
    ListInput,
    ListButton,
    BlockFooter,
  } from 'techno4-svelte';

  export let t4router;

  let username = '';
  let password = '';

  function signIn() {
    t4.dialog.alert(`Username: ${username}<br>Password: ${password}`, () => {
      t4router.back();
    });
  }
</script>

<Page noToolbar noNavbar noSwipeback loginScreen>
  <LoginScreenTitle>techno4</LoginScreenTitle>
  <List form>
    <ListInput
      label="Username"
      type="text"
      placeholder="Your username"
      value={username}
      onInput={(e) => (username = e.target.value)} />
    <ListInput
      label="Password"
      type="password"
      placeholder="Your password"
      value={password}
      onInput={(e) => (password = e.target.value)} />
  </List>
  <List>
    <ListButton onClick={signIn}>Sign In</ListButton>
  </List>
  <BlockFooter>
    Some text about login information.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  </BlockFooter>
</Page>
