// boonker/react/src/pages/routable-modals.jsx
import React from 'react';
import { Navbar, Page, List, ListItem, Block } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Routable Modals" backLink="Back"></Navbar>
    <Block strong>
      <p>In addition to pages, techno4 router allows to load modal components:</p>
    </Block>
    <List>
      <ListItem title="Popup" link="popup/" />
      <ListItem title="Action Sheet" link="actions/" />
    </List>
  </Page>
);

// boonker/svelte/src/pages/routable-modals.svelte
<script>
  import { Navbar, Page, List, ListItem, Block } from 'techno4-svelte';
</script>

<Page>
  <Navbar title="Routable Modals" backLink="Back" />
  <Block strong>
    <p>In addition to pages, techno4 router allows to load modal components:</p>
  </Block>
  <List>
    <ListItem title="Popup" link="popup/" />
    <ListItem title="Action Sheet" link="actions/" />
  </List>
</Page>
