// boonker/react/src/pages/swiper-3d-cube.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="3D Cube" backLink="Back"></Navbar>
    <Swiper className="demo-swiper demo-swiper-cube" effect="cube">
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-1.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-2.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-3.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-4.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-5.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-6.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-7.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-8.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-800x800-9.jpg)',
        }}
      />
    </Swiper>
  </Page>
);

// boonker/svelte/src/pages/swiper-3d-cube.svelte
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-svelte';
</script>

<Page>
  <Navbar title="3D Cube" backLink="Back" />
  <Swiper class="demo-swiper demo-swiper-cube" effect="cube" }>
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-1.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-2.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-3.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-4.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-5.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-6.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-7.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-8.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-800x800-9.jpg)" />
  </Swiper>
</Page>
