// boonker/react/src/pages/swiper-fade.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Fade Effect" backLink="Back"></Navbar>
    <Swiper className="demo-swiper demo-swiper-fade" pagination effect="fade">
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-1024x1024-1.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-1024x1024-2.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-1024x1024-3.jpg)',
        }}
      />
      <SwiperSlide
        style={{
          backgroundImage: 'url(https://cdn.techno4.io/placeholder/people-1024x1024-4.jpg)',
        }}
      />
    </Swiper>
  </Page>
);

// boonker/svelte/src/pages/swiper-fade.svelte
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'techno4-svelte';
</script>

<Page>
  <Navbar title="Fade Effect" backLink="Back" />
  <Swiper class="demo-swiper demo-swiper-fade" pagination effect="fade">
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-1024x1024-1.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-1024x1024-2.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-1024x1024-3.jpg)" />
    <SwiperSlide
      style="background-image: url(https://cdn.techno4.io/placeholder/people-1024x1024-4.jpg)" />
  </Swiper>
</Page>
