// boonker/react/src/pages/tabs.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'techno4-react';

export default () => (
  <Page>
    <Navbar title="Tabs" backLink="Back"></Navbar>
    <List>
      <ListItem link="/tabs-static/" title="Static Tabs" />
      <ListItem link="/tabs-animated/" title="Animated Tabs" />
      <ListItem link="/tabs-swipeable/" title="Swipeable Tabs" />
      <ListItem link="/tabs-routable/" title="Routable Tabs" />
    </List>
  </Page>
);

// boonker/svelte/src/pages/tabs.svelte
<script>
  import { Navbar, Page, List, ListItem } from 'techno4-svelte';
</script>

<Page>
  <Navbar title="Tabs" backLink="Back" />
  <List>
    <ListItem link="/tabs-static/" title="Static Tabs" />
    <ListItem link="/tabs-animated/" title="Animated Tabs" />
    <ListItem link="/tabs-swipeable/" title="Swipeable Tabs" />
    <ListItem link="/tabs-routable/" title="Routable Tabs" />
  </List>
</Page>
