// boonker/vue/src/pages/treeview.vue
<template>
  <t4-page>
    <t4-navbar title="Treeview" back-link="Back" />

    <t4-block-title>Basic tree view</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item label="Item 1">
          <t4-treeview-item label="Sub Item 1">
            <t4-treeview-item label="Sub Sub Item 1" />
            <t4-treeview-item label="Sub Sub Item 2" />
          </t4-treeview-item>
          <t4-treeview-item label="Sub Item 2">
            <t4-treeview-item label="Sub Sub Item 1" />
            <t4-treeview-item label="Sub Sub Item 2" />
          </t4-treeview-item>
        </t4-treeview-item>
        <t4-treeview-item label="Item 2">
          <t4-treeview-item label="Sub Item 1">
            <t4-treeview-item label="Sub Sub Item 1" />
            <t4-treeview-item label="Sub Sub Item 2" />
          </t4-treeview-item>
          <t4-treeview-item label="Sub Item 2">
            <t4-treeview-item label="Sub Sub Item 1" />
            <t4-treeview-item label="Sub Sub Item 2" />
          </t4-treeview-item>
        </t4-treeview-item>
        <t4-treeview-item label="Item 3" />
      </t4-treeview>
    </t4-block>

    <t4-block-title>With icons</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item label="images" icon-t4="folder_fill">
          <t4-treeview-item label="avatar.png" icon-t4="photo_fill" />
          <t4-treeview-item label="background.jpg" icon-t4="photo_fill" />
        </t4-treeview-item>
        <t4-treeview-item label="documents" icon-t4="folder_fill">
          <t4-treeview-item label="cv.docx" icon-t4="doc_text_fill" />
          <t4-treeview-item label="info.docx" icon-t4="doc_text_fill" />
        </t4-treeview-item>
        <t4-treeview-item label=".gitignore" icon-t4="logo_github" />
        <t4-treeview-item label="index.html" icon-t4="doc_text_fill" />
      </t4-treeview>
    </t4-block>

    <t4-block-title>With checkboxes</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item label="images" icon-t4="folder_fill">
          <template #content-start>
            <t4-checkbox
              :checked="Object.values(checkboxes.images).indexOf(false) < 0"
              :indeterminate="
                Object.values(checkboxes.images).indexOf(false) >= 0 &&
                Object.values(checkboxes.images).indexOf(true) >= 0
              "
              @change="
                (e) =>
                  Object.keys(checkboxes.images).forEach(
                    (k) => (checkboxes.images[k] = e.target.checked),
                  )
              "
            />
          </template>
          <t4-treeview-item label="avatar.png" icon-t4="photo_fill">
            <template #content-start>
              <t4-checkbox
                :checked="checkboxes.images['avatar.png']"
                @change="checkboxes.images['avatar.png'] = $event.target.checked"
              />
            </template>
          </t4-treeview-item>
          <t4-treeview-item label="background.jpg" icon-t4="photo_fill">
            <template #content-start>
              <t4-checkbox
                :checked="checkboxes.images['background.jpg']"
                @change="checkboxes.images['background.jpg'] = $event.target.checked"
              />
            </template>
          </t4-treeview-item>
        </t4-treeview-item>
        <t4-treeview-item label="documents" icon-t4="folder_fill">
          <template #content-start>
            <t4-checkbox
              :checked="Object.values(checkboxes.documents).indexOf(false) < 0"
              :indeterminate="
                Object.values(checkboxes.documents).indexOf(false) >= 0 &&
                Object.values(checkboxes.documents).indexOf(true) >= 0
              "
              @change="
                (e) =>
                  Object.keys(checkboxes.documents).forEach(
                    (k) => (checkboxes.documents[k] = e.target.checked),
                  )
              "
            />
          </template>
          <t4-treeview-item label="cv.docx" icon-t4="doc_text_fill">
            <template #content-start>
              <t4-checkbox
                :checked="checkboxes.documents['cv.docx']"
                @change="checkboxes.documents['cv.docx'] = $event.target.checked"
              />
            </template>
          </t4-treeview-item>
          <t4-treeview-item label="info.docx" icon-t4="doc_text_fill">
            <template #content-start>
              <t4-checkbox
                :checked="checkboxes.documents['info.docx']"
                @change="checkboxes.documents['info.docx'] = $event.target.checked"
              />
            </template>
          </t4-treeview-item>
        </t4-treeview-item>
        <t4-treeview-item label=".gitignore" icon-t4="logo_github">
          <template #content-start>
            <t4-checkbox
              :checked="checkboxes['.gitignore']"
              @change="checkboxes['.gitignore'] = $event.target.checked"
            />
          </template>
        </t4-treeview-item>
        <t4-treeview-item label="index.html" icon-t4="doc_text_fill">
          <template #content-start>
            <t4-checkbox
              :checked="checkboxes['index.html']"
              @change="checkboxes['index.html'] = $event.target.checked"
            />
          </template>
        </t4-treeview-item>
      </t4-treeview>
    </t4-block>

    <t4-block-title>Whole item as toggle</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item item-toggle label="images" icon-t4="folder_fill">
          <t4-treeview-item label="avatar.png" icon-t4="photo_fill" />
          <t4-treeview-item label="background.jpg" icon-t4="photo_fill" />
        </t4-treeview-item>
        <t4-treeview-item item-toggle label="documents" icon-t4="folder_fill">
          <t4-treeview-item label="cv.docx" icon-t4="doc_text_fill" />
          <t4-treeview-item label="info.docx" icon-t4="doc_text_fill" />
        </t4-treeview-item>
        <t4-treeview-item label=".gitignore" icon-t4="logo_github" />
        <t4-treeview-item label="index.html" icon-t4="doc_text_fill" />
      </t4-treeview>
    </t4-block>

    <t4-block-title>Selectable</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item
          selectable
          :selected="selectedItem === 'images'"
          label="images"
          icon-t4="folder_fill"
          @click="toggleSelectable($event, 'images')"
        >
          <t4-treeview-item
            selectable
            :selected="selectedItem === 'avatar.png'"
            label="avatar.png"
            icon-t4="photo_fill"
            @click="toggleSelectable($event, 'avatar.png')"
          />
          <t4-treeview-item
            selectable
            :selected="selectedItem === 'background.jpg'"
            label="background.jpg"
            icon-t4="photo_fill"
            @click="toggleSelectable($event, 'background.jpg')"
          />
        </t4-treeview-item>
        <t4-treeview-item
          selectable
          :selected="selectedItem === 'documents'"
          label="documents"
          icon-t4="folder_fill"
          @click="toggleSelectable($event, 'documents')"
        >
          <t4-treeview-item
            selectable
            :selected="selectedItem === 'cv.docx'"
            label="cv.docx"
            icon-t4="doc_text_fill"
            @click="toggleSelectable($event, 'cv.docx')"
          />
          <t4-treeview-item
            selectable
            :selected="selectedItem === 'info.docx'"
            label="info.docx"
            icon-t4="doc_text_fill"
            @click="toggleSelectable($event, 'info.docx')"
          />
        </t4-treeview-item>
        <t4-treeview-item
          selectable
          :selected="selectedItem === '.gitignore'"
          label=".gitignore"
          icon-t4="logo_github"
          @click="toggleSelectable($event, '.gitignore')"
        />
        <t4-treeview-item
          selectable
          :selected="selectedItem === 'index.html'"
          label="index.html"
          icon-t4="doc_text_fill"
          @click="toggleSelectable($event, 'index.html')"
        />
      </t4-treeview>
    </t4-block>

    <t4-block-title>Preload children</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item
          toggle
          load-children
          icon-t4="person_2_fill"
          label="Users"
          @treeview:loadchildren="loadChildren"
        >
          <t4-treeview-item
            v-for="(item, index) in loadedChildren"
            :key="index"
            icon-t4="person_fill"
            :label="item.name"
          />
        </t4-treeview-item>
      </t4-treeview>
    </t4-block>

    <t4-block-title>With links</t4-block-title>
    <t4-block strong class="no-padding-horizontal">
      <t4-treeview>
        <t4-treeview-item icon-t4="square_grid_2x2_fill" item-toggle label="Modals">
          <t4-treeview-item link="/popup/" icon-t4="link" label="Popup" />
          <t4-treeview-item link="/dialog/" icon-t4="link" label="Dialog" />
          <t4-treeview-item link="/action-sheet/" icon-t4="link" label="Action Sheet" />
        </t4-treeview-item>
        <t4-treeview-item icon-t4="square_grid_2x2_fill" item-toggle label="Navigation Bars">
          <t4-treeview-item link="/navbar/" icon-t4="link" label="Navbar" />
          <t4-treeview-item link="/toolbar-tabbar/" icon-t4="link" label="Toolbar & Tabbar" />
        </t4-treeview-item>
      </t4-treeview>
    </t4-block>
  </t4-page>
</template>
<script>
import {
  t4Page,
  t4Navbar,
  t4BlockTitle,
  t4Block,
  t4Treeview,
  t4TreeviewItem,
  t4Checkbox,
} from 'techno4-vue';
import $ from 'dom64';

export default {
  components: {
    t4Page,
    t4Navbar,
    t4BlockTitle,
    t4Block,
    t4Treeview,
    t4TreeviewItem,
    t4Checkbox,
  },
  data() {
    return {
      checkboxes: {
        images: {
          'avatar.png': false,
          'background.jpg': false,
        },
        documents: {
          'cv.docx': false,
          'info.docx': false,
        },
        '.gitignore': false,
        'index.html': false,
      },
      selectedItem: null,
      loadedChildren: [],
    };
  },
  methods: {
    toggleSelectable(e, item) {
      const self = this;
      if ($(e.target).is('.treeview-toggle')) return;
      self.selectedItem = item;
    },
    loadChildren(e, done) {
      const self = this;
      setTimeout(() => {
        // call done() to hide preloader
        done();
        self.loadedChildren = [
          {
            name: 'John Doe',
          },
          {
            name: 'Jane Doe',
          },
          {
            name: 'Calvin Johnson',
          },
        ];
      }, 2000);
    },
  },
};
</script>

// boonker/svelte/src/pages/treeview.svelte
<script>
  import {
    t4,
    Page,
    Navbar,
    BlockTitle,
    Block,
    Treeview,
    TreeviewItem,
    Checkbox,
  } from 'techno4-svelte';

  let checkboxes = {
    images: {
      'avatar.png': false,
      'background.jpg': false,
    },
    documents: {
      'cv.docx': false,
      'info.docx': false,
    },
    '.gitignore': false,
    'index.html': false,
  };
  let selectedItem = null;
  let loadedChildren = [];

  function toggleSelectable(e, item) {
    const $ = t4.$;
    if ($(e.target).is('.treeview-toggle')) return;
    selectedItem = item;
  }

  function loadChildren(done) {
    setTimeout(() => {
      // call done() to hide preloader
      done();
      loadedChildren = [
        {
          name: 'John Doe',
        },
        {
          name: 'Jane Doe',
        },
        {
          name: 'Calvin Johnson',
        },
      ];
    }, 2000);
  }
</script>

<Page>
  <Navbar title="Treeview" backLink="Back" />

  <BlockTitle>Basic tree view</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem label="Item 1">
        <TreeviewItem label="Sub Item 1">
          <TreeviewItem label="Sub Sub Item 1" />
          <TreeviewItem label="Sub Sub Item 2" />
        </TreeviewItem>
        <TreeviewItem label="Sub Item 2">
          <TreeviewItem label="Sub Sub Item 1" />
          <TreeviewItem label="Sub Sub Item 2" />
        </TreeviewItem>
      </TreeviewItem>
      <TreeviewItem label="Item 2">
        <TreeviewItem label="Sub Item 1">
          <TreeviewItem label="Sub Sub Item 1" />
          <TreeviewItem label="Sub Sub Item 2" />
        </TreeviewItem>
        <TreeviewItem label="Sub Item 2">
          <TreeviewItem label="Sub Sub Item 1" />
          <TreeviewItem label="Sub Sub Item 2" />
        </TreeviewItem>
      </TreeviewItem>
      <TreeviewItem label="Item 3" />
    </Treeview>
  </Block>

  <BlockTitle>With icons</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem label="images" icont4="folder_fill">
        <TreeviewItem label="avatar.png" icont4="photo_fill" />
        <TreeviewItem label="background.jpg" icont4="photo_fill" />
      </TreeviewItem>
      <TreeviewItem label="documents" icont4="folder_fill">
        <TreeviewItem label="cv.docx" icont4="doc_text_fill" />
        <TreeviewItem label="info.docx" icont4="doc_text_fill" />
      </TreeviewItem>
      <TreeviewItem label=".gitignore" icont4="logo_github" />
      <TreeviewItem label="index.html" icont4="doc_text_fill" />
    </Treeview>
  </Block>

  <BlockTitle>With checkboxes</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem label="images" icont4="folder_fill">
        <span slot="content-start">
          <Checkbox
            checked={Object.values(checkboxes.images).indexOf(false) < 0}
            indeterminate={Object.values(checkboxes.images).indexOf(false) >= 0 && Object.values(checkboxes.images).indexOf(true) >= 0}
            onChange={(e) => {
              Object.keys(checkboxes.images).forEach((k) => (checkboxes.images[k] = e.target.checked));
              checkboxes = checkboxes;
            }} />
        </span>
        <TreeviewItem label="avatar.png" icont4="photo_fill" toggle={false}>
          <span slot="content-start">
            <Checkbox
              checked={checkboxes.images['avatar.png']}
              onChange={(e) => {
                checkboxes.images['avatar.png'] = e.target.checked;
                checkboxes = checkboxes;
              }} />
          </span>
        </TreeviewItem>
        <TreeviewItem label="background.jpg" icont4="photo_fill" toggle={false}>
          <span slot="content-start">
            <Checkbox
              checked={checkboxes.images['background.jpg']}
              onChange={(e) => {
                checkboxes.images['background.jpg'] = e.target.checked;
                checkboxes = checkboxes;
              }} />
          </span>
        </TreeviewItem>
      </TreeviewItem>
      <TreeviewItem label="documents" icont4="folder_fill">
        <span slot="content-start">
          <Checkbox
            checked={Object.values(checkboxes.documents).indexOf(false) < 0}
            indeterminate={Object.values(checkboxes.documents).indexOf(false) >= 0 && Object.values(checkboxes.documents).indexOf(true) >= 0}
            onChange={(e) => {
              Object.keys(checkboxes.documents).forEach((k) => (checkboxes.documents[k] = e.target.checked));
              checkboxes = checkboxes;
            }} />
        </span>
        <TreeviewItem label="cv.docx" icont4="doc_text_fill" toggle={false}>
          <span slot="content-start">
            <Checkbox
              checked={checkboxes.documents['cv.docx']}
              onChange={(e) => {
                checkboxes.documents['cv.docx'] = e.target.checked;
                checkboxes = checkboxes;
              }} />
          </span>
        </TreeviewItem>
        <TreeviewItem label="info.docx" icont4="doc_text_fill" toggle={false}>
          <span slot="content-start">
            <Checkbox
              checked={checkboxes.documents['info.docx']}
              onChange={(e) => {
                checkboxes.documents['info.docx'] = e.target.checked;
                checkboxes = checkboxes;
              }} />
          </span>
        </TreeviewItem>
      </TreeviewItem>
      <TreeviewItem label=".gitignore" icont4="logo_github" toggle={false}>
        <span slot="content-start">
          <Checkbox
            checked={checkboxes['.gitignore']}
            onChange={(e) => {
              checkboxes['.gitignore'] = e.target.checked;
              checkboxes = checkboxes;
            }} />
        </span>
      </TreeviewItem>
      <TreeviewItem label="index.html" icont4="doc_text_fill" toggle={false}>
        <span slot="content-start">
          <Checkbox
            checked={checkboxes['index.html']}
            onChange={(e) => {
              checkboxes['index.html'] = e.target.checked;
              checkboxes = checkboxes;
            }} />
        </span>
      </TreeviewItem>
    </Treeview>
  </Block>

  <BlockTitle>Whole item as toggle</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem itemToggle label="images" icont4="folder_fill">
        <TreeviewItem label="avatar.png" icont4="photo_fill" />
        <TreeviewItem label="background.jpg" icont4="photo_fill" />
      </TreeviewItem>
      <TreeviewItem itemToggle label="documents" icont4="folder_fill">
        <TreeviewItem label="cv.docx" icont4="doc_text_fill" />
        <TreeviewItem label="info.docx" icont4="doc_text_fill" />
      </TreeviewItem>
      <TreeviewItem label=".gitignore" icont4="logo_github" />
      <TreeviewItem label="index.html" icont4="doc_text_fill" />
    </Treeview>
  </Block>

  <BlockTitle>Selectable</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem
        selectable
        selected={selectedItem === 'images'}
        label="images"
        icont4="folder_fill"
        onClick={(e) => toggleSelectable(e, 'images')}>
        <TreeviewItem
          selectable
          selected={selectedItem === 'avatar.png'}
          label="avatar.png"
          icont4="photo_fill"
          onClick={(e) => toggleSelectable(e, 'avatar.png')} />
        <TreeviewItem
          selectable
          selected={selectedItem === 'background.jpg'}
          label="background.jpg"
          icont4="photo_fill"
          onClick={(e) => toggleSelectable(e, 'background.jpg')} />
      </TreeviewItem>
      <TreeviewItem
        selectable
        selected={selectedItem === 'documents'}
        label="documents"
        icont4="folder_fill"
        onClick={(e) => toggleSelectable(e, 'documents')}>
        <TreeviewItem
          selectable
          selected={selectedItem === 'cv.docx'}
          label="cv.docx"
          icont4="doc_text_fill"
          onClick={(e) => toggleSelectable(e, 'cv.docx')} />
        <TreeviewItem
          selectable
          selected={selectedItem === 'info.docx'}
          label="info.docx"
          icont4="doc_text_fill"
          onClick={(e) => toggleSelectable(e, 'info.docx')} />
      </TreeviewItem>
      <TreeviewItem
        selectable
        selected={selectedItem === '.gitignore'}
        label=".gitignore"
        icont4="logo_github"
        onClick={(e) => toggleSelectable(e, '.gitignore')} />
      <TreeviewItem
        selectable
        selected={selectedItem === 'index.html'}
        label="index.html"
        icont4="doc_text_fill"
        onClick={(e) => toggleSelectable(e, 'index.html')} />
    </Treeview>
  </Block>

  <BlockTitle>Preload children</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem
        toggle
        loadChildren
        icont4="person_2_fill"
        label="Users"
        onTreeviewLoadChildren={(el, done) => loadChildren(done)}>
        {#each loadedChildren as item, index (index)}
          <TreeviewItem icont4="person_fill" label={item.name} />
        {/each}
      </TreeviewItem>
    </Treeview>
  </Block>

  <BlockTitle>With links</BlockTitle>
  <Block strong class="no-padding-horizontal">
    <Treeview>
      <TreeviewItem icont4="square_grid_2x2_fill" itemToggle label="Modals">
        <TreeviewItem link="/popup/" icont4="link" label="Popup" />
        <TreeviewItem link="/dialog/" icont4="link" label="Dialog" />
        <TreeviewItem link="/action-sheet/" icont4="link" label="Action Sheet" />
      </TreeviewItem>
      <TreeviewItem icont4="square_grid_2x2_fill" itemToggle label="Navigation Bars">
        <TreeviewItem link="/navbar/" icont4="link" label="Navbar" />
        <TreeviewItem link="/toolbar-tabbar/" icont4="link" label="Toolbar & Tabbar" />
      </TreeviewItem>
    </Treeview>
  </Block>
</Page>
